using System.Collections.Generic;

namespace Tools28.Localization
{
    internal static class StringsCN
    {
        internal static readonly Dictionary<string, string> All = new Dictionary<string, string>
        {
            // === Ribbon: Panel Names ===
            { "Ribbon.Panel.GridBubble", "轴号 开/关" },
            { "Ribbon.Panel.SheetView", "图纸·视图" },
            { "Ribbon.Panel.3DView", "3D视图" },
            { "Ribbon.Panel.Annotation", "注释·详图" },
            { "Ribbon.Panel.Structural", "色分" },
            { "Ribbon.Panel.Quantity", "数量算出" },
            { "Ribbon.Panel.Excel", "Excel" },
            { "Ribbon.Panel.Settings", "设置" },

            // === Ribbon: GridBubble ===
            { "Ribbon.GridBubble.Both", "两端" },
            { "Ribbon.GridBubble.Both.Tip", "在两端显示轴网/标高符号" },
            { "Ribbon.GridBubble.Left", "左端" },
            { "Ribbon.GridBubble.Left.Tip", "仅在左端显示轴网/标高符号" },
            { "Ribbon.GridBubble.Right", "右端" },
            { "Ribbon.GridBubble.Right.Tip", "仅在右端显示轴网/标高符号" },

            // === Ribbon: Sheet/View ===
            { "Ribbon.Sheet.Create", "批量\n创建" },
            { "Ribbon.Sheet.Create.Tip", "指定标题栏批量创建图纸" },
            { "Ribbon.Viewport.Copy", "视口\n复制位置" },
            { "Ribbon.Viewport.Copy.Tip", "复制图纸上的视口位置" },
            { "Ribbon.Viewport.Paste", "视口\n粘贴位置" },
            { "Ribbon.Viewport.Paste.Tip", "将复制的视口位置粘贴到其他图纸" },
            { "Ribbon.CropBox.Copy", "裁剪\n区域复制" },
            { "Ribbon.CropBox.Copy.Tip", "复制视图的裁剪区域" },
            { "Ribbon.CropBox.Paste", "裁剪\n区域粘贴" },
            { "Ribbon.CropBox.Paste.Tip", "将复制的裁剪区域粘贴到其他视图" },

            // === Ribbon: 3D View ===
            { "Ribbon.View.Copy", "复制视点" },
            { "Ribbon.View.Copy.Tip", "复制3D视图的视点" },
            { "Ribbon.View.Paste", "粘贴视点" },
            { "Ribbon.View.Paste.Tip", "将复制的视点粘贴到其他3D视图" },
            { "Ribbon.SectionBox.Copy", "剖面框\n复制" },
            { "Ribbon.SectionBox.Copy.Tip", "复制3D视图的剖面框" },
            { "Ribbon.SectionBox.Paste", "剖面框\n粘贴" },
            { "Ribbon.SectionBox.Paste.Tip", "将复制的剖面框粘贴到其他3D视图" },

            // === Ribbon: Annotation ===
            { "Ribbon.RoomTag", "房间标签\n自动放置" },
            { "Ribbon.RoomTag.Tip", "按指定方向和间距自动放置房间标签" },
            { "Ribbon.FilledRegion", "填充区域\n拆分·合并" },
            { "Ribbon.FilledRegion.Tip", "拆分或合并已放置的填充区域" },

            // === Ribbon: Structural ===
            { "Ribbon.BeamUnder", "梁底\n色分" },
            { "Ribbon.BeamUnder.Tip", "自动计算天花板视图中的梁底标高并按标高色分显示" },
            { "Ribbon.BeamTop", "梁顶\n色分" },
            { "Ribbon.BeamTop.Tip", "从参数获取梁顶标高并按标高色分显示" },
            { "Ribbon.FireProtection", "防火涂层\n色分" },
            { "Ribbon.FireProtection.Tip", "自动检测防火涂层范围并创建按类型色分的填充区域" },

            // === Ribbon: Quantity ===
            { "Ribbon.Formwork", "模板" },
            { "Ribbon.Formwork.Tip", "从结构模型自动计算模板数量（面积），并输出到 Excel / Revit 汇总视图 / 色分3D视图" },

            // === Ribbon: Excel ===
            { "Ribbon.Excel.Export", "Excel\n导出" },
            { "Ribbon.Excel.Export.Tip", "将参数导出到Excel" },
            { "Ribbon.Excel.Import", "Excel\n导入" },
            { "Ribbon.Excel.Import.Tip", "从Excel导入参数" },

            // === Ribbon: Settings ===
            { "Ribbon.Settings.Lang.Tip", "切换界面显示语言 (JP / US / CN)" },
            { "Ribbon.Settings.About", "关于" },
            { "Ribbon.Settings.About.Tip", "显示 28 Tools 版本信息" },
            { "Ribbon.Settings.Manual", "手册" },
            { "Ribbon.Settings.Manual.Tip", "在浏览器中打开 28 Tools 手册" },
            { "Ribbon.Settings.Lang.JP.Tip", "日本語に切り替えます" },
            { "Ribbon.Settings.Lang.US.Tip", "Switch to English" },
            { "Ribbon.Settings.Lang.CN.Tip", "切换为中文" },

            // === Common ===
            { "Common.Error", "错误" },
            { "Common.Warning", "警告" },
            { "Common.Confirm", "确认" },
            { "Common.Complete", "完成" },
            { "Common.OK", "确定" },
            { "Common.Cancel", "取消" },
            { "Common.Next", "下一步" },
            { "Common.Back", "上一步" },
            { "Common.Execute", "执行" },
            { "Common.Create", "创建" },
            { "Common.Search", "搜索" },
            { "Common.InputError", "输入错误" },
            { "Common.ProcessComplete", "处理完成" },
            { "Common.StepIndicator", "步骤 {0} / {1}  {2}" },

            // === Application.cs ===
            { "App.StartupFailed", "插件启动失败。\n{0}" },

            // === About ===
            { "About.Title", "关于 28 Tools" },
            { "About.Message", "28 Tools\n版本: {0}\n有效期至: {1} {2}\n\nRevit 业务效率化插件" },
            { "About.RemainingSuffix", "(剩余 {0} 天)" },
            { "About.ExpiredSuffix", "(已过期)" },

            // === SheetCreation Dialog ===
            { "Sheet.Title", "批量创建图纸" },
            { "Sheet.SelectTitleBlock", "选择标题栏:" },
            { "Sheet.Count", "创建数量:" },
            { "Sheet.CountHint", "※ 请输入1～100的数值" },
            { "Sheet.DrawingNo", "图号:" },
            { "Sheet.DrawingNoHint", "※ 留空则无图号（例: D-停车, A-栋等）" },
            { "Sheet.NoTitleBlock", "项目中未加载标题栏族。" },
            { "Sheet.SelectTitleBlockWarn", "请选择标题栏。" },
            { "Sheet.CountRange", "创建数量必须在1～100的范围内。" },

            // === FilledRegion Dialog ===
            { "FilledRegion.Title", "填充区域 拆分/合并" },
            { "FilledRegion.Operation", "操作" },
            { "FilledRegion.Split", "拆分（将多区域的填充区域拆分为单独区域）" },
            { "FilledRegion.Merge", "合并（将多个填充区域合并为一个）" },
            { "FilledRegion.Pattern", "填充图案" },
            { "FilledRegion.SelectPattern", "请选择合并后的填充图案：" },
            { "FilledRegion.SelectFirst", "请先选择填充区域再执行此命令。" },
            { "FilledRegion.NoneSelected", "未选择填充区域。\n请先选择填充区域再执行此命令。" },
            { "FilledRegion.NoneAvailable", "没有可拆分或合并的填充区域。\n\n• 拆分: 请选择具有多个区域的填充区域\n• 合并: 请选择多个填充区域" },
            { "FilledRegion.SelectOperation", "请选择操作（拆分或合并）。" },
            { "FilledRegion.SelectPatternWarn", "请选择填充图案。" },
            { "FilledRegion.ProcessError", "处理过程中发生错误。\n\n{0}" },
            { "FilledRegion.InfoSplit", "已选择: {0}个区域（可拆分: {1}个, 共{2}个区域）" },
            { "FilledRegion.InfoMerge", "已选择: {0}个区域（共{1}个区域）→ 合并为1个区域" },
            { "FilledRegion.InfoGeneral", "已选择: {0}个区域" },
            { "FilledRegion.SplitResult", "已将{0}个区域拆分为{1}个独立区域。" },
            { "FilledRegion.MergeResult", "已将{0}个区域合并为1个区域。" },

            // === RoomTag Dialog ===
            { "RoomTag.Title", "房间标签自动配置" },
            { "RoomTag.ViewName", "视图名:" },
            { "RoomTag.ViewFamilyType", "视图族类型:" },
            { "RoomTag.FloorPlan", "装修表__平面图" },
            { "RoomTag.CeilingPlan", "装修表__天花板图" },
            { "RoomTag.TagFamilyType", "标签族类型:" },
            { "RoomTag.TagSpacing", "标签间距 (mm):" },
            { "RoomTag.RoomList", "房间列表:" },
            { "RoomTag.MoveUp", "上移" },
            { "RoomTag.MoveDown", "下移" },
            { "RoomTag.Delete", "删除" },
            { "RoomTag.UnclosedHint", "*表示未闭合房间" },
            { "RoomTag.Preview", "配置预览:" },
            { "RoomTag.IncRows", "增加行数" },
            { "RoomTag.DecRows", "减少行数" },
            { "RoomTag.OpenSheet", "请在打开图纸视图的状态下执行。" },
            { "RoomTag.NoViewport", "无法获取视口。" },
            { "RoomTag.NoView", "无法获取视口的视图。" },
            { "RoomTag.NoRooms", "所选视口内未找到房间。" },
            { "RoomTag.NoViewType", "未选择视图族类型。" },
            { "RoomTag.NoTagType", "未选择标签族类型。" },
            { "RoomTag.NoLayout", "无法获取配置设置。" },
            { "RoomTag.GenFailed", "房间标签生成失败。" },
            { "RoomTag.GenError", "生成房间标签时发生错误。\n{0}" },
            { "RoomTag.Done", "房间标签自动配置完成。\n\n视图名: {0}\n放置数量: {1}个" },
            { "RoomTag.EnterViewName", "请输入视图名。" },
            { "RoomTag.SelectRooms", "未选择房间。" },
            { "RoomTag.SelectTagType", "请选择标签族类型。" },
            { "RoomTag.InvalidSpacing", "标签间距请输入0以上的数值。" },

            // === BeamTopLevel Dialog ===
            { "BeamTop.Title", "梁顶色分" },
            { "BeamTop.Step1", "步骤 1 / 3  基本设置" },
            { "BeamTop.ViewInfo", "视图信息" },
            { "BeamTop.ViewName", "视图名:" },
            { "BeamTop.BeamCount", "梁数量:" },
            { "BeamTop.RefLevel", "参照标高:" },
            { "BeamTop.TextTypeSetting", "文字类型设置" },
            { "BeamTop.LegendTextType", "图例文字类型:" },
            { "BeamTop.LabelTextType", "梁标签文字类型:" },
            { "BeamTop.TextTypeHint", "※ 图例使用制图视图文字，梁标签在平面视图梁上显示" },
            { "BeamTop.ParamSelect", "梁顶标高参数选择" },
            { "BeamTop.ParamHint", "※ 请为每个族选择用作梁顶标高（相对参照标高偏移）的参数" },
            { "BeamTop.Summary", "处理概要" },
            { "BeamTop.ProcessContent", "处理内容" },
            { "BeamTop.SharedParam", "创建/绑定共享参数" },
            { "BeamTop.GetValue", "获取/写入梁顶标高值" },
            { "BeamTop.CreateFilter", "自动创建过滤器并色分" },
            { "BeamTop.CreateLegend", "创建图例制图视图" },
            { "BeamTop.ExistingFilter", "现有过滤器" },
            { "BeamTop.OverwriteFilter", "覆盖现有「梁顶_」过滤器" },
            { "BeamTop.OverwriteHint", "※ 取消勾选则保留现有过滤器" },
            { "BeamTop.StepName1", "基本设置" },
            { "BeamTop.StepName2", "梁顶标高参数选择" },
            { "BeamTop.StepName3", "处理确认" },
            { "BeamTop.NotPlanView", "当前视图不是平面视图或结构平面。\n请在平面视图或结构平面中执行。" },
            { "BeamTop.ViewTemplate", "视图模板确认" },
            { "BeamTop.ViewTemplateMsg", "已设置视图模板。\n创建过滤器需要解除模板。\n\n是否解除模板？" },
            { "BeamTop.NoBeams", "视图中未找到梁（结构框架）。" },
            { "BeamTop.NoRefLevel", "无法获取视图的参照标高。" },
            { "BeamTop.DoneTitle", "梁顶色分 - 完成" },

            // === BeamUnderLevel Dialog ===
            { "BeamUnder.Title", "梁底色分" },
            { "BeamUnder.Step1", "步骤 1 / 4  标高和图例设置" },
            { "BeamUnder.ViewInfo", "视图信息" },
            { "BeamUnder.ViewName", "视图名:" },
            { "BeamUnder.BeamCount", "梁数量:" },
            { "BeamUnder.TextTypeSetting", "文字类型设置" },
            { "BeamUnder.LegendTextType", "图例文字类型:" },
            { "BeamUnder.LabelTextType", "梁标签文字类型:" },
            { "BeamUnder.TextTypeHint", "※ 图例使用制图视图文字，梁标签在天花板视图梁上显示" },
            { "BeamUnder.LevelSetting", "标高设置" },
            { "BeamUnder.RefLevel", "参照标高:" },
            { "BeamUnder.UpperLevel", "上位标高:" },
            { "BeamUnder.FloorHeight", "层高:" },
            { "BeamUnder.LevelHint", "※ 以参照标高为基准计算梁底标高" },
            { "BeamUnder.HeightParam", "梁高参数选择" },
            { "BeamUnder.HeightParamHint", "※ 请为每个族选择用作梁高的参数" },
            { "BeamUnder.TopParam", "梁顶标高参数选择" },
            { "BeamUnder.TopParamHint", "※ 请为每个族选择用作梁顶标高（相对参照标高偏移）的参数" },
            { "BeamUnder.Summary", "处理概要" },
            { "BeamUnder.ProcessContent", "处理内容" },
            { "BeamUnder.SharedParam", "创建/绑定共享参数" },
            { "BeamUnder.CalcValue", "计算/写入梁底标高值" },
            { "BeamUnder.CreateFilter", "自动创建过滤器并色分" },
            { "BeamUnder.CreateLegend", "创建图例制图视图" },
            { "BeamUnder.ExistingFilter", "现有过滤器" },
            { "BeamUnder.OverwriteFilter", "覆盖现有「梁底_」过滤器" },
            { "BeamUnder.OverwriteHint", "※ 取消勾选则保留现有过滤器" },
            { "BeamUnder.StepName1", "标高和图例设置" },
            { "BeamUnder.StepName2", "梁高参数选择" },
            { "BeamUnder.StepName3", "梁顶标高参数选择" },
            { "BeamUnder.StepName4", "处理确认" },
            { "BeamUnder.NotCeiling", "当前视图不是天花板平面。\n请在天花板平面中执行。" },
            { "BeamUnder.ViewTemplate", "视图模板确认" },
            { "BeamUnder.ViewTemplateMsg", "已设置视图模板。\n创建过滤器需要解除模板。\n\n是否解除模板？" },
            { "BeamUnder.NoBeams", "视图中未找到梁（结构框架）。" },
            { "BeamUnder.NoRefLevel", "无法获取视图的参照标高。" },
            { "BeamUnder.NoUpperLevel", "未找到高于参照标高的标高。" },
            { "BeamUnder.DoneTitle", "梁底色分 - 完成" },

            // === FireProtection Dialog ===
            { "Fire.Title", "防火涂层 色分" },
            { "Fire.Step1", "步骤 1 / 3  基本设置" },
            { "Fire.ParamLabel", "防火涂层参数" },
            { "Fire.ParamHint", "※ 自动检测包含「防火涂层」的参数" },
            { "Fire.DetectedTypes", "检测到的防火涂层类型" },
            { "Fire.ColorHint", "※ 点击色块可更改颜色" },
            { "Fire.OffsetSetting", "填充区域偏移设置" },
            { "Fire.CommonOffset", "统一偏移" },
            { "Fire.IndividualOffset", "按类型单独偏移" },
            { "Fire.Mm", " mm" },
            { "Fire.OffsetHint", "※ 距梁边缘的距离（mm）" },
            { "Fire.BeamFace", "▽ 梁面" },
            { "Fire.ColumnSetting", "柱 防火涂层设置" },
            { "Fire.ColumnDistA", "A: 柱中心距离:" },
            { "Fire.ColumnWidthB", "B: 外侧宽度:" },
            { "Fire.ColumnHint", "※ 从柱中心到A，再向外B宽度" },
            { "Fire.Column", "柱" },
            { "Fire.DisplaySetting", "显示设置" },
            { "Fire.LineStyle", "边界线样式:" },
            { "Fire.FillPattern", "填充区域图案:" },
            { "Fire.LegendTextType", "图例文字类型:" },
            { "Fire.Summary", "处理概要" },
            { "Fire.ProcessContent", "处理内容" },
            { "Fire.CreateTypes", "按防火涂层类型创建填充区域类型" },
            { "Fire.AutoPlace", "在构件周围自动放置填充区域（重叠部分合并）" },
            { "Fire.CreateLegend", "创建图例制图视图" },
            { "Fire.ExistingLabel", "现有防火涂层" },
            { "Fire.Overwrite", "覆盖现有「防火涂层_」填充区域和图例" },
            { "Fire.StepName1", "基本设置" },
            { "Fire.StepName2", "偏移·显示设置" },
            { "Fire.StepName3", "处理确认" },
            { "Fire.NoViewOnSheet", "图纸上没有对应的视图（平面、天花板、结构、剖面）。" },
            { "Fire.WrongView", "请在平面视图、天花板平面、结构平面、剖面或图纸中执行。" },
            { "Fire.NoElements", "视图中未找到梁（结构框架）或柱（结构柱）。" },
            { "Fire.DoneTitle", "防火涂层色分 - 完成" },
            { "Fire.DoneMsg", "处理完成。\n\n目标视图数: {0}\n填充区域数: {1}" },
            { "Fire.Foreground", "前景" },
            { "Fire.Background", "背景" },
            { "Fire.ParamDetected", "※ 检测到 {0} 个参数" },
            { "Fire.ParamDetectedSuffix", "（检测到{0}件）" },
            { "Fire.ParamNotFound", "※ 未找到包含「防火涂层」的参数" },
            { "Fire.NoParamValues", "没有设置防火涂层参数值的构件。\n请检查参数。" },
            { "Fire.CategoryBeam", "梁" },
            { "Fire.CategoryBeamColumn", "梁·柱" },
            { "Fire.SummaryView", "视图: {0}" },
            { "Fire.SummaryCategory", "目标类别: {0}" },
            { "Fire.SummaryParam", "防火涂层参数: {0}" },
            { "Fire.SummaryNone", "无" },
            { "Fire.SummaryTypes", "检测到的类型: {0}" },
            { "Fire.SummaryOffset", "  - {0}（偏移: {1}mm）" },
            { "Fire.SummaryBorder", "边界线: {0}" },
            { "Fire.SummaryPattern", "填充图案: {0}" },

            // === ExcelExport Dialog ===
            { "Export.Title", "Excel导出" },
            { "Export.Category", "选择类别" },
            { "Export.Parameter", "参数" },
            { "Export.Output", "输出" },
            { "Export.AddToOutput", "添加到输出" },
            { "Export.RemoveFromOutput", "从输出中删除" },
            { "Export.MoveUp", "上移" },
            { "Export.MoveDown", "下移" },
            { "Export.SeparateSheets", "将输出Excel按类别分成工作表" },
            { "Export.RestoreSettings", "恢复" },
            { "Export.LoadSettings", "加载" },
            { "Export.SaveSettings", "保存" },
            { "Export.SettingsSaved", "设置已保存。" },
            { "Export.SettingsSaveTitle", "保存设置" },
            { "Export.SettingsSaveFailed", "保存设置失败。\n{0}" },
            { "Export.SettingsLoadFailed", "加载设置失败。\n{0}" },
            { "Export.SelectParams", "请选择要输出的参数。" },
            { "Export.SelectCategory", "请选择类别。" },
            { "Export.ParamPrefixLegend", "I- : 实例（图元）参数\nT- : 类型参数" },
            { "Export.Scope.WindowTitle", "Excel导出" },
            { "Export.Scope.Title", "选择导出范围" },
            { "Export.Scope.Description", "请选择要导出的元素范围。" },
            { "Export.Scope.Project", "整个项目的元素" },
            { "Export.Scope.View", "当前视图中的元素" },
            { "Export.Scope.Selection", "当前选中的元素" },

            // === ExcelImport Dialog ===
            { "Import.Title", "Excel导入" },
            { "Import.ExcelFile", "Excel文件" },
            { "Import.OpenFile", "已打开的文件" },
            { "Import.Browse", "浏览..." },
            { "Import.SheetInfo", "工作表信息" },
            { "Import.SelectFile", "请选择Excel文件" },
            { "Import.Preview", "更改预览" },
            { "Import.ColElementId", "元素ID" },
            { "Import.ColCategory", "类别" },
            { "Import.ColParameter", "参数" },
            { "Import.ColCurrentValue", "当前值" },
            { "Import.ColNewValue", "新值" },
            { "Import.Execute", "执行导入" },
            { "Import.ResultTitle", "导入结果" },
            { "Import.NoOpenFile", "未找到已打开的Excel文件。" },
            { "Import.ReadFailed", "读取文件失败。\n{0}" },

            // === FormworkCalculator Dialog ===
            { "Formwork.Title", "模板数量计算" },
            { "Formwork.Scope.Header", "计算范围" },
            { "Formwork.Scope.Project", "整个项目" },
            { "Formwork.Scope.View", "当前视图中可见的构件" },
            { "Formwork.Scope.SelectedViews", "选中的视图" },
            { "Formwork.Group.Header", "汇总分组" },
            { "Formwork.Group.Category", "按部位（柱·梁·墙·板·基础·楼梯·屋顶）" },
            { "Formwork.Group.Zone", "按施工区" },
            { "Formwork.Group.Type", "按模板种类" },
            { "Formwork.Group.ParamName", "参数名称:" },
            { "Formwork.Output.Header", "输出设置" },
            { "Formwork.Output.Excel", "导出到 Excel" },
            { "Formwork.Output.Schedule", "创建明细表" },
            { "Formwork.Output.View3D", "创建色分 3D 视图" },
            { "Formwork.Output.Sheet", "创建图纸" },
            { "Formwork.Color.Header", "色分方案" },
            { "Formwork.Color.Category", "按部位" },
            { "Formwork.Color.Zone", "按施工区" },
            { "Formwork.Color.Type", "按模板种类" },
            { "Formwork.Option.Header", "选项" },
            { "Formwork.Option.ShowDeducted", "同时显示扣除面" },
            { "Formwork.Option.IncludeLinks", "包括链接模型" },
            { "Formwork.NeedZoneParam", "要按施工区分组时，请输入施工区参数名称。" },
            { "Formwork.NeedTypeParam", "要按模板种类分组时，请输入模板种类参数名称。" },
            { "Formwork.SaveExcelTitle", "模板数量 - Excel 保存位置" },
            { "Formwork.NoElements", "未找到目标构件。" },
            { "Formwork.CalcFailed", "模板数量计算时发生错误。\n{0}" },
            { "Formwork.ExcelFailed", "Excel 导出时发生错误。\n{0}" },
            { "Formwork.ViewFailed", "创建视图时发生错误。\n{0}" },
            { "Formwork.DoneTitle", "模板数量计算 - 完成" },
            { "Formwork.DoneMsg", "处理已完成。\n\n构件数: {0}\n模板面积: {1:F2} ㎡\n扣除面积: {2:F2} ㎡\n倾斜面（不纳入）: {3:F2} ㎡" },
            { "Formwork.ExcelAt", "Excel 输出: {0}" },
            { "Formwork.ErrorCount", "错误·注释: {0} 条" },
            { "Formwork.Fatal", "模板数量计算时发生严重错误。\n{0}" },
            { "Formwork.ShapesCreated", "已创建模板面对象: {0} 个（在其他视图中自动隐藏）" },
            { "Formwork.ScheduleCreated", "已创建明细表「模板数量汇总」" },
            { "Formwork.SummaryScheduleCreated", "已创建汇总明细表「模板数量汇总_合计」（构件删除时自动更新）" },
            { "Formwork.SheetCreated", "已创建图纸「{0} - {1}」（自动放置三维视图与明细表）" },
            { "Formwork.SteelExcluded", "已排除 {0} 个钢构件（无需模板）" },
            { "Formwork.DeckSlabExcluded", "已排除 {0} 个压型钢板楼板（类型名称包含 \"DS\"）" },
            { "Formwork.WallSweepExcluded", "已排除 {0} 个墙饰条/凹槽（无需模板）" },
            { "Formwork.SteelStairExcluded", "已排除 {0} 个钢楼梯（类型/材质包含钢相关关键字）" },
            { "Formwork.LgsExcluded", "已排除 {0} 个 LGS 墙（含石膏板层、不含混凝土层的墙）" },
            { "Formwork.LinkedIncluded", "已从链接模型包含 {0} 个构件（链接实例：{1} 个）" },
            { "Formwork.ExcludedFilterNote", "（排除的构件在分析三维视图中由「型枠_除外」过滤器隐藏，开启过滤器即可查看）" },
            { "Formwork.UpdateConfirm.Title", "模板数量算出 - 更新确认" },
            { "Formwork.UpdateConfirm.MainInstruction", "检测到既有的模板输出" },
            { "Formwork.UpdateConfirm.Content", "所选源视图对应的分析三维视图或明细表已存在。请选择执行模式。" },
            { "Formwork.UpdateConfirm.UpdateLabel", "更新（保留图纸布局）" },
            { "Formwork.UpdateConfirm.UpdateDesc", "仅使用最新模型刷新目标分析三维视图与明细表。图纸、合计明细表与其他视图保持不变。" },
            { "Formwork.UpdateConfirm.RecreateLabel", "重新生成（重建所有输出）" },
            { "Formwork.UpdateConfirm.RecreateDesc", "删除并重新创建所有输出，包括图纸与合计明细表。" },

            // === Excel 导出类别名称 ===
            { "Category.Walls", "墙" },
            { "Category.Floors", "楼板" },
            { "Category.Roofs", "屋顶" },
            { "Category.Ceilings", "天花板" },
            { "Category.Doors", "门" },
            { "Category.Windows", "窗" },
            { "Category.Stairs", "楼梯" },
            { "Category.Ramps", "坡道" },
            { "Category.Railings", "栏杆" },
            { "Category.Columns", "柱" },
            { "Category.StructuralColumns", "结构柱" },
            { "Category.StructuralFraming", "结构框架" },
            { "Category.StructuralFoundation", "结构基础" },
            { "Category.StructuralTruss", "结构桁架" },
            { "Category.Rebar", "钢筋" },
            { "Category.Stiffener", "加劲肋" },
            { "Category.Rooms", "房间" },
            { "Category.Areas", "区域" },
            { "Category.Furniture", "家具" },
            { "Category.FurnitureSystems", "家具系统" },
            { "Category.Casework", "橱柜" },
            { "Category.GenericModel", "常规模型" },
            { "Category.SpecialityEquipment", "专用设备" },
            { "Category.Site", "场地" },
            { "Category.Topography", "地形" },
            { "Category.Planting", "植物" },
            { "Category.Parking", "停车场" },
            { "Category.Entourage", "配景" },
            { "Category.Mass", "体量" },
            { "Category.CurtainPanels", "幕墙嵌板" },
            { "Category.CurtainMullions", "幕墙竖梃" },
            { "Category.Ducts", "风管" },
            { "Category.DuctFittings", "风管管件" },
            { "Category.DuctAccessories", "风管附件" },
            { "Category.AirTerminals", "风口" },
            { "Category.Pipes", "管道" },
            { "Category.PipeFittings", "管件" },
            { "Category.PipeAccessories", "管道附件" },
            { "Category.Conduits", "线管" },
            { "Category.CableTrays", "电缆桥架" },
            { "Category.ElectricalEquipment", "电气设备" },
            { "Category.ElectricalFixtures", "电气装置" },
            { "Category.LightingFixtures", "照明设备" },
            { "Category.LightingDevices", "照明装置" },
            { "Category.MechanicalEquipment", "机械设备" },
            { "Category.PlumbingFixtures", "卫浴装置" },
            { "Category.Sprinklers", "喷头" },
            { "Category.FireAlarmDevices", "火警装置" },
            { "Category.DataDevices", "数据装置" },
            { "Category.CommunicationDevices", "通讯装置" },
            { "Category.SecurityDevices", "安防装置" },
            { "Category.NurseCallDevices", "护士呼叫装置" },
            { "Category.TelephoneDevices", "电话装置" },
            { "Category.Grids", "轴网" },
            { "Category.Levels", "标高" },
            { "Category.Sheets", "图纸" },
            { "Category.Views", "视图" },
            { "Category.Viewports", "视口" },
            { "Category.TextNotes", "文字注释" },
            { "Category.GenericAnnotation", "常规注释" },
            { "Category.RevisionClouds", "修订云" },
            { "Category.Schedules", "明细表" },

            { "Expiry.Title", "28 Tools - 使用期限已到" },
            { "Expiry.ExpiredMessage", "此版本的使用期限（{0}）已过。\n\n请从以下链接下载最新版本：\nhttps://28tools.com/addins.html" },
            { "Expiry.WarningTitle", "28 Tools - 即将到期" },
            { "Expiry.WarningMessage", "此版本将在 {0} 天后到期（到期日：{1}）。\n\n建议尽快更新到最新版本：\nhttps://28tools.com/addins.html" },

            // 填充图案导入导出
            { "Ribbon.FillPatternIO", "填充图案\n导入导出" },
            { "Ribbon.FillPatternIO.Tip", "列出当前模型中的填充图案，并以.pat文件形式导出/导入。" },
            { "FillPatternIO.Title", "填充图案导入导出" },
            { "FillPatternIO.PatternType", "图案类型" },
            { "FillPatternIO.Search", "搜索:" },
            { "FillPatternIO.ColPreview", "图案" },
            { "FillPatternIO.Model", "模型" },
            { "FillPatternIO.Drafting", "绘图" },
            { "FillPatternIO.SelectAll", "全选" },
            { "FillPatternIO.ClearAll", "全部清除" },
            { "FillPatternIO.ColName", "名称" },
            { "FillPatternIO.ColType", "类型" },
            { "FillPatternIO.ColGrid", "网格数" },
            { "FillPatternIO.Unit", "单位:" },
            { "FillPatternIO.Export", "导出" },
            { "FillPatternIO.Import", "导入" },
            { "FillPatternIO.Close", "关闭" },
            { "FillPatternIO.CountInfo", "共 {0} 项 / 已选 {1} 项" },
            { "FillPatternIO.PatFilter", "图案文件 (*.pat)|*.pat|所有文件 (*.*)|*.*" },
            { "FillPatternIO.SelectFolder", "请选择导出目标文件夹（每个图案将保存为单独的.pat文件）。" },
            { "FillPatternIO.NoSelection", "请从列表中选择要导出的图案。" },
            { "FillPatternIO.OnlySolid", "所选图案均为实体填充。实体填充无法导出为.pat文件。" },
            { "FillPatternIO.NoDocument", "没有活动文档。请先打开rvt文件后再执行。" },
            { "FillPatternIO.TransImport", "导入填充图案" },
            { "FillPatternIO.ExportDone", "已导出 {0} 个图案。" },
            { "FillPatternIO.SolidSkipped", "（已跳过 {0} 个实体填充。）" },
            { "FillPatternIO.ImportDone", "已导入 {0} 个图案。" },
            { "FillPatternIO.DupSkipped", "（已跳过 {0} 个同名的现有图案。）" },
            { "FillPatternIO.InvalidSkipped", "（已跳过 {0} 个无效图案。）" },
            { "FillPatternIO.ExportError", "导出时发生错误：\n{0}" },
            { "FillPatternIO.ImportError", "导入时发生错误：\n{0}" },
            { "FillPatternIO.ProcessError", "处理时发生错误：\n{0}" },

            // === ParameterCleanup（参数整理）===
            { "Ribbon.Panel.Parameter", "参数" },
            { "Ribbon.ParamCleanup", "参数整理" },
            { "Ribbon.ParamCleanup.Tip", "列出项目中可删除的参数（项目／共享／全局），高亮同名参数，检查每个参数是否有值，并删除未使用（空）的参数。为避免在大型模型上卡顿，值检查仅在需要时执行，并支持进度显示和中止。" },
            { "ParamCleanup.Title", "参数整理" },
            { "ParamCleanup.Description", "列出项目中可删除的参数，并自动检查每个参数是否有元素填入了值。同名参数将被高亮显示。选择并删除未使用（空）的参数。" },
            { "ParamCleanup.SortHint", "点击列标题排序" },
            { "ParamCleanup.Search", "搜索:" },
            { "ParamCleanup.DuplicateOnly", "仅同名" },
            { "ParamCleanup.EmptyOnly", "仅空值" },
            { "ParamCleanup.SelectEmpty", "全选空值" },
            { "ParamCleanup.Filter.Kind", "类别:" },
            { "ParamCleanup.Filter.All", "全部" },
            { "ParamCleanup.Filter.SortAsc", "升序排列" },
            { "ParamCleanup.Filter.SortDesc", "降序排列" },
            { "ParamCleanup.Filter.SelectAll", "(全选)" },
            { "ParamCleanup.Filter.Blank", "(空白)" },
            { "ParamCleanup.Filter.Clear", "清除" },
            { "ParamCleanup.FilterHint", "排序 / 筛选" },
            { "ParamCleanup.Col.Select", "选择" },
            { "ParamCleanup.Col.Name", "参数名称" },
            { "ParamCleanup.Col.Kind", "类别" },
            { "ParamCleanup.Col.Scope", "绑定" },
            { "ParamCleanup.Col.Categories", "对象类别" },
            { "ParamCleanup.Col.ScheduleRef", "明细表引用" },
            { "ParamCleanup.Col.Value", "值" },
            { "ParamCleanup.Btn.Check", "检查值" },
            { "ParamCleanup.Btn.Cancel", "中止" },
            { "ParamCleanup.Btn.Delete", "删除所选参数" },
            { "ParamCleanup.Btn.Close", "关闭" },
            { "ParamCleanup.Kind.Project", "项目" },
            { "ParamCleanup.Kind.Shared", "共享" },
            { "ParamCleanup.Kind.Global", "全局" },
            { "ParamCleanup.Scope.Instance", "实例" },
            { "ParamCleanup.Scope.Type", "类型" },
            { "ParamCleanup.State.Unchecked", "未检查" },
            { "ParamCleanup.State.Checking", "检查中…" },
            { "ParamCleanup.State.HasValue", "有值" },
            { "ParamCleanup.State.Empty", "空（未使用）" },
            { "ParamCleanup.State.NotApplicable", "未绑定" },
            { "ParamCleanup.Tip.HasValue", "至少有一个元素填入了值（使用中）。" },
            { "ParamCleanup.Tip.Empty", "已检查绑定类别的所有元素，没有任何元素填入值（未使用）。" },
            { "ParamCleanup.Tip.Unchecked", "尚未检查。可用「检查值」进行判断。" },
            { "ParamCleanup.Tip.Checking", "检查中…" },
            { "ParamCleanup.Tip.NotBound", "未绑定到任何类别，无法判断是否有值（仅存在定义）。仍可删除。" },
            { "ParamCleanup.Tip.Global", "全局参数的当前值。" },
            { "ParamCleanup.Status.Scanning", "检查中: {0}" },
            { "ParamCleanup.Status.Done", "检查完成。" },
            { "ParamCleanup.Status.DoneSummary", "检查完成 — 有值: {0} 项 / 空: {1} 项" },
            { "ParamCleanup.Status.Cancelled", "已中止检查。" },
            { "ParamCleanup.Count.Summary", "共 {0} 项 / 显示 {1} 项 / 已选 {2} 项" },
            { "ParamCleanup.Count.Progress", "{0} / {1} 项" },
            { "ParamCleanup.Txn", "删除未使用的参数" },
            { "ParamCleanup.NoDoc", "没有活动的项目。" },
            { "ParamCleanup.NoSelection.Msg", "未选择要删除的参数。" },
            { "ParamCleanup.NotChecked.Msg", "请先执行「检查值」。" },
            { "ParamCleanup.Confirm.Title", "删除参数" },
            { "ParamCleanup.Confirm.Main", "将删除所选的 {0} 个参数。此操作无法撤销。" },
            { "ParamCleanup.Confirm.Content", "注意：即使参数为空，如果它被视图过滤器、明细表、标记或公式引用，删除后可能导致这些功能失效。删除前请确认内容。\n\n确定要删除吗？" },
            { "ParamCleanup.Result.Title", "删除结果" },
            { "ParamCleanup.Result.Msg", "已删除: {0} 项 / 失败: {1} 项" },
            { "ParamCleanup.Result.Error", "删除时发生错误：\n{0}" },
        };
    }
}
