using System.Collections.Generic;

namespace Tools28.Localization
{
    internal static class StringsEN
    {
        internal static readonly Dictionary<string, string> All = new Dictionary<string, string>
        {
            // === Ribbon: Panel Names ===
            { "Ribbon.Panel.GridBubble", "Grid Bubble" },
            { "Ribbon.Panel.SheetView", "Sheet / View" },
            { "Ribbon.Panel.3DView", "3D View" },
            { "Ribbon.Panel.Annotation", "Annotation" },
            { "Ribbon.Panel.Structural", "Color Code" },
            { "Ribbon.Panel.Excel", "Excel" },
            { "Ribbon.Panel.Settings", "Settings" },

            // === Ribbon: GridBubble ===
            { "Ribbon.GridBubble.Both", "Both" },
            { "Ribbon.GridBubble.Both.Tip", "Show grid/level bubbles on both ends" },
            { "Ribbon.GridBubble.Left", "Left" },
            { "Ribbon.GridBubble.Left.Tip", "Show grid/level bubbles on left end only" },
            { "Ribbon.GridBubble.Right", "Right" },
            { "Ribbon.GridBubble.Right.Tip", "Show grid/level bubbles on right end only" },

            // === Ribbon: Sheet/View ===
            { "Ribbon.Sheet.Create", "Batch\nCreate" },
            { "Ribbon.Sheet.Create.Tip", "Create multiple sheets with a specified title block" },
            { "Ribbon.Viewport.Copy", "Viewport\nCopy Pos" },
            { "Ribbon.Viewport.Copy.Tip", "Copy viewport position on a sheet" },
            { "Ribbon.Viewport.Paste", "Viewport\nPaste Pos" },
            { "Ribbon.Viewport.Paste.Tip", "Paste copied viewport position to another sheet" },
            { "Ribbon.CropBox.Copy", "Crop\nRegion Copy" },
            { "Ribbon.CropBox.Copy.Tip", "Copy the crop region of a view" },
            { "Ribbon.CropBox.Paste", "Crop\nRegion Paste" },
            { "Ribbon.CropBox.Paste.Tip", "Paste copied crop region to another view" },

            // === Ribbon: 3D View ===
            { "Ribbon.View.Copy", "Copy View" },
            { "Ribbon.View.Copy.Tip", "Copy the 3D view orientation" },
            { "Ribbon.View.Paste", "Paste View" },
            { "Ribbon.View.Paste.Tip", "Paste copied orientation to another 3D view" },
            { "Ribbon.SectionBox.Copy", "Section Box\nCopy" },
            { "Ribbon.SectionBox.Copy.Tip", "Copy the section box of a 3D view" },
            { "Ribbon.SectionBox.Paste", "Section Box\nPaste" },
            { "Ribbon.SectionBox.Paste.Tip", "Paste copied section box to another 3D view" },

            // === Ribbon: Annotation ===
            { "Ribbon.RoomTag", "Room Tag\nAuto Place" },
            { "Ribbon.RoomTag.Tip", "Auto-place room tags with specified direction and spacing" },
            { "Ribbon.FilledRegion", "Filled Region\nSplit/Merge" },
            { "Ribbon.FilledRegion.Tip", "Split or merge placed filled regions" },

            // === Ribbon: Structural ===
            { "Ribbon.BeamUnder", "Beam Bottom\nColor Code" },
            { "Ribbon.BeamUnder.Tip", "Calculate beam bottom level and apply color coding by level" },
            { "Ribbon.BeamTop", "Beam Top\nColor Code" },
            { "Ribbon.BeamTop.Tip", "Get beam top level from parameters and apply color coding by level" },
            { "Ribbon.FireProtection", "Fireproofing\nColor Code" },
            { "Ribbon.FireProtection.Tip", "Auto-detect fireproofing zones and create color-coded filled regions" },

            // === Ribbon: Excel ===
            { "Ribbon.Excel.Export", "Excel\nExport" },
            { "Ribbon.Excel.Export.Tip", "Export parameters to Excel" },
            { "Ribbon.Excel.Import", "Excel\nImport" },
            { "Ribbon.Excel.Import.Tip", "Import parameters from Excel" },

            // === Ribbon: Settings ===
            { "Ribbon.Settings.Lang.Tip", "Switch UI display language (JP / US / CN)" },
            { "Ribbon.Settings.About", "About" },
            { "Ribbon.Settings.About.Tip", "Show 28 Tools version information" },
            { "Ribbon.Settings.Manual", "Manual" },
            { "Ribbon.Settings.Manual.Tip", "Open 28 Tools manual in browser" },
            { "Ribbon.Settings.Lang.JP.Tip", "日本語に切り替えます" },
            { "Ribbon.Settings.Lang.US.Tip", "Switch to English" },
            { "Ribbon.Settings.Lang.CN.Tip", "切换为中文" },

            // === Common ===
            { "Common.Error", "Error" },
            { "Common.Warning", "Warning" },
            { "Common.Confirm", "Confirm" },
            { "Common.Complete", "Complete" },
            { "Common.OK", "OK" },
            { "Common.Cancel", "Cancel" },
            { "Common.Next", "Next" },
            { "Common.Back", "Back" },
            { "Common.Execute", "Execute" },
            { "Common.Create", "Create" },
            { "Common.Search", "Search" },
            { "Common.InputError", "Input Error" },
            { "Common.ProcessComplete", "Process Complete" },
            { "Common.StepIndicator", "Step {0} / {1}  {2}" },

            // === Application.cs ===
            { "App.StartupFailed", "Failed to start add-in.\n{0}" },

            // === About ===
            { "About.Title", "About 28 Tools" },
            { "About.Message", "28 Tools\nVersion: {0}\n\nProductivity add-in for Revit" },

            // === SheetCreation Dialog ===
            { "Sheet.Title", "Batch Sheet Creation" },
            { "Sheet.SelectTitleBlock", "Select title block:" },
            { "Sheet.Count", "Number of sheets:" },
            { "Sheet.CountHint", "* Enter a value between 1 and 100" },
            { "Sheet.DrawingNo", "Drawing No:" },
            { "Sheet.DrawingNoHint", "* Leave blank for no number (e.g. D-parking, A-bldg)" },
            { "Sheet.NoTitleBlock", "No title block family is loaded in the project." },
            { "Sheet.SelectTitleBlockWarn", "Please select a title block." },
            { "Sheet.CountRange", "Number of sheets must be between 1 and 100." },

            // === FilledRegion Dialog ===
            { "FilledRegion.Title", "Filled Region Split/Merge" },
            { "FilledRegion.Operation", "Operation" },
            { "FilledRegion.Split", "Split (separate multi-area regions into individual regions)" },
            { "FilledRegion.Merge", "Merge (combine multiple regions into one)" },
            { "FilledRegion.Pattern", "Fill Pattern" },
            { "FilledRegion.SelectPattern", "Select fill pattern for merged region:" },
            { "FilledRegion.SelectFirst", "Select filled regions before running this command." },
            { "FilledRegion.NoneSelected", "No filled regions selected.\nSelect filled regions before running this command." },
            { "FilledRegion.NoneAvailable", "No filled regions available for split or merge.\n\n• Split: Select regions with multiple areas\n• Merge: Select multiple regions" },
            { "FilledRegion.SelectOperation", "Please select an operation (Split or Merge)." },
            { "FilledRegion.SelectPatternWarn", "Please select a fill pattern." },
            { "FilledRegion.ProcessError", "An error occurred during processing.\n\n{0}" },
            { "FilledRegion.InfoSplit", "Selected: {0} regions (splittable: {1}, total {2} areas)" },
            { "FilledRegion.InfoMerge", "Selected: {0} regions (total {1} areas) → merge into 1 region" },
            { "FilledRegion.InfoGeneral", "Selected: {0} regions" },
            { "FilledRegion.SplitResult", "Split {0} regions into {1} independent regions." },
            { "FilledRegion.MergeResult", "Merged {0} regions into 1 region." },

            // === RoomTag Dialog ===
            { "RoomTag.Title", "Room Tag Auto Placement" },
            { "RoomTag.ViewName", "View name:" },
            { "RoomTag.ViewFamilyType", "View family type:" },
            { "RoomTag.FloorPlan", "Finish Schedule - Floor Plan" },
            { "RoomTag.CeilingPlan", "Finish Schedule - Ceiling Plan" },
            { "RoomTag.TagFamilyType", "Tag family type:" },
            { "RoomTag.TagSpacing", "Tag spacing (mm):" },
            { "RoomTag.RoomList", "Room list:" },
            { "RoomTag.MoveUp", "Move up" },
            { "RoomTag.MoveDown", "Move down" },
            { "RoomTag.Delete", "Delete item" },
            { "RoomTag.UnclosedHint", "* indicates unclosed rooms" },
            { "RoomTag.Preview", "Placement preview:" },
            { "RoomTag.IncRows", "Increase rows" },
            { "RoomTag.DecRows", "Decrease rows" },
            { "RoomTag.OpenSheet", "Please open a sheet view before running this command." },
            { "RoomTag.NoViewport", "Could not get the viewport." },
            { "RoomTag.NoView", "Could not get the view from the viewport." },
            { "RoomTag.NoRooms", "No rooms found in the selected viewport." },
            { "RoomTag.NoViewType", "No view family type selected." },
            { "RoomTag.NoTagType", "No tag family type selected." },
            { "RoomTag.NoLayout", "Could not get layout settings." },
            { "RoomTag.GenFailed", "Failed to generate room tags." },
            { "RoomTag.GenError", "An error occurred while generating room tags.\n{0}" },
            { "RoomTag.Done", "Room tag auto-placement complete.\n\nView name: {0}\nTags placed: {1}" },
            { "RoomTag.EnterViewName", "Please enter a view name." },
            { "RoomTag.SelectRooms", "No rooms selected." },
            { "RoomTag.SelectTagType", "Please select a tag family type." },
            { "RoomTag.InvalidSpacing", "Tag spacing must be 0 or greater." },

            // === BeamTopLevel Dialog ===
            { "BeamTop.Title", "Beam Top Color Coding" },
            { "BeamTop.Step1", "Step 1 / 3  Basic Settings" },
            { "BeamTop.ViewInfo", "View Information" },
            { "BeamTop.ViewName", "View name:" },
            { "BeamTop.BeamCount", "Beam count:" },
            { "BeamTop.RefLevel", "Reference level:" },
            { "BeamTop.TextTypeSetting", "Text Type Settings" },
            { "BeamTop.LegendTextType", "Legend text type:" },
            { "BeamTop.LabelTextType", "Beam label text type:" },
            { "BeamTop.TextTypeHint", "* Legend uses drafting view text, label displays on beams in plan view" },
            { "BeamTop.ParamSelect", "Beam Top Level Parameter Selection" },
            { "BeamTop.ParamHint", "* Select the parameter representing the beam top level offset from the reference level for each family" },
            { "BeamTop.Summary", "Process Summary" },
            { "BeamTop.ProcessContent", "Process Details" },
            { "BeamTop.SharedParam", "Create/bind shared parameters" },
            { "BeamTop.GetValue", "Get/write beam top level values" },
            { "BeamTop.CreateFilter", "Auto-create filters and apply color coding" },
            { "BeamTop.CreateLegend", "Create legend drafting view" },
            { "BeamTop.ExistingFilter", "Existing Filters" },
            { "BeamTop.OverwriteFilter", "Overwrite existing \"BeamTop_\" filters" },
            { "BeamTop.OverwriteHint", "* Uncheck to keep existing filters" },
            { "BeamTop.StepName1", "Basic Settings" },
            { "BeamTop.StepName2", "Beam Top Level Parameter Selection" },
            { "BeamTop.StepName3", "Process Confirmation" },
            { "BeamTop.NotPlanView", "Active view is not a floor plan or structural plan.\nPlease open a floor plan or structural plan." },
            { "BeamTop.ViewTemplate", "View Template" },
            { "BeamTop.ViewTemplateMsg", "A view template is applied.\nThe template must be removed to create filters.\n\nRemove the template?" },
            { "BeamTop.NoBeams", "No beams (structural framing) found in the view." },
            { "BeamTop.NoRefLevel", "Cannot get the reference level of the view." },
            { "BeamTop.DoneTitle", "Beam Top Color Coding - Complete" },

            // === BeamUnderLevel Dialog ===
            { "BeamUnder.Title", "Beam Bottom Color Coding" },
            { "BeamUnder.Step1", "Step 1 / 4  Level & Legend Settings" },
            { "BeamUnder.ViewInfo", "View Information" },
            { "BeamUnder.ViewName", "View name:" },
            { "BeamUnder.BeamCount", "Beam count:" },
            { "BeamUnder.TextTypeSetting", "Text Type Settings" },
            { "BeamUnder.LegendTextType", "Legend text type:" },
            { "BeamUnder.LabelTextType", "Beam label text type:" },
            { "BeamUnder.TextTypeHint", "* Legend uses drafting view text, label displays on beams in ceiling plan" },
            { "BeamUnder.LevelSetting", "Level Settings" },
            { "BeamUnder.RefLevel", "Reference level:" },
            { "BeamUnder.UpperLevel", "Upper level:" },
            { "BeamUnder.FloorHeight", "Floor height:" },
            { "BeamUnder.LevelHint", "* Beam bottom level is calculated based on the reference level" },
            { "BeamUnder.HeightParam", "Beam Height Parameter Selection" },
            { "BeamUnder.HeightParamHint", "* Select the parameter representing beam height for each family" },
            { "BeamUnder.TopParam", "Beam Top Level Parameter Selection" },
            { "BeamUnder.TopParamHint", "* Select the parameter representing the beam top level offset from the reference level for each family" },
            { "BeamUnder.Summary", "Process Summary" },
            { "BeamUnder.ProcessContent", "Process Details" },
            { "BeamUnder.SharedParam", "Create/bind shared parameters" },
            { "BeamUnder.CalcValue", "Calculate/write beam bottom level values" },
            { "BeamUnder.CreateFilter", "Auto-create filters and apply color coding" },
            { "BeamUnder.CreateLegend", "Create legend drafting view" },
            { "BeamUnder.ExistingFilter", "Existing Filters" },
            { "BeamUnder.OverwriteFilter", "Overwrite existing \"BeamBottom_\" filters" },
            { "BeamUnder.OverwriteHint", "* Uncheck to keep existing filters" },
            { "BeamUnder.StepName1", "Level & Legend Settings" },
            { "BeamUnder.StepName2", "Beam Height Parameter Selection" },
            { "BeamUnder.StepName3", "Beam Top Level Parameter Selection" },
            { "BeamUnder.StepName4", "Process Confirmation" },
            { "BeamUnder.NotCeiling", "Active view is not a ceiling plan.\nPlease open a ceiling plan." },
            { "BeamUnder.ViewTemplate", "View Template" },
            { "BeamUnder.ViewTemplateMsg", "A view template is applied.\nThe template must be removed to create filters.\n\nRemove the template?" },
            { "BeamUnder.NoBeams", "No beams (structural framing) found in the view." },
            { "BeamUnder.NoRefLevel", "Cannot get the reference level of the view." },
            { "BeamUnder.NoUpperLevel", "No levels found above the reference level." },
            { "BeamUnder.DoneTitle", "Beam Bottom Color Coding - Complete" },

            // === FireProtection Dialog ===
            { "Fire.Title", "Fireproofing Color Coding" },
            { "Fire.Step1", "Step 1 / 3  Basic Settings" },
            { "Fire.ParamLabel", "Fireproofing Parameter" },
            { "Fire.ParamHint", "* Auto-detects parameters containing \"fireproofing\"" },
            { "Fire.DetectedTypes", "Detected Fireproofing Types" },
            { "Fire.ColorHint", "* Click color square to change" },
            { "Fire.OffsetSetting", "Filled Region Offset Settings" },
            { "Fire.CommonOffset", "Common offset" },
            { "Fire.IndividualOffset", "Individual offset per type" },
            { "Fire.Mm", " mm" },
            { "Fire.OffsetHint", "* Distance from beam edge (mm)" },
            { "Fire.BeamFace", "▽ Beam face" },
            { "Fire.ColumnSetting", "Column Fireproofing Settings" },
            { "Fire.ColumnDistA", "A: Distance from column center:" },
            { "Fire.ColumnWidthB", "B: Outer width:" },
            { "Fire.ColumnHint", "* Distance A from column center, then width B outward" },
            { "Fire.Column", "Column" },
            { "Fire.DisplaySetting", "Display Settings" },
            { "Fire.LineStyle", "Boundary line style:" },
            { "Fire.FillPattern", "Fill region pattern:" },
            { "Fire.LegendTextType", "Legend text type:" },
            { "Fire.Summary", "Process Summary" },
            { "Fire.ProcessContent", "Process Details" },
            { "Fire.CreateTypes", "Create filled region type per fireproofing type" },
            { "Fire.AutoPlace", "Auto-place filled regions around elements (merge overlaps)" },
            { "Fire.CreateLegend", "Create legend drafting view" },
            { "Fire.ExistingLabel", "Existing Fireproofing" },
            { "Fire.Overwrite", "Overwrite existing \"Fireproofing_\" filled regions and legend" },
            { "Fire.StepName1", "Basic Settings" },
            { "Fire.StepName2", "Offset & Display Settings" },
            { "Fire.StepName3", "Process Confirmation" },
            { "Fire.NoViewOnSheet", "No applicable views (plan, ceiling, structural, section) found on this sheet." },
            { "Fire.WrongView", "Please run in a floor plan, ceiling plan, structural plan, section, or sheet view." },
            { "Fire.NoElements", "No beams (structural framing) or columns (structural columns) found in the view." },
            { "Fire.DoneTitle", "Fireproofing Color Coding - Complete" },
            { "Fire.DoneMsg", "Process complete.\n\nTarget views: {0}\nFilled regions: {1}" },
            { "Fire.Foreground", "Fore" },
            { "Fire.Background", "Back" },
            { "Fire.ParamDetected", "* {0} parameter(s) detected" },
            { "Fire.ParamDetectedSuffix", " ({0} detected)" },
            { "Fire.ParamNotFound", "* No parameters containing \"fireproofing\" found" },
            { "Fire.NoParamValues", "No elements have values set for the fireproofing parameter.\nPlease check the parameters." },
            { "Fire.CategoryBeam", "Beams" },
            { "Fire.CategoryBeamColumn", "Beams & Columns" },
            { "Fire.SummaryView", "View: {0}" },
            { "Fire.SummaryCategory", "Target category: {0}" },
            { "Fire.SummaryParam", "Fireproofing parameter: {0}" },
            { "Fire.SummaryNone", "None" },
            { "Fire.SummaryTypes", "Detected types: {0}" },
            { "Fire.SummaryOffset", "  - {0} (Offset: {1}mm)" },
            { "Fire.SummaryBorder", "Border line: {0}" },
            { "Fire.SummaryPattern", "Fill pattern: {0}" },

            // === ExcelExport Dialog ===
            { "Export.Title", "Excel Export" },
            { "Export.Category", "Select Category" },
            { "Export.Parameter", "Parameters" },
            { "Export.Output", "Output" },
            { "Export.AddToOutput", "Add to output" },
            { "Export.RemoveFromOutput", "Remove from output" },
            { "Export.MoveUp", "Move up" },
            { "Export.MoveDown", "Move down" },
            { "Export.SeparateSheets", "Separate sheets by category" },
            { "Export.RestoreSettings", "Restore" },
            { "Export.LoadSettings", "Load" },
            { "Export.SaveSettings", "Save" },
            { "Export.SettingsSaved", "Settings saved." },
            { "Export.SettingsSaveTitle", "Save Settings" },
            { "Export.SettingsSaveFailed", "Failed to save settings.\n{0}" },
            { "Export.SettingsLoadFailed", "Failed to load settings.\n{0}" },
            { "Export.SelectParams", "Please select parameters to export." },
            { "Export.SelectCategory", "Please select a category." },
            { "Export.Scope.WindowTitle", "Excel Export" },
            { "Export.Scope.Title", "Select Export Scope" },
            { "Export.Scope.Description", "Choose which elements to export." },
            { "Export.Scope.Project", "Entire project" },
            { "Export.Scope.View", "Elements in current view" },
            { "Export.Scope.Selection", "Currently selected elements" },

            // === ExcelImport Dialog ===
            { "Import.Title", "Excel Import" },
            { "Import.ExcelFile", "Excel File" },
            { "Import.OpenFile", "Open File" },
            { "Import.Browse", "Browse..." },
            { "Import.SheetInfo", "Sheet Info" },
            { "Import.SelectFile", "Select an Excel file" },
            { "Import.Preview", "Change Preview" },
            { "Import.ColElementId", "Element ID" },
            { "Import.ColCategory", "Category" },
            { "Import.ColParameter", "Parameter" },
            { "Import.ColCurrentValue", "Current Value" },
            { "Import.ColNewValue", "New Value" },
            { "Import.Execute", "Import" },
            { "Import.ResultTitle", "Import Result" },
            { "Import.NoOpenFile", "No open Excel file found." },
            { "Import.ReadFailed", "Failed to read the file.\n{0}" },
        };
    }
}
