using System.Collections.Generic;

namespace Tools28.Localization
{
    internal static class StringsJP
    {
        internal static readonly Dictionary<string, string> All = new Dictionary<string, string>
        {
            // === Ribbon: Panel Names ===
            { "Ribbon.Panel.GridBubble", "符号 ON/OFF" },
            { "Ribbon.Panel.SheetView", "シート・ビュー" },
            { "Ribbon.Panel.3DView", "3Dビュー" },
            { "Ribbon.Panel.Annotation", "注釈・詳細" },
            { "Ribbon.Panel.Structural", "色分け" },
            { "Ribbon.Panel.Quantity", "数量算出" },
            { "Ribbon.Panel.Excel", "Excel連携" },
            { "Ribbon.Panel.Settings", "設定" },

            // === Ribbon: GridBubble ===
            { "Ribbon.GridBubble.Both", "両端" },
            { "Ribbon.GridBubble.Both.Tip", "通り芯・レベルの符号を両端に表示します" },
            { "Ribbon.GridBubble.Left", "左端" },
            { "Ribbon.GridBubble.Left.Tip", "通り芯・レベルの符号を左端のみに表示します" },
            { "Ribbon.GridBubble.Right", "右端" },
            { "Ribbon.GridBubble.Right.Tip", "通り芯・レベルの符号を右端のみに表示します" },

            // === Ribbon: Sheet/View ===
            { "Ribbon.Sheet.Create", "一括作成" },
            { "Ribbon.Sheet.Create.Tip", "図枠を指定して複数のシートを一括作成します" },
            { "Ribbon.Viewport.Copy", "位置コピー" },
            { "Ribbon.Viewport.Copy.Tip", "シート上のビューポート位置をコピーします" },
            { "Ribbon.Viewport.Paste", "位置ペースト" },
            { "Ribbon.Viewport.Paste.Tip", "コピーしたビューポート位置を他のシートに適用します" },
            { "Ribbon.CropBox.Copy", "領域コピー" },
            { "Ribbon.CropBox.Copy.Tip", "ビューのトリミング領域をコピーします" },
            { "Ribbon.CropBox.Paste", "領域ペースト" },
            { "Ribbon.CropBox.Paste.Tip", "コピーしたトリミング領域を他のビューに適用します" },

            // === Ribbon: 3D View ===
            { "Ribbon.View.Copy", "視点コピー" },
            { "Ribbon.View.Copy.Tip", "3Dビューの視点をコピーします" },
            { "Ribbon.View.Paste", "視点ペースト" },
            { "Ribbon.View.Paste.Tip", "コピーした視点を他の3Dビューに適用します" },
            { "Ribbon.SectionBox.Copy", "切断ボックス\nコピー" },
            { "Ribbon.SectionBox.Copy.Tip", "3Dビューの切断ボックスをコピーします" },
            { "Ribbon.SectionBox.Paste", "切断ボックス\nペースト" },
            { "Ribbon.SectionBox.Paste.Tip", "コピーした切断ボックスを他の3Dビューに適用します" },

            // === Ribbon: Annotation ===
            { "Ribbon.RoomTag", "部屋タグ\n自動配置" },
            { "Ribbon.RoomTag.Tip", "ビューポート内の部屋タグを指定方向・間隔で自動配置します" },
            { "Ribbon.Room3DColor", "部屋3D\n色分け" },
            { "Ribbon.Room3DColor.Tip", "部屋の立体を生成し、3Dビューで部屋のみを表示して色分けします" },

            // === Room3DColor ===
            { "Room3D.Title", "部屋 3D 色分け" },
            { "Room3D.Header", "部屋を 3D ビューで色分け" },
            { "Room3D.BasisLabel", "色分け基準" },
            { "Room3D.BasisName", "部屋名ごと" },
            { "Room3D.BasisLevel", "レベル（階）ごと" },
            { "Room3D.BasisParameter", "指定パラメータの値ごと" },
            { "Room3D.BasisPerRoom", "部屋ごとに個別" },
            { "Room3D.BasisAll", "すべて（全部屋を同色）" },
            { "Room3D.AllGroupLabel", "すべての部屋" },
            { "Room3D.ParameterLabel", "対象パラメータ" },
            { "Room3D.PreviewLabel", "グループと色" },
            { "Room3D.ColorHint", "※ 色の四角をクリックすると変更できます" },
            { "Room3D.OutputLabel", "出力設定" },
            { "Room3D.ViewNameLabel", "作成する3Dビュー名" },
            { "Room3D.WorksetNameLabel", "ワークセット名（ワークシェア時）" },
            { "Room3D.DefaultViewName", "部屋3D色分け" },
            { "Room3D.DeleteExisting", "既存の部屋色分けソリッドを削除して作り直す" },
            { "Room3D.CreateLegend", "凡例（製図ビュー）を作成する" },
            { "Room3D.NoRooms", "配置済みの部屋が見つかりません。面積を持つ部屋を配置してから実行してください。" },
            { "Room3D.NoGroups", "（対象となる部屋がありません）" },
            { "Room3D.GroupRow", "{0}（{1}部屋）" },
            { "Room3D.LegendViewName", "部屋3D色分け 凡例" },
            { "Room3D.LegendTitle", "部屋3D色分け 凡例" },
            { "Room3D.LegendRow", "- {0}（{1}部屋）" },
            { "Room3D.DoneTitle", "部屋3D色分け 完了" },
            { "Room3D.DoneMessage", "処理が完了しました。\n\nビュー: {0}\n色分けした部屋数: {1}\nグループ数: {2}" },
            { "Room3D.DoneLegendCreated", "凡例ビュー: 作成しました" },
            { "Room3D.DoneLegendSkipped", "凡例ビュー: 作成をスキップしました" },
            { "Room3D.DoneFailure", "※ 立体を生成できなかった部屋: {0} 件（非囲繞または体積0の可能性）" },
            { "Room3D.VolumeEnabledNote", "※ 体積計算が無効だったため有効化しました。" },
            { "Room3D.WorksetName", "部屋3D色分け" },
            { "Room3D.DoneWorkset", "ワークセット: 「{0}」に配置し、他のビューでは非表示にしました" },
            { "Room3D.DoneHiddenOtherViews", "他ビュー表示: このモデルはワークセット未使用のため、他のビューでは要素を非表示にしました" },
            { "Room3D.Error", "部屋3D色分け処理中にエラーが発生しました。\n\n{0}" },
            { "Ribbon.FilledRegion", "塗潰し領域\n分割･統合" },
            { "Ribbon.FilledRegion.Tip", "配置されている塗潰領域を分割/統合します" },

            // === Ribbon: Structural ===
            { "Ribbon.BeamUnder", "梁下端\n色分け" },
            { "Ribbon.BeamUnder.Tip", "天井伏図の梁下端レベルを自動算出し、レベル別に色分け表示します" },
            { "Ribbon.BeamTop", "梁天端\n色分け" },
            { "Ribbon.BeamTop.Tip", "平面ビューの梁天端レベルをパラメータから取得し、レベル別に色分け表示します" },
            { "Ribbon.FireProtection", "耐火被覆\n色分け" },
            { "Ribbon.FireProtection.Tip", "梁の耐火被覆範囲を自動検出し、種類別に色分けした塗潰領域を作成します" },

            // === Ribbon: Quantity ===
            { "Ribbon.Formwork", "型枠" },
            { "Ribbon.Formwork.Tip", "躯体モデルから型枠数量（面積）を自動算出し、Excel/Revit集計表/色分け3Dビューを出力します" },

            // === Ribbon: Excel ===
            { "Ribbon.Excel.Export", "Excel\nエクスポート" },
            { "Ribbon.Excel.Export.Tip", "パラメータをExcelに書き出します" },
            { "Ribbon.Excel.Import", "Excel\nインポート" },
            { "Ribbon.Excel.Import.Tip", "Excelからパラメータを読み込みます" },

            // === Ribbon: Settings ===
            { "Ribbon.Settings.Lang.Tip", "UIの表示言語を切り替えます (JP / US / CN)" },
            { "Ribbon.Settings.About", "バージョン情報" },
            { "Ribbon.Settings.About.Tip", "28 Tools のバージョン情報を表示します" },
            { "Ribbon.Settings.Manual", "マニュアル" },
            { "Ribbon.Settings.Manual.Tip", "28 Tools のマニュアルをブラウザで開きます" },
            { "Ribbon.Settings.Lang.JP.Tip", "日本語に切り替えます" },
            { "Ribbon.Settings.Lang.US.Tip", "Switch to English" },
            { "Ribbon.Settings.Lang.CN.Tip", "切换为中文" },

            // === Common ===
            { "Common.Error", "エラー" },
            { "Common.Warning", "警告" },
            { "Common.Confirm", "確認" },
            { "Common.Complete", "完了" },
            { "Common.OK", "OK" },
            { "Common.Cancel", "キャンセル" },
            { "Common.Next", "次へ" },
            { "Common.Back", "戻る" },
            { "Common.Execute", "実行" },
            { "Common.Create", "作成" },
            { "Common.Search", "検索" },
            { "Common.InputError", "入力エラー" },
            { "Common.ProcessComplete", "処理完了" },
            { "Common.StepIndicator", "ステップ {0} / {1}  {2}" },

            // === Application.cs ===
            { "App.StartupFailed", "アドインの起動に失敗しました。\n{0}" },

            // === About ===
            { "About.Title", "28 Tools について" },
            { "About.Message", "28 Tools\nバージョン: {0}\n有効期限: {1} {2}\n\nRevit 向け業務効率化アドイン" },
            { "About.RemainingSuffix", "(残り {0} 日)" },
            { "About.ExpiredSuffix", "(期限切れ)" },

            // === SheetCreation Dialog ===
            { "Sheet.Title", "シート一括作成" },
            { "Sheet.SelectTitleBlock", "図枠を選択:" },
            { "Sheet.Count", "作成枚数:" },
            { "Sheet.CountHint", "※ 1～100の範囲で入力してください" },
            { "Sheet.DrawingNo", "図面No:" },
            { "Sheet.DrawingNoHint", "※ 空欄の場合は図面Noなし（例: D-駐住, A-棟, など）" },
            { "Sheet.NoTitleBlock", "プロジェクトに図枠ファミリがロードされていません。" },
            { "Sheet.SelectTitleBlockWarn", "図枠を選択してください。" },
            { "Sheet.CountRange", "作成枚数は1～100の範囲で入力してください。" },

            // === FilledRegion Dialog ===
            { "FilledRegion.Title", "塗潰し領域 分割/統合" },
            { "FilledRegion.Operation", "操作" },
            { "FilledRegion.Split", "分割（複数エリアを持つ領域を個別の領域に分割）" },
            { "FilledRegion.Merge", "統合（複数の領域を1つの領域に統合）" },
            { "FilledRegion.Pattern", "塗り潰しパターン" },
            { "FilledRegion.SelectPattern", "統合後の塗り潰しパターンを選択してください：" },
            { "FilledRegion.SelectFirst", "塗り潰し領域を選択してから、このコマンドを実行してください。" },
            { "FilledRegion.NoneSelected", "塗り潰し領域が選択されていません。\n塗り潰し領域を選択してから、このコマンドを実行してください。" },
            { "FilledRegion.NoneAvailable", "分割または統合できる塗り潰し領域がありません。\n\n• 分割: 複数のエリアを持つ領域を選択してください\n• 統合: 複数の領域を選択してください" },
            { "FilledRegion.SelectOperation", "操作（分割または統合）を選択してください。" },
            { "FilledRegion.SelectPatternWarn", "塗り潰しパターンを選択してください。" },
            { "FilledRegion.ProcessError", "処理中にエラーが発生しました。\n\n{0}" },
            { "FilledRegion.InfoSplit", "選択: {0}個の領域（分割可能: {1}個、合計{2}エリア）" },
            { "FilledRegion.InfoMerge", "選択: {0}個の領域（合計{1}エリア）→ 1個の領域に統合" },
            { "FilledRegion.InfoGeneral", "選択: {0}個の領域" },
            { "FilledRegion.SplitResult", "{0}個の領域を{1}個の独立した領域に分割しました。" },
            { "FilledRegion.MergeResult", "{0}個の領域を1個の領域に統合しました。" },

            // === RoomTag Dialog ===
            { "RoomTag.Title", "部屋タグ自動配置" },
            { "RoomTag.ViewName", "ビュー名:" },
            { "RoomTag.ViewFamilyType", "ビューファミリタイプ:" },
            { "RoomTag.FloorPlan", "仕上表__平面図" },
            { "RoomTag.CeilingPlan", "仕上表__天井伏図" },
            { "RoomTag.TagFamilyType", "タグファミリタイプ:" },
            { "RoomTag.TagSpacing", "タグ間隔 (mm):" },
            { "RoomTag.RoomList", "部屋リスト:" },
            { "RoomTag.MoveUp", "上へ移動" },
            { "RoomTag.MoveDown", "下へ移動" },
            { "RoomTag.Delete", "項目を削除" },
            { "RoomTag.UnclosedHint", "*は未閉鎖部屋を示す" },
            { "RoomTag.Preview", "配置プレビュー:" },
            { "RoomTag.IncRows", "行数を増やす" },
            { "RoomTag.DecRows", "行数を減らす" },
            { "RoomTag.OpenSheet", "シートビューを開いた状態で実行してください。" },
            { "RoomTag.NoViewport", "ビューポートが取得できませんでした。" },
            { "RoomTag.NoView", "ビューポートのビューが取得できませんでした。" },
            { "RoomTag.NoRooms", "選択したビューポート内に部屋が見つかりません。" },
            { "RoomTag.NoViewType", "ビューファミリタイプが選択されていません。" },
            { "RoomTag.NoTagType", "タグファミリタイプが選択されていません。" },
            { "RoomTag.NoLayout", "配置設定が取得できませんでした。" },
            { "RoomTag.GenFailed", "部屋タグの生成に失敗しました。" },
            { "RoomTag.GenError", "部屋タグの生成中にエラーが発生しました。\n{0}" },
            { "RoomTag.Done", "部屋タグの自動配置が完了しました。\n\nビュー名: {0}\n配置枚数: {1}個" },
            { "RoomTag.EnterViewName", "ビュー名を入力してください。" },
            { "RoomTag.SelectRooms", "部屋が選択されていません。" },
            { "RoomTag.SelectTagType", "タグファミリタイプを選択してください。" },
            { "RoomTag.InvalidSpacing", "タグ間隔には0以上の数値を入力してください。" },

            // === BeamTopLevel Dialog ===
            { "BeamTop.Title", "梁天端色分け" },
            { "BeamTop.Step1", "ステップ 1 / 3  基本設定" },
            { "BeamTop.ViewInfo", "ビュー情報" },
            { "BeamTop.ViewName", "ビュー名:" },
            { "BeamTop.BeamCount", "梁数:" },
            { "BeamTop.RefLevel", "参照レベル:" },
            { "BeamTop.TextTypeSetting", "文字タイプ設定" },
            { "BeamTop.LegendTextType", "凡例の文字タイプ:" },
            { "BeamTop.LabelTextType", "梁ラベルの文字タイプ:" },
            { "BeamTop.TextTypeHint", "※ 凡例は製図ビューの文字、梁ラベルは平面ビュー上の梁に表示する文字です" },
            { "BeamTop.ParamSelect", "梁天端レベルパラメータ選択" },
            { "BeamTop.ParamHint", "※ ファミリ毎に梁天端レベル（参照レベルからのオフセット）として使用するパラメータを選択してください" },
            { "BeamTop.Summary", "処理概要" },
            { "BeamTop.ProcessContent", "処理内容" },
            { "BeamTop.SharedParam", "共有パラメータ作成・バインド" },
            { "BeamTop.GetValue", "梁天端レベル値の取得・書き込み" },
            { "BeamTop.CreateFilter", "フィルタ自動作成・色分け" },
            { "BeamTop.CreateLegend", "凡例の製図ビュー作成" },
            { "BeamTop.ExistingFilter", "既存フィルタについて" },
            { "BeamTop.OverwriteFilter", "既存の「梁天端_」フィルタを上書きする" },
            { "BeamTop.OverwriteHint", "※ チェックを���すと既存フィルタはそのまま残ります" },
            { "BeamTop.StepName1", "基本設定" },
            { "BeamTop.StepName2", "梁天端レベルパラメータ選択" },
            { "BeamTop.StepName3", "処理確認" },
            { "BeamTop.NotPlanView", "アクティブビューが平面ビューまたは構造伏図ではありません。\n平面ビューまたは構造伏図を開いた状態で実行してください。" },
            { "BeamTop.ViewTemplate", "ビューテンプレート確認" },
            { "BeamTop.ViewTemplateMsg", "ビューテンプレートが設定されています。\nフィルタを作成するにはテンプレートを解除する必要があります。\n\nテンプレートを解除しますか？" },
            { "BeamTop.NoBeams", "ビュー内に梁（構造フレーム）が見つかりません。" },
            { "BeamTop.NoRefLevel", "ビューの参照レベルが取得できません。" },
            { "BeamTop.DoneTitle", "梁天端色分け - 完了" },

            // === BeamUnderLevel Dialog ===
            { "BeamUnder.Title", "梁下端色分け" },
            { "BeamUnder.Step1", "ステップ 1 / 4  レベル設定、凡例設定" },
            { "BeamUnder.ViewInfo", "ビュー情報" },
            { "BeamUnder.ViewName", "ビュー名:" },
            { "BeamUnder.BeamCount", "梁数:" },
            { "BeamUnder.TextTypeSetting", "文字タイプ設定" },
            { "BeamUnder.LegendTextType", "凡例の文字タイプ:" },
            { "BeamUnder.LabelTextType", "梁ラベルの文字タイプ:" },
            { "BeamUnder.TextTypeHint", "※ 凡例は製図ビューの文字、梁ラベルは天井伏図上の梁に表示する文字です" },
            { "BeamUnder.LevelSetting", "レベル設定" },
            { "BeamUnder.RefLevel", "参照レベル:" },
            { "BeamUnder.UpperLevel", "上位レベル:" },
            { "BeamUnder.FloorHeight", "階高:" },
            { "BeamUnder.LevelHint", "※ 参照レベルを基準として梁下端レベルを算出します" },
            { "BeamUnder.HeightParam", "梁高さパラメータ選択" },
            { "BeamUnder.HeightParamHint", "※ ファミリ毎に梁高さとして使用するパラメータを選択してください" },
            { "BeamUnder.TopParam", "梁天端レベルパラメータ選択" },
            { "BeamUnder.TopParamHint", "※ ファミリ毎に梁天端レベル（参照レベルからのオフセット）として使用するパラメータを選択してください" },
            { "BeamUnder.Summary", "処理概要" },
            { "BeamUnder.ProcessContent", "処理内容" },
            { "BeamUnder.SharedParam", "共有パラメータ作成・バインド" },
            { "BeamUnder.CalcValue", "梁下レベル値の計算・書き込み" },
            { "BeamUnder.CreateFilter", "フィルタ自動作成・色分け" },
            { "BeamUnder.CreateLegend", "凡例の製図ビュー作成" },
            { "BeamUnder.ExistingFilter", "既存フィルタについて" },
            { "BeamUnder.OverwriteFilter", "既存の「梁下_」フィルタを上書きする" },
            { "BeamUnder.OverwriteHint", "※ チェックを外すと既存フィルタはそのまま残ります" },
            { "BeamUnder.StepName1", "レベル設定、凡例設定" },
            { "BeamUnder.StepName2", "梁高さパラメータ選択" },
            { "BeamUnder.StepName3", "梁天端レベルパラメータ選択" },
            { "BeamUnder.StepName4", "処理確認" },
            { "BeamUnder.NotCeiling", "アクティブビューが天井伏図ではありません。\n天井伏図を開いた状態で実行してください。" },
            { "BeamUnder.ViewTemplate", "ビューテンプレート確認" },
            { "BeamUnder.ViewTemplateMsg", "ビューテンプレートが設定されています。\nフィルタを作成するにはテンプレートを解除する必要があります。\n\nテンプレートを解除しますか？" },
            { "BeamUnder.NoBeams", "ビュー内に梁（構造フレーム）が見つかりません。" },
            { "BeamUnder.NoRefLevel", "ビューの参照レベルが取得できません。" },
            { "BeamUnder.NoUpperLevel", "参照レベルより上のレベルが見つかりません。" },
            { "BeamUnder.DoneTitle", "梁下端色分け - 完了" },

            // === FireProtection Dialog ===
            { "Fire.Title", "耐火被覆 色分け" },
            { "Fire.Step1", "ステップ 1 / 3  基本設定" },
            { "Fire.ParamLabel", "耐火被覆パラメータ" },
            { "Fire.ParamHint", "※「耐火被覆」を含むパラメータを自動検出します" },
            { "Fire.DetectedTypes", "検出された耐火被覆の種類" },
            { "Fire.ColorHint", "※ 色の四角をクリックすると変更できます" },
            { "Fire.OffsetSetting", "塗り潰し領域のオフセット設定" },
            { "Fire.CommonOffset", "共通オフセット" },
            { "Fire.IndividualOffset", "種類ごとに個別オフセット" },
            { "Fire.Mm", " mm" },
            { "Fire.OffsetHint", "※ 梁のエッジからの距離（mm）" },
            { "Fire.BeamFace", "▽ 梁面" },
            { "Fire.ColumnSetting", "柱 耐火被覆設定" },
            { "Fire.ColumnDistA", "A: 柱中心からの距離:" },
            { "Fire.ColumnWidthB", "B: 外側の幅:" },
            { "Fire.ColumnHint", "※ 柱中心からA、そこから外側にB幅" },
            { "Fire.Column", "柱" },
            { "Fire.DisplaySetting", "表示設定" },
            { "Fire.LineStyle", "境界線の線種:" },
            { "Fire.FillPattern", "塗り潰し領域パターン:" },
            { "Fire.LegendTextType", "凡例の文字タイプ:" },
            { "Fire.Summary", "処理概要" },
            { "Fire.ProcessContent", "処理内容" },
            { "Fire.CreateTypes", "耐火被覆種類ごとの塗潰領域タイプ作成" },
            { "Fire.AutoPlace", "要素周囲に塗潰領域を自動配置（重なり部分は統合）" },
            { "Fire.CreateLegend", "凡例の製図ビュー作成" },
            { "Fire.ExistingLabel", "既存の耐火被覆について" },
            { "Fire.Overwrite", "既存の「耐火被覆_」塗潰領域・凡例を上書きする" },
            { "Fire.StepName1", "基本設定" },
            { "Fire.StepName2", "オフセット・表示設定" },
            { "Fire.StepName3", "処理確認" },
            { "Fire.NoViewOnSheet", "シート上に対応するビュー（平面、天伏、構造伏、断面）がありません。" },
            { "Fire.WrongView", "平面ビュー、天井伏図、構造伏図、断面図、またはシートで実行してください。" },
            { "Fire.NoElements", "ビュー内に梁（構造フレーム）または柱（構造柱）が見つかりません。" },
            { "Fire.DoneTitle", "耐火被覆色分け - 完了" },
            { "Fire.DoneMsg", "処理が完了しました。\n\n対象ビュー数: {0}\n塗潰領域数: {1}" },
            { "Fire.Foreground", "前景" },
            { "Fire.Background", "背景" },
            { "Fire.ParamDetected", "※ {0} 個のパラメータを検出しました" },
            { "Fire.ParamDetectedSuffix", "（{0}件検出）" },
            { "Fire.ParamNotFound", "※「耐火被覆」を含むパラメータが見つかりません" },
            { "Fire.NoParamValues", "耐火被覆パラメータに値が設定された要素がありません。\nパラメータを確認してください。" },
            { "Fire.CategoryBeam", "梁" },
            { "Fire.CategoryBeamColumn", "梁・柱" },
            { "Fire.SummaryView", "ビュー: {0}" },
            { "Fire.SummaryCategory", "対象カテゴリ: {0}" },
            { "Fire.SummaryParam", "耐火被覆パラメータ: {0}" },
            { "Fire.SummaryNone", "なし" },
            { "Fire.SummaryTypes", "検出された種類: {0}" },
            { "Fire.SummaryOffset", "  - {0}（オフセット: {1}mm）" },
            { "Fire.SummaryBorder", "境界線: {0}" },
            { "Fire.SummaryPattern", "塗りパターン: {0}" },

            // === ExcelExport Dialog ===
            { "Export.Title", "EXCELエクスポート" },
            { "Export.Category", "カテゴリを選択" },
            { "Export.Parameter", "パラメータ" },
            { "Export.Output", "出力" },
            { "Export.AddToOutput", "出力に追加" },
            { "Export.RemoveFromOutput", "出力から削除" },
            { "Export.MoveUp", "上へ移動" },
            { "Export.MoveDown", "下へ移動" },
            { "Export.SeparateSheets", "出力Excelをカテゴリ毎にシートに分ける" },
            { "Export.RunExport", "エクスポート実行" },
            { "Export.LoadSettings", "読込" },
            { "Export.LoadSettingsFromExcel", "Excel読込" },
            { "Export.ExcelSettingsNoParams", "選択したExcelから出力設定を読み取れませんでした。\nこのアドインで書き出したExcelファイルを選択してください。" },
            { "Export.ExcelSettingsPartial", "出力設定を読み込みました。\n{1}件中{0}件を復元しました（現在の対象に存在しないパラメータは除外されました）。" },
            { "Export.SaveSettings", "保存" },
            { "Export.LoadSettings.Desc", "保存した設定ファイル(.json)から設定を読み込む" },
            { "Export.LoadSettingsFromExcel.Desc", "書き出し済みのExcelから出力設定を読み込む" },
            { "Export.SaveSettings.Desc", "現在の設定をファイル(.json)に保存する" },
            { "Export.SettingsSaved", "設定を保存しました。" },
            { "Export.SettingsSaveTitle", "設定保存" },
            { "Export.SettingsSaveFailed", "設定の保存に失敗しました。\n{0}" },
            { "Export.SettingsLoadFailed", "設定の読み込みに失敗しました。\n{0}" },
            { "Export.SelectParams", "出力するパラメータを選択してください。" },
            { "Export.SelectCategory", "カテゴリを選択してください。" },
            { "Export.ParamPrefixLegend", "I- : インスタンス（要素）パラメータ\nT- : タイプパラメータ" },
            // 同名パラメータ区別用の種別ラベル（Excelヘッダーにも使用。翻訳変更時は ParameterKindHelper の逆引き表も更新）
            { "Export.ParamKind.BuiltIn", "組み込み" },
            { "Export.ParamKind.Shared", "共有" },
            { "Export.ParamKind.Project", "プロジェクト" },
            { "Common.SelectAll", "全選択" },
            { "Common.SelectNone", "選択解除" },
            { "Export.ClearOutput", "クリア" },
            { "Export.ClearOutput.Desc", "出力欄のパラメータをすべてクリアする" },
            { "Export.ClearOutputConfirm", "出力欄のパラメータをすべてクリアします。よろしいですか？" },
            { "Export.Scope.WindowTitle", "EXCELエクスポート" },
            { "Export.Scope.Title", "書出し範囲の選択" },
            { "Export.Scope.Description", "書出す要素の範囲を選択してください。" },
            { "Export.Scope.Project", "プロジェクト全体の要素" },
            { "Export.Scope.View", "現在のビューにある要素" },
            { "Export.Scope.Selection", "現在選択されている要素" },

            // === ExcelImport Dialog ===
            { "Import.Title", "EXCELインポート" },
            { "Import.ExcelFile", "Excelファイル" },
            { "Import.OpenFile", "開いているファイル" },
            { "Import.Browse", "参照..." },
            { "Import.Preview", "変更プレビュー" },
            { "Import.ColElementId", "要素ID" },
            { "Import.ColCategory", "カテゴリ" },
            { "Import.ColParameter", "パラメータ" },
            { "Import.ColCurrentValue", "現在値" },
            { "Import.ColNewValue", "新しい値" },
            { "Import.Execute", "インポート実行" },
            { "Import.ResultTitle", "インポート結果" },
            { "Import.NoOpenFile", "開いているExcelファイルが見つかりません。" },
            { "Import.ReadFailed", "ファイルの読み込みに失敗しました。\n{0}" },

            // === FormworkCalculator Dialog ===
            { "Formwork.Title", "型枠数量算出" },
            { "Formwork.Scope.Header", "計算範囲" },
            { "Formwork.Scope.Project", "プロジェクト全体" },
            { "Formwork.Scope.View", "現在のビューに表示されている要素" },
            { "Formwork.Scope.SelectedViews", "選択のビュー" },
            { "Formwork.Group.Header", "集計区分" },
            { "Formwork.Group.Category", "部位別（柱・梁・壁・スラブ・基礎・階段・屋根）" },
            { "Formwork.Group.Zone", "工区別" },
            { "Formwork.Group.Type", "型枠種別" },
            { "Formwork.Group.ParamName", "パラメータ名:" },
            { "Formwork.Output.Header", "出力設定" },
            { "Formwork.Output.Excel", "Excel ファイルに出力" },
            { "Formwork.Output.Schedule", "集計表を作成" },
            { "Formwork.Output.View3D", "色分け 3D ビューを作成" },
            { "Formwork.Output.Sheet", "シートを作成" },
            { "Formwork.Color.Header", "色分け区分" },
            { "Formwork.Color.Category", "部位別" },
            { "Formwork.Color.Zone", "工区別" },
            { "Formwork.Color.Type", "型枠種別" },
            { "Formwork.Option.Header", "オプション" },
            { "Formwork.Option.ShowDeducted", "控除面も表示する" },
            { "Formwork.Option.IncludeLinks", "リンクモデルも対象に含める" },
            { "Formwork.NeedZoneParam", "工区別集計を有効にする場合は、工区パラメータ名を入力してください。" },
            { "Formwork.NeedTypeParam", "型枠種別集計を有効にする場合は、型枠種別パラメータ名を入力してください。" },
            { "Formwork.SaveExcelTitle", "型枠数量集計 - Excel 保存先" },
            { "Formwork.NoElements", "対象要素が見つかりませんでした。" },
            { "Formwork.CalcFailed", "型枠数量の計算中にエラーが発生しました。\n{0}" },
            { "Formwork.ExcelFailed", "Excel 出力中にエラーが発生しました。\n{0}" },
            { "Formwork.ViewFailed", "ビュー作成中にエラーが発生しました。\n{0}" },
            { "Formwork.DoneTitle", "型枠数量算出 - 完了" },
            { "Formwork.DoneMsg", "処理が完了しました。\n\n対象要素数: {0}\n型枠面積: {1:F2} ㎡\n控除面積: {2:F2} ㎡\n傾斜面（計算対象外）: {3:F2} ㎡" },
            { "Formwork.ExcelAt", "Excel 出力先: {0}" },
            { "Formwork.ErrorCount", "エラー・注記: {0} 件" },
            { "Formwork.Fatal", "型枠数量算出中に致命的なエラーが発生しました。\n{0}" },
            { "Formwork.ShapesCreated", "型枠面オブジェクト: {0} 個を作成（他ビューでは自動的に非表示）" },
            { "Formwork.ScheduleCreated", "集計表「型枠数量集計」を作成しました" },
            { "Formwork.SummaryScheduleCreated", "サマリ集計表「型枠数量集計_合計」を作成しました（要素削除に追従）" },
            { "Formwork.SheetCreated", "シート「{0} - {1}」を作成しました（3Dビューと集計表を自動配置）" },
            { "Formwork.SteelExcluded", "鉄骨部材 {0} 個を型枠不要として除外しました" },
            { "Formwork.DeckSlabExcluded", "デッキスラブ {0} 個を型枠不要として除外しました（タイプ名に \"DS\" を含む床）" },
            { "Formwork.WallSweepExcluded", "壁スイープ・リビール {0} 個を型枠不要として除外しました" },
            { "Formwork.SteelStairExcluded", "鉄骨階段 {0} 個を型枠不要として除外しました（タイプ名・マテリアルに鉄骨キーワードを含む階段）" },
            { "Formwork.LgsExcluded", "LGS壁 {0} 個を型枠不要として除外しました（石膏ボード層を含みコンクリート層を含まない壁）" },
            { "Formwork.LinkedIncluded", "リンクモデルから {0} 件の要素を対象に含めました（リンクインスタンス: {1} 個）" },
            { "Formwork.ExcludedFilterNote", "（除外要素は解析3Dビューの「型枠_除外」フィルタで非表示。表示 ON で確認可能）" },
            { "Formwork.UpdateConfirm.Title", "型枠数量算出 - 更新確認" },
            { "Formwork.UpdateConfirm.MainInstruction", "既存の型枠出力が見つかりました" },
            { "Formwork.UpdateConfirm.Content", "対象ビューに対応する分析3Dビューまたは集計表が既に存在します。実行モードを選択してください。" },
            { "Formwork.UpdateConfirm.UpdateLabel", "更新（既存のシートレイアウトを保持）" },
            { "Formwork.UpdateConfirm.UpdateDesc", "対象の分析3Dビューと集計表のみ最新モデルで更新します。シート・合計集計表・他のビューは変更しません。" },
            { "Formwork.UpdateConfirm.RecreateLabel", "再作成（全ての出力を作り直す）" },
            { "Formwork.UpdateConfirm.RecreateDesc", "シートと合計集計表を含む全ての出力を削除して再作成します。" },

            // === Excel エクスポート カテゴリ名（BuiltInCategory→ローカライズ）===
            { "Category.Walls", "壁" },
            { "Category.Floors", "床" },
            { "Category.Roofs", "屋根" },
            { "Category.Ceilings", "天井" },
            { "Category.Doors", "ドア" },
            { "Category.Windows", "窓" },
            { "Category.Stairs", "階段" },
            { "Category.Ramps", "スロープ" },
            { "Category.Railings", "手すり" },
            { "Category.Columns", "柱" },
            { "Category.StructuralColumns", "構造柱" },
            { "Category.StructuralFraming", "構造フレーム" },
            { "Category.StructuralFoundation", "構造基礎" },
            { "Category.StructuralTruss", "構造トラス" },
            { "Category.Rebar", "鉄筋" },
            { "Category.Stiffener", "スティフナー" },
            { "Category.Rooms", "部屋" },
            { "Category.Areas", "エリア" },
            { "Category.Furniture", "家具" },
            { "Category.FurnitureSystems", "システム家具" },
            { "Category.Casework", "造作家具" },
            { "Category.GenericModel", "一般モデル" },
            { "Category.SpecialityEquipment", "特殊設備" },
            { "Category.Site", "敷地" },
            { "Category.Topography", "地形" },
            { "Category.Planting", "植栽" },
            { "Category.Parking", "駐車場" },
            { "Category.Entourage", "エンタラージュ" },
            { "Category.Mass", "マス" },
            { "Category.CurtainPanels", "カーテンパネル" },
            { "Category.CurtainMullions", "カーテンマリオン" },
            { "Category.Ducts", "ダクト" },
            { "Category.DuctFittings", "ダクト継手" },
            { "Category.DuctAccessories", "ダクト付属品" },
            { "Category.AirTerminals", "空気端末" },
            { "Category.Pipes", "配管" },
            { "Category.PipeFittings", "配管継手" },
            { "Category.PipeAccessories", "配管付属品" },
            { "Category.Conduits", "電線管" },
            { "Category.CableTrays", "ケーブルトレイ" },
            { "Category.ElectricalEquipment", "電気設備" },
            { "Category.ElectricalFixtures", "電気器具" },
            { "Category.LightingFixtures", "照明器具" },
            { "Category.LightingDevices", "照明装置" },
            { "Category.MechanicalEquipment", "機械設備" },
            { "Category.PlumbingFixtures", "衛生器具" },
            { "Category.Sprinklers", "スプリンクラー" },
            { "Category.FireAlarmDevices", "火災警報装置" },
            { "Category.DataDevices", "データ装置" },
            { "Category.CommunicationDevices", "通信装置" },
            { "Category.SecurityDevices", "セキュリティ装置" },
            { "Category.NurseCallDevices", "ナースコール装置" },
            { "Category.TelephoneDevices", "電話装置" },
            { "Category.Grids", "通り芯" },
            { "Category.Levels", "レベル" },
            { "Category.Sheets", "シート" },
            { "Category.Views", "ビュー" },
            { "Category.Viewports", "ビューポート" },
            { "Category.TextNotes", "テキスト" },
            { "Category.GenericAnnotation", "一般注釈" },
            { "Category.RevisionClouds", "改訂雲" },
            { "Category.Schedules", "集計表" },

            { "Expiry.Title", "28 Tools - 使用期限" },
            { "Expiry.ExpiredMessage", "このバージョンの使用期限（{0}）が切れました。\n\n最新版を以下からダウンロードしてください：\nhttps://28tools.com/addins.html" },
            { "Expiry.WarningTitle", "28 Tools - 期限切れ間近" },
            { "Expiry.WarningMessage", "このバージョンの使用期限まで残り {0} 日です（期限: {1}）。\n\n最新版へのアップデートをご検討ください：\nhttps://28tools.com/addins.html" },

            // 塗潰しパターン入出力
            { "Ribbon.FillPatternIO", "塗潰しパターン\n入出力" },
            { "Ribbon.FillPatternIO.Tip", "rvtファイル内の塗り潰しパターンを一覧表示し、.patファイルへの書き出し／読み込みを行います。" },
            { "FillPatternIO.Title", "塗潰しパターン入出力" },
            { "FillPatternIO.PatternType", "パターン タイプ" },
            { "FillPatternIO.Search", "検索:" },
            { "FillPatternIO.ColPreview", "パターン" },
            { "FillPatternIO.Model", "モデル" },
            { "FillPatternIO.Drafting", "製図" },
            { "FillPatternIO.SelectAll", "全選択" },
            { "FillPatternIO.ClearAll", "全解除" },
            { "FillPatternIO.ColName", "名前" },
            { "FillPatternIO.ColType", "種類" },
            { "FillPatternIO.ColGrid", "グリッド数" },
            { "FillPatternIO.Unit", "単位:" },
            { "FillPatternIO.Export", "エクスポート" },
            { "FillPatternIO.Import", "インポート" },
            { "FillPatternIO.Close", "閉じる" },
            { "FillPatternIO.CountInfo", "全 {0} 件 / 選択 {1} 件" },
            { "FillPatternIO.PatFilter", "パターンファイル (*.pat)|*.pat|すべてのファイル (*.*)|*.*" },
            { "FillPatternIO.SelectFolder", "書き出し先のフォルダを選択してください（各パターンを個別の.patファイルとして保存します）。" },
            { "FillPatternIO.NoSelection", "書き出すパターンを一覧から選択してください。" },
            { "FillPatternIO.OnlySolid", "選択されたパターンはソリッド塗り潰しのみです。ソリッド塗り潰しは.pat形式で書き出せません。" },
            { "FillPatternIO.NoDocument", "アクティブなドキュメントがありません。rvtファイルを開いてから実行してください。" },
            { "FillPatternIO.TransImport", "塗潰しパターンのインポート" },
            { "FillPatternIO.ExportDone", "{0} 件のパターンを書き出しました。" },
            { "FillPatternIO.SolidSkipped", "（ソリッド塗り潰し {0} 件はスキップしました）" },
            { "FillPatternIO.ImportDone", "{0} 件のパターンを読み込みました。" },
            { "FillPatternIO.DupSkipped", "（同名の既存パターン {0} 件はスキップしました）" },
            { "FillPatternIO.InvalidSkipped", "（無効なパターン {0} 件はスキップしました）" },
            { "FillPatternIO.ExportError", "書き出し中にエラーが発生しました：\n{0}" },
            { "FillPatternIO.ImportError", "読み込み中にエラーが発生しました：\n{0}" },
            { "FillPatternIO.ProcessError", "処理中にエラーが発生しました：\n{0}" },

            // === ParameterCleanup（パラメータ整理）===
            { "Ribbon.Panel.Parameter", "パラメータ" },
            { "Ribbon.ParamCleanup", "パラメータ\n整理" },
            { "Ribbon.ParamCleanup.Tip", "プロジェクト内の削除可能なパラメータ（プロジェクト／共有／グローバル）を一覧表示し、同名パラメータの特定・値の有無の確認・不要（未使用）パラメータの削除を行います。大容量モデルでもフリーズしないよう、値の確認は必要なときだけ実行され、進捗表示と中止に対応します。" },
            { "ParamCleanup.Title", "パラメータ整理" },
            { "ParamCleanup.Description", "プロジェクト内の削除可能なパラメータを一覧表示し、各パラメータに値が入った要素があるかを自動で確認します。\n同名のパラメータは強調表示されます。不要（空）なパラメータを選択して削除できます。" },
            { "ParamCleanup.SortHint", "列見出しをクリックで並べ替え" },
            { "ParamCleanup.Search", "検索:" },
            { "ParamCleanup.DuplicateOnly", "同名のみ" },
            { "ParamCleanup.EmptyOnly", "空のみ" },
            { "ParamCleanup.SelectEmpty", "空を全選択" },
            { "ParamCleanup.SelectNotBound", "バインドなしを全選択" },
            { "ParamCleanup.SelectAll", "全選択" },
            { "ParamCleanup.DeselectAll", "選択解除" },
            { "ParamCleanup.Filter.Kind", "種別:" },
            { "ParamCleanup.Filter.All", "すべて" },
            { "ParamCleanup.Filter.SortAsc", "昇順で並べ替え" },
            { "ParamCleanup.Filter.SortDesc", "降順で並べ替え" },
            { "ParamCleanup.Filter.SelectAll", "(すべて選択)" },
            { "ParamCleanup.Filter.Blank", "(空白)" },
            { "ParamCleanup.Filter.Clear", "クリア" },
            { "ParamCleanup.Filter.CheckAll", "全選択" },
            { "ParamCleanup.Filter.UncheckAll", "選択解除" },
            { "ParamCleanup.FilterHint", "並べ替え・フィルター" },
            { "ParamCleanup.Col.Select", "選択" },
            { "ParamCleanup.Col.Name", "パラメータ名" },
            { "ParamCleanup.Col.Kind", "種別" },
            { "ParamCleanup.Col.Scope", "バインド" },
            { "ParamCleanup.Col.Categories", "対象カテゴリ" },
            { "ParamCleanup.Col.ScheduleRef", "集計表参照" },
            { "ParamCleanup.Col.Value", "値" },
            { "ParamCleanup.Btn.Check", "値の有無を確認" },
            { "ParamCleanup.Btn.Cancel", "中止" },
            { "ParamCleanup.Btn.Delete", "選択したパラメータを削除" },
            { "ParamCleanup.Btn.Close", "閉じる" },
            { "ParamCleanup.Kind.Project", "プロジェクト" },
            { "ParamCleanup.Kind.Shared", "共有" },
            { "ParamCleanup.Kind.Global", "グローバル" },
            { "ParamCleanup.Scope.Instance", "インスタンス" },
            { "ParamCleanup.Scope.Type", "タイプ" },
            { "ParamCleanup.State.Unchecked", "未確認" },
            { "ParamCleanup.State.Checking", "確認中…" },
            { "ParamCleanup.State.HasValue", "値あり" },
            { "ParamCleanup.State.Empty", "空（未使用）" },
            { "ParamCleanup.State.NotApplicable", "バインドなし" },
            { "ParamCleanup.Tip.HasValue", "値の入った要素が1件以上あります（使用中）。" },
            { "ParamCleanup.Tip.Empty", "バインド先カテゴリの全要素を確認しましたが、値が1件も入っていません（未使用）。" },
            { "ParamCleanup.Tip.Unchecked", "未確認です。「値の有無を確認」で判定できます。" },
            { "ParamCleanup.Tip.Checking", "確認中です…" },
            { "ParamCleanup.Tip.NotBound", "どのカテゴリにもバインドされていないため、値の有無を判定できません（定義のみ存在）。削除は可能です。" },
            { "ParamCleanup.Tip.Global", "グローバルパラメータの現在値です。" },
            { "ParamCleanup.Status.Scanning", "確認中: {0}" },
            { "ParamCleanup.Status.Done", "確認が完了しました。" },
            { "ParamCleanup.Status.DoneSummary", "確認完了 — 値あり: {0} 件 / 空: {1} 件" },
            { "ParamCleanup.Status.Cancelled", "確認を中止しました。" },
            { "ParamCleanup.Count.Summary", "全 {0} 件 / 表示 {1} 件 / 選択 {2} 件" },
            { "ParamCleanup.Count.Progress", "{0} / {1} 件" },
            { "ParamCleanup.Txn", "不要パラメータの削除" },
            { "ParamCleanup.NoDoc", "アクティブなプロジェクトがありません。" },
            { "ParamCleanup.NoSelection.Msg", "削除するパラメータが選択されていません。" },
            { "ParamCleanup.NotChecked.Msg", "先に「値の有無を確認」を実行してください。" },
            { "ParamCleanup.Confirm.Title", "パラメータの削除" },
            { "ParamCleanup.Confirm.Main", "選択した {0} 件のパラメータを削除します。この操作は元に戻せません。" },
            { "ParamCleanup.Confirm.Content", "注意: 値が空でも、ビューフィルタ・集計表・タグ・数式などで参照されているパラメータを削除すると、それらが機能しなくなる場合があります。削除前に内容をご確認ください。\n\n削除してもよろしいですか？" },
            { "ParamCleanup.Result.Title", "削除結果" },
            { "ParamCleanup.Result.Msg", "削除: {0} 件 / 失敗: {1} 件" },
            { "ParamCleanup.Result.Error", "削除中にエラーが発生しました：\n{0}" },

            // === Ribbon: FilterManagement ===
            { "Ribbon.FilterMgmt", "フィルタ\n整理" },
            { "Ribbon.FilterMgmt.Tip", "プロジェクト内の全フィルタ（表示/グラフィックスの上書き用）を一覧表示し、各フィルタがどのビューで使われているか（未使用か）を確認できます。フィルタ名で検索・絞り込みができ、チェックを入れて名前の変更や不要なフィルタの削除が行えます。" },

            // === FilterManagement Dialog ===
            { "FilterMgmt.Title", "フィルタ整理" },
            { "FilterMgmt.Description", "プロジェクト内のフィルタを一覧表示し、各フィルタがどのビューで使われているか（未使用か）を確認できます。\nフィルタ名の変更（名前欄をダブルクリック）や、不要なフィルタの削除ができます。" },
            { "FilterMgmt.Search", "検索:" },
            { "FilterMgmt.UnusedOnly", "未使用のみ" },
            { "FilterMgmt.Filter.Kind", "種別:" },
            { "FilterMgmt.Filter.All", "すべて" },
            { "FilterMgmt.Kind.Rule", "ルール" },
            { "FilterMgmt.Kind.Selection", "選択" },
            { "FilterMgmt.Col.Select", "選択" },
            { "FilterMgmt.Col.Name", "フィルタ名" },
            { "FilterMgmt.Col.Kind", "種別" },
            { "FilterMgmt.Col.Categories", "対象カテゴリ" },
            { "FilterMgmt.Col.ViewCount", "使用数" },
            { "FilterMgmt.Col.Usage", "使用状況（ビュー）" },
            { "FilterMgmt.SelectUnused", "未使用を全選択" },
            { "FilterMgmt.SelectAll", "全選択" },
            { "FilterMgmt.DeselectAll", "選択解除" },
            { "FilterMgmt.Btn.Reload", "再読み込み" },
            { "FilterMgmt.Btn.Delete", "選択したフィルタを削除" },
            { "FilterMgmt.Btn.Close", "閉じる" },
            { "FilterMgmt.Unused", "未使用" },
            { "FilterMgmt.TemplateMark", "テンプレート" },
            { "FilterMgmt.Count.Summary", "全 {0} 件 / 表示 {1} 件 / 未使用 {2} 件 / 選択 {3} 件" },
            { "FilterMgmt.Txn.Rename", "フィルタ名の変更" },
            { "FilterMgmt.Txn.Delete", "不要フィルタの削除" },
            { "FilterMgmt.NoDoc", "アクティブなプロジェクトがありません。" },
            { "FilterMgmt.NoSelection.Msg", "削除するフィルタが選択されていません。" },
            { "FilterMgmt.Rename.Empty", "フィルタ名を空にすることはできません。" },
            { "FilterMgmt.Rename.Duplicate", "「{0}」という名前のフィルタは既に存在します。別の名前を指定してください。" },
            { "FilterMgmt.Rename.Error", "名前の変更に失敗しました：\n{0}" },
            { "FilterMgmt.Confirm.Title", "フィルタの削除" },
            { "FilterMgmt.Confirm.Main", "選択した {0} 件のフィルタを削除します。この操作は元に戻せません。" },
            { "FilterMgmt.Confirm.Content", "削除してもよろしいですか？" },
            { "FilterMgmt.Confirm.ContentUsed", "注意: 選択したフィルタのうち {0} 件は、いずれかのビューで使用中です。削除すると、そのビューの表示/グラフィックスの上書きから取り除かれます。\n\n削除してもよろしいですか？" },
            { "FilterMgmt.Result.Title", "削除結果" },
            { "FilterMgmt.Result.Msg", "削除: {0} 件 / 失敗: {1} 件" },
            { "FilterMgmt.Result.Error", "削除中にエラーが発生しました：\n{0}" },

            // === Ribbon: ViewTemplateManagement ===
            { "Ribbon.TemplateMgmt", "テンプレート\n整理" },
            { "Ribbon.TemplateMgmt.Tip", "プロジェクト内の全ビューテンプレートを一覧表示し、各テンプレートがどのビューに適用されているか（未使用か）を確認できます。名前で検索・絞り込みができ、チェックを入れて名前の変更や不要なテンプレートの削除が行えます。" },

            // === ViewTemplateManagement Dialog ===
            { "TemplateMgmt.Title", "テンプレート整理" },
            { "TemplateMgmt.Description", "プロジェクト内のビューテンプレートを一覧表示し、各テンプレートがどのビューに適用されているか（未使用か）を確認できます。\nテンプレート名の変更（名前欄をダブルクリック）や、不要なテンプレートの削除ができます。" },
            { "TemplateMgmt.Search", "検索:" },
            { "TemplateMgmt.UnusedOnly", "未使用のみ" },
            { "TemplateMgmt.Col.Select", "選択" },
            { "TemplateMgmt.Col.Name", "テンプレート名" },
            { "TemplateMgmt.Col.ViewType", "種別" },
            { "TemplateMgmt.Col.ViewCount", "使用数" },
            { "TemplateMgmt.Col.Usage", "使用状況（ビュー）" },
            { "TemplateMgmt.SelectUnused", "未使用を全選択" },
            { "TemplateMgmt.SelectAll", "全選択" },
            { "TemplateMgmt.DeselectAll", "選択解除" },
            { "TemplateMgmt.Btn.Reload", "再読み込み" },
            { "TemplateMgmt.Btn.Delete", "選択したテンプレートを削除" },
            { "TemplateMgmt.Btn.Close", "閉じる" },
            { "TemplateMgmt.Unused", "未使用" },
            { "TemplateMgmt.Count.Summary", "全 {0} 件 / 表示 {1} 件 / 未使用 {2} 件 / 選択 {3} 件" },
            { "TemplateMgmt.Txn.Rename", "テンプレート名の変更" },
            { "TemplateMgmt.Txn.Delete", "不要テンプレートの削除" },
            { "TemplateMgmt.NoDoc", "アクティブなプロジェクトがありません。" },
            { "TemplateMgmt.NoSelection.Msg", "削除するテンプレートが選択されていません。" },
            { "TemplateMgmt.Rename.Empty", "テンプレート名を空にすることはできません。" },
            { "TemplateMgmt.Rename.Duplicate", "「{0}」という名前のテンプレートは既に存在します。別の名前を指定してください。" },
            { "TemplateMgmt.Rename.Error", "名前の変更に失敗しました：\n{0}" },
            { "TemplateMgmt.Confirm.Title", "テンプレートの削除" },
            { "TemplateMgmt.Confirm.Main", "選択した {0} 件のテンプレートを削除します。この操作は元に戻せません。" },
            { "TemplateMgmt.Confirm.Content", "削除してもよろしいですか？" },
            { "TemplateMgmt.Confirm.ContentUsed", "注意: 選択したテンプレートのうち {0} 件は、いずれかのビューに適用されています。削除すると、それらのビューはテンプレートが未設定になります（現在の表示設定は保持されますが、テンプレートによる一括制御は外れます）。\n\n削除してもよろしいですか？" },
            { "TemplateMgmt.Result.Title", "削除結果" },
            { "TemplateMgmt.Result.Msg", "削除: {0} 件 / 失敗: {1} 件" },
            { "TemplateMgmt.Result.Error", "削除中にエラーが発生しました：\n{0}" },

            // === View Types（テンプレートの種別表示）===
            { "ViewType.FloorPlan", "平面図" },
            { "ViewType.CeilingPlan", "天井伏図" },
            { "ViewType.EngineeringPlan", "構造伏図" },
            { "ViewType.AreaPlan", "面積図" },
            { "ViewType.Elevation", "立面図" },
            { "ViewType.Section", "断面図" },
            { "ViewType.Detail", "詳細図" },
            { "ViewType.ThreeD", "3Dビュー" },
            { "ViewType.DraftingView", "製図ビュー" },
            { "ViewType.Legend", "凡例" },
            { "ViewType.Schedule", "集計表" },
            { "ViewType.Rendering", "レンダリング" },
            { "ViewType.Walkthrough", "ウォークスルー" },

            // === AutoBackup（自動バックアップ） ===
            { "Ribbon.AutoBackup", "自動\nバックアップ" },
            { "Ribbon.AutoBackup.Tip", "作業中のモデルを一定間隔（既定15分）で自動的にローカルへバックアップします。Revitが空いた瞬間に保存するため作業を中断しません。保存先・間隔・世代数を設定できます。" },
            { "AutoBackup.Title", "自動バックアップ設定" },
            { "AutoBackup.Enable", "自動バックアップを有効にする" },
            { "AutoBackup.Interval.Header", "バックアップ間隔" },
            { "AutoBackup.Interval.Unit", "分ごと" },
            { "AutoBackup.Folder.Header", "バックアップ先" },
            { "AutoBackup.Folder.Model", "モデルと同じ場所（Tools28_Backups フォルダ）" },
            { "AutoBackup.Folder.Custom", "指定フォルダ" },
            { "AutoBackup.Advanced.Header", "詳細" },
            { "AutoBackup.Generations", "保存する世代数" },
            { "AutoBackup.SaveBeforeBackup", "未保存の変更も保存してからバックアップする" },
            { "AutoBackup.BackupNow", "今すぐバックアップ" },
            { "AutoBackup.Last", "最終バックアップ: {0}（{1}）" },
            { "AutoBackup.Last.Never", "最終バックアップ: まだ実行されていません" },
            { "AutoBackup.Last.NeverShort", "未実行" },
            { "AutoBackup.Error.Interval", "バックアップ間隔には1以上の整数（分）を入力してください。" },
            { "AutoBackup.Error.Generations", "世代数には1以上の整数を入力してください。" },
            { "AutoBackup.Error.Folder", "バックアップ先フォルダを指定してください。" },
            { "AutoBackup.Status.Success", "成功" },
            { "AutoBackup.Status.NoDoc", "対象のドキュメントが開かれていません" },
            { "AutoBackup.Status.Linked", "リンクモデルのため対象外です" },
            { "AutoBackup.Status.NotSaved", "モデルが一度も保存されていないため対象外です" },
            { "AutoBackup.Status.Failed", "失敗: {0}" },
            { "AutoBackup.SyncWorkshared", "ワークシェアモデルは中央モデルに自動同期する（クラウド対応）" },
            { "AutoBackup.SyncWorkshared.Note", "クラウド中央モデル（BIM 360 / ACC）はファイルコピーできないため、この方式で同期し、クラウドのバージョン履歴をバックアップとして利用します。" },
            { "AutoBackup.Sync.Comment", "自動バックアップによる同期" },
            { "AutoBackup.Status.Synced", "中央モデルに同期しました" },
            { "AutoBackup.Status.SyncSkipped", "同期をスキップしました（中央がロック中、または一時的な状態）" },
            { "AutoBackup.Status.CloudNeedsSync", "クラウドモデルです。「中央モデルに自動同期する」を有効にしてください" },

            // === DwgLayerTransfer（DWGレイヤ表示設定の移行） ===
            { "Ribbon.DwgVg", "DWG表示\n移行" },
            { "Ribbon.DwgVg.Tip", "開いている別のモデルから、読み込み／リンクした DWG のレイヤ表示設定（表示/非表示・線の色・線幅・線種・ハーフトーン）をこのモデルへ移行します。参照元のビューと DWG を選び、反映先のビュー（複数可）と DWG を選ぶだけで移せます。Excel などの中間ファイルは使いません。" },

            { "DwgVg.Title", "DWGレイヤ表示設定の移行" },
            { "DwgVg.Description", "開いている別のモデルから、DWG レイヤの表示設定（表示/非表示・線の色・線幅・線種・ハーフトーン）をこのモデルへ移行します。左で読み取り元のビューと DWG を選び、右で反映先のビューと DWG を選んでください。" },
            { "DwgVg.Source", "移行元モデル:" },
            { "DwgVg.Target", "移行先モデル:" },
            { "DwgVg.Mode", "反映先の単位:" },
            { "DwgVg.Mode.Template", "ビューテンプレート" },
            { "DwgVg.Mode.View", "ビュー" },
            { "DwgVg.ObjectStyles.Label", "基準値:" },
            { "DwgVg.ObjectStyles", "オブジェクトスタイル（線の色・太さ・線種）も揃える" },
            { "DwgVg.ObjectStyles.Tip", "V/G の上書きは「オブジェクトスタイル」への差分です。上書きしていないレイヤの見た目は基準値で決まるため、これを揃えないとモデル間で表示が一致しません。\n※ ビュー単位ではなくモデル全体に効きます。" },
            { "DwgVg.Result.ObjectStyles", "オブジェクトスタイルを揃えたレイヤ: {0} 件（モデル全体に効きます）" },
            { "DwgVg.Mode.Hint", "※ 移行元と同名のものを自動で選択します" },

            { "DwgVg.Section.Source", "移行元モデル データ情報" },
            { "DwgVg.Section.Target", "移行先モデル データ情報" },
            { "DwgVg.Step1.View", "① 読み取り元のビューを選択" },
            { "DwgVg.Step1.Hint", "※ そのビューで実際に効いている設定を読み取ります（ビューテンプレート由来／ビュー個別のどちらでも）" },
            { "DwgVg.Step2", "② このビューにある DWG を選択" },
            { "DwgVg.Step3", "③ 反映するビューを選択（複数可）" },
            { "DwgVg.Step3.Template", "③ 反映するビューテンプレートを選択（複数可）" },
            { "DwgVg.Step4", "④ 反映先の DWG を選択（複数可）" },

            { "DwgVg.Col.Name", "名前" },
            { "DwgVg.Col.Status", "状態" },
            { "DwgVg.SelectAll", "全選択" },
            { "DwgVg.DeselectAll", "選択解除" },
            { "DwgVg.Btn.Reload", "再読み込み" },
            { "DwgVg.Btn.Apply", "設定を移行" },
            { "DwgVg.Btn.Close", "閉じる" },

            { "DwgVg.Kind.Link", "リンク" },
            { "DwgVg.Kind.Import", "読み込み" },
            { "DwgVg.Kind.ViewSpecific", "このビュー専用" },
            { "DwgVg.Dwg.SourceDetail", "{0}レイヤ / 設定 {1}" },
            { "DwgVg.Dwg.TargetDetail", "{0}レイヤ / 一致 {1}" },
            { "DwgVg.Dwg.PlainDetail", "{0}レイヤ" },

            { "DwgVg.Status.ViaTemplate", "テンプレート「{0}」が割当済み（書き込み先はこちらになります）" },
            { "DwgVg.Status.TemplateNotControlling", "このテンプレートは読み込みカテゴリを制御していません（テンプレート側でV/Gを有効にしてください）" },

            { "DwgVg.Summary", "移行元: {0} ／ {1}（設定 {2} 件）　→　移行先: {3} 件のビュー ／ {4} 件の DWG" },
            { "DwgVg.NoDoc", "モデルが開かれていません。" },
            { "DwgVg.NoSourceDoc", "移行元にできるモデルが見つかりません。\n\n設定のコピー元となるモデルも Revit で開いてから、もう一度実行してください。" },

            { "DwgVg.Warn.NoSourceView", "読み取り元のビューを選択してください。" },
            { "DwgVg.Warn.NoSourceDwg", "移行元の DWG を選択してください。\n\n選択中のビューに DWG が無い場合は、別のビューを選んでください。" },
            { "DwgVg.Warn.NoTargetView", "反映先のビューを1つ以上選択してください。" },
            { "DwgVg.Warn.NoTargetDwg", "反映先の DWG を1つ以上チェックしてください。\n\n移行先モデルにも同じ DWG を読み込み／リンクしてから実行してください。" },
            { "DwgVg.Warn.NoLayers", "移行できるレイヤ設定がありません。" },

            { "DwgVg.Confirm.Title", "設定の移行" },
            { "DwgVg.Confirm.Main", "「{0}」の DWG「{1}」のレイヤ表示設定を、{2} 件のビューの DWG「{3}」へ反映します。" },
            { "DwgVg.Confirm.ViaTemplate", "うち {0} 件のビューは、ビューテンプレートが「読み込み」カテゴリの V/G を制御しているため、ビューテンプレート {1} 件へ書き込みます。\n※ 同じテンプレートを使う他のビューにも反映されます。" },
            { "DwgVg.Confirm.ObjectStyles", "⚠️ 「オブジェクトスタイルも揃える」が有効です。これは選んだビューだけでなく【モデル全体】の DWG の線の色・太さ・線種を書き換えます。他のビューの見た目も変わります。" },
            { "DwgVg.Confirm.Content", "反映先の現在の設定は上書きされます。実行後は Ctrl+Z で元に戻せます。\n続行しますか？" },
            { "DwgVg.Txn.Apply", "DWGレイヤ表示設定の移行" },
            { "DwgVg.Result.Title", "移行結果" },
            { "DwgVg.Result.Msg", "{0} 件のビューに、DWG レイヤ {1} 件分の表示設定を反映しました。" },
            { "DwgVg.Result.ViaTemplate", "うち {0} 件のビューはビューへ直接書き込めなかったため、ビューテンプレート {1} 件へ書き込みました。" },
            { "DwgVg.Result.WrittenTo", "書き込み先: {0}" },
            { "DwgVg.Result.None", "設定を反映できませんでした。" },
            { "DwgVg.Result.SourceEmpty", "※ 移行元の「このビュー × この DWG」には、既定から変更された設定がありませんでした。移行元の DWG 一覧で「設定 ◯」が 1 以上のものを選んでください。" },
            { "DwgVg.Result.Failures", "反映できなかったビュー: {0} 件" },
            { "DwgVg.Result.LogHint", "詳しい経過は C:\\temp\\Tools28_debug.txt に記録しています。" },
            { "DwgVg.Fail.ViewNotFound", "{0}: ビューが見つかりませんでした" },
            { "DwgVg.Fail.NoLayerMatch", "{0}: 移行先の DWG に一致するレイヤがありませんでした" },
            { "DwgVg.Fail.NotApplied", "{0}: 書き込んでも値が変わりませんでした {1}" },
            { "DwgVg.Fail.NoEffect", "{0}: 「{1}」へは書き込めましたが、このビューには反映されませんでした。ビューテンプレートの V/G 設定で「読み込み」が含まれていない可能性があります（テンプレートを編集し、V/G の「読み込み」にチェックを入れてください）" },
            { "DwgVg.Fail.TemplateNotApplied", "{0}: ビューテンプレート「{1}」への書き込みも反映されませんでした {2}" },
            { "DwgVg.Result.HiddenBlocked", "表示/非表示を再現できなかったレイヤ: {0} 件（Revit がこのビューでの非表示を許可していません）" },
            { "DwgVg.Result.MissingLayers", "移行先の DWG に見つからなかったレイヤ: {0} 件" },
            { "DwgVg.Result.MissingPatterns", "移行先に存在しない線種（既定のまま）: {0} 件" },
            { "DwgVg.Result.More", "ほか {0} 件" },
            { "DwgVg.Result.Error", "移行中にエラーが発生しました:\n{0}" },
        };
    }
}
