using System.Collections.Generic;

namespace Tools28.Localization
{
    internal static class StringsEN
    {
        internal static readonly Dictionary<string, string> All = new Dictionary<string, string>
        {
            // === Ribbon: Panel Names ===
            { "Ribbon.Panel.GridBubble", "Grid Bubble" },
            { "Ribbon.Panel.SheetView", "Sheet / View" },
            { "Ribbon.Panel.3DView", "3D View" },
            { "Ribbon.Panel.Annotation", "Annotation" },
            { "Ribbon.Panel.Structural", "Color Code" },
            { "Ribbon.Panel.Quantity", "Quantity Calc" },
            { "Ribbon.Panel.Excel", "Excel" },
            { "Ribbon.Panel.Settings", "Settings" },

            // === Ribbon: GridBubble ===
            { "Ribbon.GridBubble.Both", "Both" },
            { "Ribbon.GridBubble.Both.Tip", "Show grid/level bubbles on both ends" },
            { "Ribbon.GridBubble.Left", "Left" },
            { "Ribbon.GridBubble.Left.Tip", "Show grid/level bubbles on left end only" },
            { "Ribbon.GridBubble.Right", "Right" },
            { "Ribbon.GridBubble.Right.Tip", "Show grid/level bubbles on right end only" },

            // === Ribbon: Sheet/View ===
            { "Ribbon.Sheet.Create", "Batch\nCreate" },
            { "Ribbon.Sheet.Create.Tip", "Create multiple sheets with a specified title block" },
            { "Ribbon.Viewport.Copy", "Viewport\nCopy Pos" },
            { "Ribbon.Viewport.Copy.Tip", "Copy viewport position on a sheet" },
            { "Ribbon.Viewport.Paste", "Viewport\nPaste Pos" },
            { "Ribbon.Viewport.Paste.Tip", "Paste copied viewport position to another sheet" },
            { "Ribbon.CropBox.Copy", "Crop\nRegion Copy" },
            { "Ribbon.CropBox.Copy.Tip", "Copy the crop region of a view" },
            { "Ribbon.CropBox.Paste", "Crop\nRegion Paste" },
            { "Ribbon.CropBox.Paste.Tip", "Paste copied crop region to another view" },

            // === Ribbon: 3D View ===
            { "Ribbon.View.Copy", "Copy View" },
            { "Ribbon.View.Copy.Tip", "Copy the 3D view orientation" },
            { "Ribbon.View.Paste", "Paste View" },
            { "Ribbon.View.Paste.Tip", "Paste copied orientation to another 3D view" },
            { "Ribbon.SectionBox.Copy", "Section Box\nCopy" },
            { "Ribbon.SectionBox.Copy.Tip", "Copy the section box of a 3D view" },
            { "Ribbon.SectionBox.Paste", "Section Box\nPaste" },
            { "Ribbon.SectionBox.Paste.Tip", "Paste copied section box to another 3D view" },

            // === Ribbon: Annotation ===
            { "Ribbon.RoomTag", "Room Tag\nAuto Place" },
            { "Ribbon.RoomTag.Tip", "Auto-place room tags with specified direction and spacing" },
            { "Ribbon.FilledRegion", "Filled Region\nSplit/Merge" },
            { "Ribbon.FilledRegion.Tip", "Split or merge placed filled regions" },

            // === Ribbon: Structural ===
            { "Ribbon.BeamUnder", "Beam Bottom\nColor Code" },
            { "Ribbon.BeamUnder.Tip", "Calculate beam bottom level and apply color coding by level" },
            { "Ribbon.BeamTop", "Beam Top\nColor Code" },
            { "Ribbon.BeamTop.Tip", "Get beam top level from parameters and apply color coding by level" },
            { "Ribbon.FireProtection", "Fireproofing\nColor Code" },
            { "Ribbon.FireProtection.Tip", "Auto-detect fireproofing zones and create color-coded filled regions" },

            // === Ribbon: Quantity ===
            { "Ribbon.Formwork", "Formwork" },
            { "Ribbon.Formwork.Tip", "Auto-calculate formwork quantity (area) from the structural model and output to Excel / Revit view / color-coded 3D view" },

            // === Ribbon: Excel ===
            { "Ribbon.Excel.Export", "Excel\nExport" },
            { "Ribbon.Excel.Export.Tip", "Export parameters to Excel" },
            { "Ribbon.Excel.Import", "Excel\nImport" },
            { "Ribbon.Excel.Import.Tip", "Import parameters from Excel" },

            // === Ribbon: Settings ===
            { "Ribbon.Settings.Lang.Tip", "Switch UI display language (JP / US / CN)" },
            { "Ribbon.Settings.About", "About" },
            { "Ribbon.Settings.About.Tip", "Show 28 Tools version information" },
            { "Ribbon.Settings.Manual", "Manual" },
            { "Ribbon.Settings.Manual.Tip", "Open 28 Tools manual in browser" },
            { "Ribbon.Settings.Lang.JP.Tip", "日本語に切り替えます" },
            { "Ribbon.Settings.Lang.US.Tip", "Switch to English" },
            { "Ribbon.Settings.Lang.CN.Tip", "切换为中文" },

            // === Common ===
            { "Common.Error", "Error" },
            { "Common.Warning", "Warning" },
            { "Common.Confirm", "Confirm" },
            { "Common.Complete", "Complete" },
            { "Common.OK", "OK" },
            { "Common.Cancel", "Cancel" },
            { "Common.Next", "Next" },
            { "Common.Back", "Back" },
            { "Common.Execute", "Execute" },
            { "Common.Create", "Create" },
            { "Common.Search", "Search" },
            { "Common.InputError", "Input Error" },
            { "Common.ProcessComplete", "Process Complete" },
            { "Common.StepIndicator", "Step {0} / {1}  {2}" },

            // === Application.cs ===
            { "App.StartupFailed", "Failed to start add-in.\n{0}" },

            // === About ===
            { "About.Title", "About 28 Tools" },
            { "About.Message", "28 Tools\nVersion: {0}\nExpires: {1} {2}\n\nProductivity add-in for Revit" },
            { "About.RemainingSuffix", "({0} days remaining)" },
            { "About.ExpiredSuffix", "(Expired)" },

            // === SheetCreation Dialog ===
            { "Sheet.Title", "Batch Sheet Creation" },
            { "Sheet.SelectTitleBlock", "Select title block:" },
            { "Sheet.Count", "Number of sheets:" },
            { "Sheet.CountHint", "* Enter a value between 1 and 100" },
            { "Sheet.DrawingNo", "Drawing No:" },
            { "Sheet.DrawingNoHint", "* Leave blank for no number (e.g. D-parking, A-bldg)" },
            { "Sheet.NoTitleBlock", "No title block family is loaded in the project." },
            { "Sheet.SelectTitleBlockWarn", "Please select a title block." },
            { "Sheet.CountRange", "Number of sheets must be between 1 and 100." },

            // === FilledRegion Dialog ===
            { "FilledRegion.Title", "Filled Region Split/Merge" },
            { "FilledRegion.Operation", "Operation" },
            { "FilledRegion.Split", "Split (separate multi-area regions into individual regions)" },
            { "FilledRegion.Merge", "Merge (combine multiple regions into one)" },
            { "FilledRegion.Pattern", "Fill Pattern" },
            { "FilledRegion.SelectPattern", "Select fill pattern for merged region:" },
            { "FilledRegion.SelectFirst", "Select filled regions before running this command." },
            { "FilledRegion.NoneSelected", "No filled regions selected.\nSelect filled regions before running this command." },
            { "FilledRegion.NoneAvailable", "No filled regions available for split or merge.\n\n• Split: Select regions with multiple areas\n• Merge: Select multiple regions" },
            { "FilledRegion.SelectOperation", "Please select an operation (Split or Merge)." },
            { "FilledRegion.SelectPatternWarn", "Please select a fill pattern." },
            { "FilledRegion.ProcessError", "An error occurred during processing.\n\n{0}" },
            { "FilledRegion.InfoSplit", "Selected: {0} regions (splittable: {1}, total {2} areas)" },
            { "FilledRegion.InfoMerge", "Selected: {0} regions (total {1} areas) → merge into 1 region" },
            { "FilledRegion.InfoGeneral", "Selected: {0} regions" },
            { "FilledRegion.SplitResult", "Split {0} regions into {1} independent regions." },
            { "FilledRegion.MergeResult", "Merged {0} regions into 1 region." },

            // === RoomTag Dialog ===
            { "RoomTag.Title", "Room Tag Auto Placement" },
            { "RoomTag.ViewName", "View name:" },
            { "RoomTag.ViewFamilyType", "View family type:" },
            { "RoomTag.FloorPlan", "Finish Schedule - Floor Plan" },
            { "RoomTag.CeilingPlan", "Finish Schedule - Ceiling Plan" },
            { "RoomTag.TagFamilyType", "Tag family type:" },
            { "RoomTag.TagSpacing", "Tag spacing (mm):" },
            { "RoomTag.RoomList", "Room list:" },
            { "RoomTag.MoveUp", "Move up" },
            { "RoomTag.MoveDown", "Move down" },
            { "RoomTag.Delete", "Delete item" },
            { "RoomTag.UnclosedHint", "* indicates unclosed rooms" },
            { "RoomTag.Preview", "Placement preview:" },
            { "RoomTag.IncRows", "Increase rows" },
            { "RoomTag.DecRows", "Decrease rows" },
            { "RoomTag.OpenSheet", "Please open a sheet view before running this command." },
            { "RoomTag.NoViewport", "Could not get the viewport." },
            { "RoomTag.NoView", "Could not get the view from the viewport." },
            { "RoomTag.NoRooms", "No rooms found in the selected viewport." },
            { "RoomTag.NoViewType", "No view family type selected." },
            { "RoomTag.NoTagType", "No tag family type selected." },
            { "RoomTag.NoLayout", "Could not get layout settings." },
            { "RoomTag.GenFailed", "Failed to generate room tags." },
            { "RoomTag.GenError", "An error occurred while generating room tags.\n{0}" },
            { "RoomTag.Done", "Room tag auto-placement complete.\n\nView name: {0}\nTags placed: {1}" },
            { "RoomTag.EnterViewName", "Please enter a view name." },
            { "RoomTag.SelectRooms", "No rooms selected." },
            { "RoomTag.SelectTagType", "Please select a tag family type." },
            { "RoomTag.InvalidSpacing", "Tag spacing must be 0 or greater." },

            // === BeamTopLevel Dialog ===
            { "BeamTop.Title", "Beam Top Color Coding" },
            { "BeamTop.Step1", "Step 1 / 3  Basic Settings" },
            { "BeamTop.ViewInfo", "View Information" },
            { "BeamTop.ViewName", "View name:" },
            { "BeamTop.BeamCount", "Beam count:" },
            { "BeamTop.RefLevel", "Reference level:" },
            { "BeamTop.TextTypeSetting", "Text Type Settings" },
            { "BeamTop.LegendTextType", "Legend text type:" },
            { "BeamTop.LabelTextType", "Beam label text type:" },
            { "BeamTop.TextTypeHint", "* Legend uses drafting view text, label displays on beams in plan view" },
            { "BeamTop.ParamSelect", "Beam Top Level Parameter Selection" },
            { "BeamTop.ParamHint", "* Select the parameter representing the beam top level offset from the reference level for each family" },
            { "BeamTop.Summary", "Process Summary" },
            { "BeamTop.ProcessContent", "Process Details" },
            { "BeamTop.SharedParam", "Create/bind shared parameters" },
            { "BeamTop.GetValue", "Get/write beam top level values" },
            { "BeamTop.CreateFilter", "Auto-create filters and apply color coding" },
            { "BeamTop.CreateLegend", "Create legend drafting view" },
            { "BeamTop.ExistingFilter", "Existing Filters" },
            { "BeamTop.OverwriteFilter", "Overwrite existing \"BeamTop_\" filters" },
            { "BeamTop.OverwriteHint", "* Uncheck to keep existing filters" },
            { "BeamTop.StepName1", "Basic Settings" },
            { "BeamTop.StepName2", "Beam Top Level Parameter Selection" },
            { "BeamTop.StepName3", "Process Confirmation" },
            { "BeamTop.NotPlanView", "Active view is not a floor plan or structural plan.\nPlease open a floor plan or structural plan." },
            { "BeamTop.ViewTemplate", "View Template" },
            { "BeamTop.ViewTemplateMsg", "A view template is applied.\nThe template must be removed to create filters.\n\nRemove the template?" },
            { "BeamTop.NoBeams", "No beams (structural framing) found in the view." },
            { "BeamTop.NoRefLevel", "Cannot get the reference level of the view." },
            { "BeamTop.DoneTitle", "Beam Top Color Coding - Complete" },

            // === BeamUnderLevel Dialog ===
            { "BeamUnder.Title", "Beam Bottom Color Coding" },
            { "BeamUnder.Step1", "Step 1 / 4  Level & Legend Settings" },
            { "BeamUnder.ViewInfo", "View Information" },
            { "BeamUnder.ViewName", "View name:" },
            { "BeamUnder.BeamCount", "Beam count:" },
            { "BeamUnder.TextTypeSetting", "Text Type Settings" },
            { "BeamUnder.LegendTextType", "Legend text type:" },
            { "BeamUnder.LabelTextType", "Beam label text type:" },
            { "BeamUnder.TextTypeHint", "* Legend uses drafting view text, label displays on beams in ceiling plan" },
            { "BeamUnder.LevelSetting", "Level Settings" },
            { "BeamUnder.RefLevel", "Reference level:" },
            { "BeamUnder.UpperLevel", "Upper level:" },
            { "BeamUnder.FloorHeight", "Floor height:" },
            { "BeamUnder.LevelHint", "* Beam bottom level is calculated based on the reference level" },
            { "BeamUnder.HeightParam", "Beam Height Parameter Selection" },
            { "BeamUnder.HeightParamHint", "* Select the parameter representing beam height for each family" },
            { "BeamUnder.TopParam", "Beam Top Level Parameter Selection" },
            { "BeamUnder.TopParamHint", "* Select the parameter representing the beam top level offset from the reference level for each family" },
            { "BeamUnder.Summary", "Process Summary" },
            { "BeamUnder.ProcessContent", "Process Details" },
            { "BeamUnder.SharedParam", "Create/bind shared parameters" },
            { "BeamUnder.CalcValue", "Calculate/write beam bottom level values" },
            { "BeamUnder.CreateFilter", "Auto-create filters and apply color coding" },
            { "BeamUnder.CreateLegend", "Create legend drafting view" },
            { "BeamUnder.ExistingFilter", "Existing Filters" },
            { "BeamUnder.OverwriteFilter", "Overwrite existing \"BeamBottom_\" filters" },
            { "BeamUnder.OverwriteHint", "* Uncheck to keep existing filters" },
            { "BeamUnder.StepName1", "Level & Legend Settings" },
            { "BeamUnder.StepName2", "Beam Height Parameter Selection" },
            { "BeamUnder.StepName3", "Beam Top Level Parameter Selection" },
            { "BeamUnder.StepName4", "Process Confirmation" },
            { "BeamUnder.NotCeiling", "Active view is not a ceiling plan.\nPlease open a ceiling plan." },
            { "BeamUnder.ViewTemplate", "View Template" },
            { "BeamUnder.ViewTemplateMsg", "A view template is applied.\nThe template must be removed to create filters.\n\nRemove the template?" },
            { "BeamUnder.NoBeams", "No beams (structural framing) found in the view." },
            { "BeamUnder.NoRefLevel", "Cannot get the reference level of the view." },
            { "BeamUnder.NoUpperLevel", "No levels found above the reference level." },
            { "BeamUnder.DoneTitle", "Beam Bottom Color Coding - Complete" },

            // === FireProtection Dialog ===
            { "Fire.Title", "Fireproofing Color Coding" },
            { "Fire.Step1", "Step 1 / 3  Basic Settings" },
            { "Fire.ParamLabel", "Fireproofing Parameter" },
            { "Fire.ParamHint", "* Auto-detects parameters containing \"fireproofing\"" },
            { "Fire.DetectedTypes", "Detected Fireproofing Types" },
            { "Fire.ColorHint", "* Click color square to change" },
            { "Fire.OffsetSetting", "Filled Region Offset Settings" },
            { "Fire.CommonOffset", "Common offset" },
            { "Fire.IndividualOffset", "Individual offset per type" },
            { "Fire.Mm", " mm" },
            { "Fire.OffsetHint", "* Distance from beam edge (mm)" },
            { "Fire.BeamFace", "▽ Beam face" },
            { "Fire.ColumnSetting", "Column Fireproofing Settings" },
            { "Fire.ColumnDistA", "A: Distance from column center:" },
            { "Fire.ColumnWidthB", "B: Outer width:" },
            { "Fire.ColumnHint", "* Distance A from column center, then width B outward" },
            { "Fire.Column", "Column" },
            { "Fire.DisplaySetting", "Display Settings" },
            { "Fire.LineStyle", "Boundary line style:" },
            { "Fire.FillPattern", "Fill region pattern:" },
            { "Fire.LegendTextType", "Legend text type:" },
            { "Fire.Summary", "Process Summary" },
            { "Fire.ProcessContent", "Process Details" },
            { "Fire.CreateTypes", "Create filled region type per fireproofing type" },
            { "Fire.AutoPlace", "Auto-place filled regions around elements (merge overlaps)" },
            { "Fire.CreateLegend", "Create legend drafting view" },
            { "Fire.ExistingLabel", "Existing Fireproofing" },
            { "Fire.Overwrite", "Overwrite existing \"Fireproofing_\" filled regions and legend" },
            { "Fire.StepName1", "Basic Settings" },
            { "Fire.StepName2", "Offset & Display Settings" },
            { "Fire.StepName3", "Process Confirmation" },
            { "Fire.NoViewOnSheet", "No applicable views (plan, ceiling, structural, section) found on this sheet." },
            { "Fire.WrongView", "Please run in a floor plan, ceiling plan, structural plan, section, or sheet view." },
            { "Fire.NoElements", "No beams (structural framing) or columns (structural columns) found in the view." },
            { "Fire.DoneTitle", "Fireproofing Color Coding - Complete" },
            { "Fire.DoneMsg", "Process complete.\n\nTarget views: {0}\nFilled regions: {1}" },
            { "Fire.Foreground", "Fore" },
            { "Fire.Background", "Back" },
            { "Fire.ParamDetected", "* {0} parameter(s) detected" },
            { "Fire.ParamDetectedSuffix", " ({0} detected)" },
            { "Fire.ParamNotFound", "* No parameters containing \"fireproofing\" found" },
            { "Fire.NoParamValues", "No elements have values set for the fireproofing parameter.\nPlease check the parameters." },
            { "Fire.CategoryBeam", "Beams" },
            { "Fire.CategoryBeamColumn", "Beams & Columns" },
            { "Fire.SummaryView", "View: {0}" },
            { "Fire.SummaryCategory", "Target category: {0}" },
            { "Fire.SummaryParam", "Fireproofing parameter: {0}" },
            { "Fire.SummaryNone", "None" },
            { "Fire.SummaryTypes", "Detected types: {0}" },
            { "Fire.SummaryOffset", "  - {0} (Offset: {1}mm)" },
            { "Fire.SummaryBorder", "Border line: {0}" },
            { "Fire.SummaryPattern", "Fill pattern: {0}" },

            // === ExcelExport Dialog ===
            { "Export.Title", "Excel Export" },
            { "Export.Category", "Select Category" },
            { "Export.Parameter", "Parameters" },
            { "Export.Output", "Output" },
            { "Export.AddToOutput", "Add to output" },
            { "Export.RemoveFromOutput", "Remove from output" },
            { "Export.MoveUp", "Move up" },
            { "Export.MoveDown", "Move down" },
            { "Export.SeparateSheets", "Separate sheets by category" },
            { "Export.RestoreSettings", "Restore" },
            { "Export.LoadSettings", "Load" },
            { "Export.SaveSettings", "Save" },
            { "Export.SettingsSaved", "Settings saved." },
            { "Export.SettingsSaveTitle", "Save Settings" },
            { "Export.SettingsSaveFailed", "Failed to save settings.\n{0}" },
            { "Export.SettingsLoadFailed", "Failed to load settings.\n{0}" },
            { "Export.SelectParams", "Please select parameters to export." },
            { "Export.SelectCategory", "Please select a category." },
            { "Export.ParamPrefixLegend", "Legend  I- : Instance (element) parameter    T- : Type parameter" },
            { "Export.Scope.WindowTitle", "Excel Export" },
            { "Export.Scope.Title", "Select Export Scope" },
            { "Export.Scope.Description", "Choose which elements to export." },
            { "Export.Scope.Project", "Entire project" },
            { "Export.Scope.View", "Elements in current view" },
            { "Export.Scope.Selection", "Currently selected elements" },

            // === ExcelImport Dialog ===
            { "Import.Title", "Excel Import" },
            { "Import.ExcelFile", "Excel File" },
            { "Import.OpenFile", "Open File" },
            { "Import.Browse", "Browse..." },
            { "Import.SheetInfo", "Sheet Info" },
            { "Import.SelectFile", "Select an Excel file" },
            { "Import.Preview", "Change Preview" },
            { "Import.ColElementId", "Element ID" },
            { "Import.ColCategory", "Category" },
            { "Import.ColParameter", "Parameter" },
            { "Import.ColCurrentValue", "Current Value" },
            { "Import.ColNewValue", "New Value" },
            { "Import.Execute", "Import" },
            { "Import.ResultTitle", "Import Result" },
            { "Import.NoOpenFile", "No open Excel file found." },
            { "Import.ReadFailed", "Failed to read the file.\n{0}" },

            // === FormworkCalculator Dialog ===
            { "Formwork.Title", "Formwork Quantity" },
            { "Formwork.Scope.Header", "Calculation Scope" },
            { "Formwork.Scope.Project", "Entire project" },
            { "Formwork.Scope.View", "Elements visible in the current view" },
            { "Formwork.Scope.SelectedViews", "Selected views" },
            { "Formwork.Group.Header", "Grouping" },
            { "Formwork.Group.Category", "By category (Columns / Beams / Walls / Slabs / Foundations / Stairs / Roofs)" },
            { "Formwork.Group.Zone", "By zone" },
            { "Formwork.Group.Type", "By formwork type" },
            { "Formwork.Group.ParamName", "Parameter name:" },
            { "Formwork.Output.Header", "Output" },
            { "Formwork.Output.Excel", "Export to Excel" },
            { "Formwork.Output.Schedule", "Create schedule" },
            { "Formwork.Output.View3D", "Create color-coded 3D view" },
            { "Formwork.Output.Sheet", "Create sheet" },
            { "Formwork.Color.Header", "Color Scheme" },
            { "Formwork.Color.Category", "By category" },
            { "Formwork.Color.Zone", "By zone" },
            { "Formwork.Color.Type", "By formwork type" },
            { "Formwork.Option.Header", "Options" },
            { "Formwork.Option.ShowDeducted", "Show deducted faces" },
            { "Formwork.Option.IncludeLinks", "Include linked models" },
            { "Formwork.NeedZoneParam", "Please enter the zone parameter name to enable grouping by zone." },
            { "Formwork.NeedTypeParam", "Please enter the formwork-type parameter name to enable grouping by type." },
            { "Formwork.SaveExcelTitle", "Formwork Quantity - Excel Save Location" },
            { "Formwork.NoElements", "No target elements found." },
            { "Formwork.CalcFailed", "An error occurred during formwork quantity calculation.\n{0}" },
            { "Formwork.ExcelFailed", "An error occurred during Excel export.\n{0}" },
            { "Formwork.ViewFailed", "An error occurred during view creation.\n{0}" },
            { "Formwork.DoneTitle", "Formwork Quantity - Completed" },
            { "Formwork.DoneMsg", "Processing completed.\n\nElements: {0}\nFormwork area: {1:F2} m²\nDeducted area: {2:F2} m²\nInclined (excluded): {3:F2} m²" },
            { "Formwork.ExcelAt", "Excel output: {0}" },
            { "Formwork.ErrorCount", "Errors / notes: {0}" },
            { "Formwork.Fatal", "A fatal error occurred during formwork quantity calculation.\n{0}" },
            { "Formwork.ShapesCreated", "Formwork face objects created: {0} (auto-hidden in other views)" },
            { "Formwork.ScheduleCreated", "Schedule \"Formwork Quantity\" has been created" },
            { "Formwork.SummaryScheduleCreated", "Summary schedule \"Formwork Quantity_Total\" has been created (auto-updates when DirectShapes are deleted)" },
            { "Formwork.SheetCreated", "Sheet \"{0} - {1}\" created (3D view and schedules auto-placed)" },
            { "Formwork.SteelExcluded", "Excluded {0} steel members (no formwork needed)" },
            { "Formwork.DeckSlabExcluded", "Excluded {0} deck slabs (floor type name contains \"DS\")" },
            { "Formwork.WallSweepExcluded", "Excluded {0} wall sweeps/reveals (no formwork needed)" },
            { "Formwork.SteelStairExcluded", "Excluded {0} steel stairs (type/material contains steel keyword)" },
            { "Formwork.LgsExcluded", "Excluded {0} LGS walls (wall with gypsum-board layer and no concrete layer)" },
            { "Formwork.LinkedIncluded", "Included {0} elements from linked models ({1} link instance(s))" },
            { "Formwork.ExcludedFilterNote", "(Excluded elements are hidden by the \"Formwork_Excluded\" filter in the analysis 3D view. Toggle the filter ON to inspect them.)" },
            { "Formwork.UpdateConfirm.Title", "Formwork Quantity - Update Confirmation" },
            { "Formwork.UpdateConfirm.MainInstruction", "Existing formwork outputs detected" },
            { "Formwork.UpdateConfirm.Content", "An analysis 3D view or schedule already exists for the selected source view(s). Please choose an execution mode." },
            { "Formwork.UpdateConfirm.UpdateLabel", "Update (preserve sheet layout)" },
            { "Formwork.UpdateConfirm.UpdateDesc", "Refreshes only the target analysis 3D view and schedule with the current model. The sheet, summary schedule, and other views are left untouched." },
            { "Formwork.UpdateConfirm.RecreateLabel", "Recreate (rebuild everything)" },
            { "Formwork.UpdateConfirm.RecreateDesc", "Deletes and recreates all outputs including the sheet and summary schedule." },

            // === Excel Export Category Names ===
            { "Category.Walls", "Walls" },
            { "Category.Floors", "Floors" },
            { "Category.Roofs", "Roofs" },
            { "Category.Ceilings", "Ceilings" },
            { "Category.Doors", "Doors" },
            { "Category.Windows", "Windows" },
            { "Category.Stairs", "Stairs" },
            { "Category.Ramps", "Ramps" },
            { "Category.Railings", "Railings" },
            { "Category.Columns", "Columns" },
            { "Category.StructuralColumns", "Structural Columns" },
            { "Category.StructuralFraming", "Structural Framing" },
            { "Category.StructuralFoundation", "Structural Foundations" },
            { "Category.StructuralTruss", "Structural Trusses" },
            { "Category.Rebar", "Rebar" },
            { "Category.Stiffener", "Stiffeners" },
            { "Category.Rooms", "Rooms" },
            { "Category.Areas", "Areas" },
            { "Category.Furniture", "Furniture" },
            { "Category.FurnitureSystems", "Furniture Systems" },
            { "Category.Casework", "Casework" },
            { "Category.GenericModel", "Generic Models" },
            { "Category.SpecialityEquipment", "Specialty Equipment" },
            { "Category.Site", "Site" },
            { "Category.Topography", "Topography" },
            { "Category.Planting", "Planting" },
            { "Category.Parking", "Parking" },
            { "Category.Entourage", "Entourage" },
            { "Category.Mass", "Mass" },
            { "Category.CurtainPanels", "Curtain Panels" },
            { "Category.CurtainMullions", "Curtain Wall Mullions" },
            { "Category.Ducts", "Ducts" },
            { "Category.DuctFittings", "Duct Fittings" },
            { "Category.DuctAccessories", "Duct Accessories" },
            { "Category.AirTerminals", "Air Terminals" },
            { "Category.Pipes", "Pipes" },
            { "Category.PipeFittings", "Pipe Fittings" },
            { "Category.PipeAccessories", "Pipe Accessories" },
            { "Category.Conduits", "Conduits" },
            { "Category.CableTrays", "Cable Trays" },
            { "Category.ElectricalEquipment", "Electrical Equipment" },
            { "Category.ElectricalFixtures", "Electrical Fixtures" },
            { "Category.LightingFixtures", "Lighting Fixtures" },
            { "Category.LightingDevices", "Lighting Devices" },
            { "Category.MechanicalEquipment", "Mechanical Equipment" },
            { "Category.PlumbingFixtures", "Plumbing Fixtures" },
            { "Category.Sprinklers", "Sprinklers" },
            { "Category.FireAlarmDevices", "Fire Alarm Devices" },
            { "Category.DataDevices", "Data Devices" },
            { "Category.CommunicationDevices", "Communication Devices" },
            { "Category.SecurityDevices", "Security Devices" },
            { "Category.NurseCallDevices", "Nurse Call Devices" },
            { "Category.TelephoneDevices", "Telephone Devices" },
            { "Category.Grids", "Grids" },
            { "Category.Levels", "Levels" },
            { "Category.Sheets", "Sheets" },
            { "Category.Views", "Views" },
            { "Category.Viewports", "Viewports" },
            { "Category.TextNotes", "Text Notes" },
            { "Category.GenericAnnotation", "Generic Annotations" },
            { "Category.RevisionClouds", "Revision Clouds" },
            { "Category.Schedules", "Schedules" },

            { "Expiry.Title", "28 Tools - License Expired" },
            { "Expiry.ExpiredMessage", "This version expired on {0}.\n\nPlease download the latest version from:\nhttps://28tools.com/addins.html" },
            { "Expiry.WarningTitle", "28 Tools - Expiring Soon" },
            { "Expiry.WarningMessage", "This version will expire in {0} days (on {1}).\n\nPlease consider updating to the latest version:\nhttps://28tools.com/addins.html" },

            // Fill pattern import/export
            { "Ribbon.FillPatternIO", "Fill Pattern\nI/O" },
            { "Ribbon.FillPatternIO.Tip", "List the fill patterns in the current model and export/import them as .pat files." },
            { "FillPatternIO.Title", "Fill Pattern Import/Export" },
            { "FillPatternIO.PatternType", "Pattern Type" },
            { "FillPatternIO.Search", "Search:" },
            { "FillPatternIO.ColPreview", "Pattern" },
            { "FillPatternIO.Model", "Model" },
            { "FillPatternIO.Drafting", "Drafting" },
            { "FillPatternIO.SelectAll", "Select All" },
            { "FillPatternIO.ClearAll", "Clear All" },
            { "FillPatternIO.ColName", "Name" },
            { "FillPatternIO.ColType", "Type" },
            { "FillPatternIO.ColGrid", "Grids" },
            { "FillPatternIO.Unit", "Unit:" },
            { "FillPatternIO.Export", "Export" },
            { "FillPatternIO.Import", "Import" },
            { "FillPatternIO.Close", "Close" },
            { "FillPatternIO.CountInfo", "Total {0} / Selected {1}" },
            { "FillPatternIO.PatFilter", "Pattern files (*.pat)|*.pat|All files (*.*)|*.*" },
            { "FillPatternIO.SelectFolder", "Select the destination folder (each pattern is saved as a separate .pat file)." },
            { "FillPatternIO.NoSelection", "Please select the patterns to export from the list." },
            { "FillPatternIO.OnlySolid", "The selected patterns are solid fills only. Solid fills cannot be exported as .pat files." },
            { "FillPatternIO.NoDocument", "No active document. Please open an rvt file and try again." },
            { "FillPatternIO.TransImport", "Import fill patterns" },
            { "FillPatternIO.ExportDone", "Exported {0} pattern(s)." },
            { "FillPatternIO.SolidSkipped", "({0} solid fill(s) skipped.)" },
            { "FillPatternIO.ImportDone", "Imported {0} pattern(s)." },
            { "FillPatternIO.DupSkipped", "({0} existing pattern(s) with the same name skipped.)" },
            { "FillPatternIO.InvalidSkipped", "({0} invalid pattern(s) skipped.)" },
            { "FillPatternIO.ExportError", "An error occurred during export:\n{0}" },
            { "FillPatternIO.ImportError", "An error occurred during import:\n{0}" },
            { "FillPatternIO.ProcessError", "An error occurred during processing:\n{0}" },
        };
    }
}
