using System.Collections.Generic;

namespace Tools28.Localization
{
    internal static class StringsEN
    {
        internal static readonly Dictionary<string, string> All = new Dictionary<string, string>
        {
            // === Ribbon: Panel Names ===
            { "Ribbon.Panel.GridBubble", "Grid Bubble" },
            { "Ribbon.Panel.SheetView", "Sheet / View" },
            { "Ribbon.Panel.3DView", "3D View" },
            { "Ribbon.Panel.Annotation", "Annotation" },
            { "Ribbon.Panel.Structural", "Color Code" },
            { "Ribbon.Panel.Quantity", "Quantity Calc" },
            { "Ribbon.Panel.Excel", "Excel" },
            { "Ribbon.Panel.Settings", "Settings" },

            // === Ribbon: GridBubble ===
            { "Ribbon.GridBubble.Both", "Both" },
            { "Ribbon.GridBubble.Both.Tip", "Show grid/level bubbles on both ends" },
            { "Ribbon.GridBubble.Left", "Left" },
            { "Ribbon.GridBubble.Left.Tip", "Show grid/level bubbles on left end only" },
            { "Ribbon.GridBubble.Right", "Right" },
            { "Ribbon.GridBubble.Right.Tip", "Show grid/level bubbles on right end only" },

            // === Ribbon: Sheet/View ===
            { "Ribbon.Sheet.Create", "Batch\nCreate" },
            { "Ribbon.Sheet.Create.Tip", "Create multiple sheets with a specified title block" },
            { "Ribbon.Viewport.Copy", "Copy Pos" },
            { "Ribbon.Viewport.Copy.Tip", "Copy viewport position on a sheet" },
            { "Ribbon.Viewport.Paste", "Paste Pos" },
            { "Ribbon.Viewport.Paste.Tip", "Paste copied viewport position to another sheet" },
            { "Ribbon.CropBox.Copy", "Crop Copy" },
            { "Ribbon.CropBox.Copy.Tip", "Copy the crop region of a view" },
            { "Ribbon.CropBox.Paste", "Crop Paste" },
            { "Ribbon.CropBox.Paste.Tip", "Paste copied crop region to another view" },

            // === Ribbon: 3D View ===
            { "Ribbon.View.Copy", "Copy View" },
            { "Ribbon.View.Copy.Tip", "Copy the 3D view orientation" },
            { "Ribbon.View.Paste", "Paste View" },
            { "Ribbon.View.Paste.Tip", "Paste copied orientation to another 3D view" },
            { "Ribbon.SectionBox.Copy", "Section Box\nCopy" },
            { "Ribbon.SectionBox.Copy.Tip", "Copy the section box of a 3D view" },
            { "Ribbon.SectionBox.Paste", "Section Box\nPaste" },
            { "Ribbon.SectionBox.Paste.Tip", "Paste copied section box to another 3D view" },

            // === Ribbon: Annotation ===
            { "Ribbon.RoomTag", "Room Tag\nAuto Place" },
            { "Ribbon.RoomTag.Tip", "Auto-place room tags with specified direction and spacing" },
            { "Ribbon.Room3DColor", "Room 3D\nColor" },
            { "Ribbon.Room3DColor.Tip", "Generate room solids and color-code rooms in a dedicated 3D view showing only rooms" },

            // === Room3DColor ===
            { "Room3D.Title", "Room 3D Color" },
            { "Room3D.Header", "Color-code rooms in a 3D view" },
            { "Room3D.BasisLabel", "Color by" },
            { "Room3D.BasisName", "By room name" },
            { "Room3D.BasisLevel", "By level" },
            { "Room3D.BasisParameter", "By parameter value" },
            { "Room3D.BasisPerRoom", "Per room" },
            { "Room3D.BasisAll", "All (single color)" },
            { "Room3D.AllGroupLabel", "All rooms" },
            { "Room3D.ParameterLabel", "Target parameter" },
            { "Room3D.PreviewLabel", "Groups & colors" },
            { "Room3D.ColorHint", "* Click a color swatch to change it" },
            { "Room3D.OutputLabel", "Output settings" },
            { "Room3D.ViewNameLabel", "3D view name to create" },
            { "Room3D.WorksetNameLabel", "Workset name (when workshared)" },
            { "Room3D.DefaultViewName", "Room 3D Color" },
            { "Room3D.DeleteExisting", "Delete existing room-color solids and regenerate" },
            { "Room3D.CreateLegend", "Create legend (drafting view)" },
            { "Room3D.NoRooms", "No placed rooms found. Place rooms with an area before running." },
            { "Room3D.NoGroups", "(No rooms to color)" },
            { "Room3D.GroupRow", "{0} ({1} rooms)" },
            { "Room3D.LegendViewName", "Room 3D Color Legend" },
            { "Room3D.LegendTitle", "Room 3D Color Legend" },
            { "Room3D.LegendRow", "- {0} ({1} rooms)" },
            { "Room3D.DoneTitle", "Room 3D Color Complete" },
            { "Room3D.DoneMessage", "Processing complete.\n\nView: {0}\nRooms colored: {1}\nGroups: {2}" },
            { "Room3D.DoneLegendCreated", "Legend view: created" },
            { "Room3D.DoneLegendSkipped", "Legend view: skipped" },
            { "Room3D.DoneFailure", "* Rooms whose solid could not be generated: {0} (possibly not enclosed or zero volume)" },
            { "Room3D.VolumeEnabledNote", "* Volume computation was disabled, so it has been enabled." },
            { "Room3D.WorksetName", "Room 3D Color" },
            { "Room3D.DoneWorkset", "Workset: placed on \"{0}\" and hidden in other views" },
            { "Room3D.DoneHiddenOtherViews", "Other views: this model is not workshared, so the elements were hidden in other views" },
            { "Room3D.Error", "An error occurred during Room 3D Color processing.\n\n{0}" },
            { "Ribbon.FilledRegion", "Filled Region\nSplit/Merge" },
            { "Ribbon.FilledRegion.Tip", "Split or merge placed filled regions" },

            // === Ribbon: Structural ===
            { "Ribbon.BeamUnder", "Beam Bottom\nColor Code" },
            { "Ribbon.BeamUnder.Tip", "Calculate beam bottom level and apply color coding by level" },
            { "Ribbon.BeamTop", "Beam Top\nColor Code" },
            { "Ribbon.BeamTop.Tip", "Get beam top level from parameters and apply color coding by level" },
            { "Ribbon.FireProtection", "Fireproofing\nColor Code" },
            { "Ribbon.FireProtection.Tip", "Auto-detect fireproofing zones and create color-coded filled regions" },

            // === Ribbon: Quantity ===
            { "Ribbon.Formwork", "Formwork" },
            { "Ribbon.Formwork.Tip", "Auto-calculate formwork quantity (area) from the structural model and output to Excel / Revit view / color-coded 3D view" },

            // === Ribbon: Excel ===
            { "Ribbon.Excel.Export", "Excel\nExport" },
            { "Ribbon.Excel.Export.Tip", "Export parameters to Excel" },
            { "Ribbon.Excel.Import", "Excel\nImport" },
            { "Ribbon.Excel.Import.Tip", "Import parameters from Excel" },

            // === Ribbon: Settings ===
            { "Ribbon.Settings.Lang.Tip", "Switch UI display language (JP / US / CN)" },
            { "Ribbon.Settings.About", "About" },
            { "Ribbon.Settings.About.Tip", "Show 28 Tools version information" },
            { "Ribbon.Settings.Manual", "Manual" },
            { "Ribbon.Settings.Manual.Tip", "Open 28 Tools manual in browser" },
            { "Ribbon.Settings.Lang.JP.Tip", "日本語に切り替えます" },
            { "Ribbon.Settings.Lang.US.Tip", "Switch to English" },
            { "Ribbon.Settings.Lang.CN.Tip", "切换为中文" },

            // === Common ===
            { "Common.Error", "Error" },
            { "Common.Warning", "Warning" },
            { "Common.Confirm", "Confirm" },
            { "Common.Complete", "Complete" },
            { "Common.OK", "OK" },
            { "Common.Cancel", "Cancel" },
            { "Common.Next", "Next" },
            { "Common.Back", "Back" },
            { "Common.Execute", "Execute" },
            { "Common.Create", "Create" },
            { "Common.Search", "Search" },
            { "Common.InputError", "Input Error" },
            { "Common.ProcessComplete", "Process Complete" },
            { "Common.StepIndicator", "Step {0} / {1}  {2}" },

            // === Application.cs ===
            { "App.StartupFailed", "Failed to start add-in.\n{0}" },

            // === About ===
            { "About.Title", "About 28 Tools" },
            { "About.Message", "28 Tools\nVersion: {0}\nExpires: {1} {2}\n\nProductivity add-in for Revit" },
            { "About.RemainingSuffix", "({0} days remaining)" },
            { "About.ExpiredSuffix", "(Expired)" },

            // === SheetCreation Dialog ===
            { "Sheet.Title", "Batch Sheet Creation" },
            { "Sheet.SelectTitleBlock", "Select title block:" },
            { "Sheet.Count", "Number of sheets:" },
            { "Sheet.CountHint", "* Enter a value between 1 and 100" },
            { "Sheet.DrawingNo", "Drawing No:" },
            { "Sheet.DrawingNoHint", "* Leave blank for no number (e.g. D-parking, A-bldg)" },
            { "Sheet.NoTitleBlock", "No title block family is loaded in the project." },
            { "Sheet.SelectTitleBlockWarn", "Please select a title block." },
            { "Sheet.CountRange", "Number of sheets must be between 1 and 100." },

            // === FilledRegion Dialog ===
            { "FilledRegion.Title", "Filled Region Split/Merge" },
            { "FilledRegion.Operation", "Operation" },
            { "FilledRegion.Split", "Split (separate multi-area regions into individual regions)" },
            { "FilledRegion.Merge", "Merge (combine multiple regions into one)" },
            { "FilledRegion.Pattern", "Fill Pattern" },
            { "FilledRegion.SelectPattern", "Select fill pattern for merged region:" },
            { "FilledRegion.SelectFirst", "Select filled regions before running this command." },
            { "FilledRegion.NoneSelected", "No filled regions selected.\nSelect filled regions before running this command." },
            { "FilledRegion.NoneAvailable", "No filled regions available for split or merge.\n\n• Split: Select regions with multiple areas\n• Merge: Select multiple regions" },
            { "FilledRegion.SelectOperation", "Please select an operation (Split or Merge)." },
            { "FilledRegion.SelectPatternWarn", "Please select a fill pattern." },
            { "FilledRegion.ProcessError", "An error occurred during processing.\n\n{0}" },
            { "FilledRegion.InfoSplit", "Selected: {0} regions (splittable: {1}, total {2} areas)" },
            { "FilledRegion.InfoMerge", "Selected: {0} regions (total {1} areas) → merge into 1 region" },
            { "FilledRegion.InfoGeneral", "Selected: {0} regions" },
            { "FilledRegion.SplitResult", "Split {0} regions into {1} independent regions." },
            { "FilledRegion.MergeResult", "Merged {0} regions into 1 region." },

            // === RoomTag Dialog ===
            { "RoomTag.Title", "Room Tag Auto Placement" },
            { "RoomTag.ViewName", "View name:" },
            { "RoomTag.ViewFamilyType", "View family type:" },
            { "RoomTag.FloorPlan", "Finish Schedule - Floor Plan" },
            { "RoomTag.CeilingPlan", "Finish Schedule - Ceiling Plan" },
            { "RoomTag.TagFamilyType", "Tag family type:" },
            { "RoomTag.TagSpacing", "Tag spacing (mm):" },
            { "RoomTag.RoomList", "Room list:" },
            { "RoomTag.MoveUp", "Move up" },
            { "RoomTag.MoveDown", "Move down" },
            { "RoomTag.Delete", "Delete item" },
            { "RoomTag.UnclosedHint", "* indicates unclosed rooms" },
            { "RoomTag.Preview", "Placement preview:" },
            { "RoomTag.IncRows", "Increase rows" },
            { "RoomTag.DecRows", "Decrease rows" },
            { "RoomTag.OpenSheet", "Please open a sheet view before running this command." },
            { "RoomTag.NoViewport", "Could not get the viewport." },
            { "RoomTag.NoView", "Could not get the view from the viewport." },
            { "RoomTag.NoRooms", "No rooms found in the selected viewport." },
            { "RoomTag.NoViewType", "No view family type selected." },
            { "RoomTag.NoTagType", "No tag family type selected." },
            { "RoomTag.NoLayout", "Could not get layout settings." },
            { "RoomTag.GenFailed", "Failed to generate room tags." },
            { "RoomTag.GenError", "An error occurred while generating room tags.\n{0}" },
            { "RoomTag.Done", "Room tag auto-placement complete.\n\nView name: {0}\nTags placed: {1}" },
            { "RoomTag.EnterViewName", "Please enter a view name." },
            { "RoomTag.SelectRooms", "No rooms selected." },
            { "RoomTag.SelectTagType", "Please select a tag family type." },
            { "RoomTag.InvalidSpacing", "Tag spacing must be 0 or greater." },

            // === BeamTopLevel Dialog ===
            { "BeamTop.Title", "Beam Top Color Coding" },
            { "BeamTop.Step1", "Step 1 / 3  Basic Settings" },
            { "BeamTop.ViewInfo", "View Information" },
            { "BeamTop.ViewName", "View name:" },
            { "BeamTop.BeamCount", "Beam count:" },
            { "BeamTop.RefLevel", "Reference level:" },
            { "BeamTop.TextTypeSetting", "Text Type Settings" },
            { "BeamTop.LegendTextType", "Legend text type:" },
            { "BeamTop.LabelTextType", "Beam label text type:" },
            { "BeamTop.TextTypeHint", "* Legend uses drafting view text, label displays on beams in plan view" },
            { "BeamTop.ParamSelect", "Beam Top Level Parameter Selection" },
            { "BeamTop.ParamHint", "* Select the parameter representing the beam top level offset from the reference level for each family" },
            { "BeamTop.Summary", "Process Summary" },
            { "BeamTop.ProcessContent", "Process Details" },
            { "BeamTop.SharedParam", "Create/bind shared parameters" },
            { "BeamTop.GetValue", "Get/write beam top level values" },
            { "BeamTop.CreateFilter", "Auto-create filters and apply color coding" },
            { "BeamTop.CreateLegend", "Create legend drafting view" },
            { "BeamTop.ExistingFilter", "Existing Filters" },
            { "BeamTop.OverwriteFilter", "Overwrite existing \"BeamTop_\" filters" },
            { "BeamTop.OverwriteHint", "* Uncheck to keep existing filters" },
            { "BeamTop.StepName1", "Basic Settings" },
            { "BeamTop.StepName2", "Beam Top Level Parameter Selection" },
            { "BeamTop.StepName3", "Process Confirmation" },
            { "BeamTop.NotPlanView", "Active view is not a floor plan or structural plan.\nPlease open a floor plan or structural plan." },
            { "BeamTop.ViewTemplate", "View Template" },
            { "BeamTop.ViewTemplateMsg", "A view template is applied.\nThe template must be removed to create filters.\n\nRemove the template?" },
            { "BeamTop.NoBeams", "No beams (structural framing) found in the view." },
            { "BeamTop.NoRefLevel", "Cannot get the reference level of the view." },
            { "BeamTop.DoneTitle", "Beam Top Color Coding - Complete" },

            // === BeamUnderLevel Dialog ===
            { "BeamUnder.Title", "Beam Bottom Color Coding" },
            { "BeamUnder.Step1", "Step 1 / 4  Level & Legend Settings" },
            { "BeamUnder.ViewInfo", "View Information" },
            { "BeamUnder.ViewName", "View name:" },
            { "BeamUnder.BeamCount", "Beam count:" },
            { "BeamUnder.TextTypeSetting", "Text Type Settings" },
            { "BeamUnder.LegendTextType", "Legend text type:" },
            { "BeamUnder.LabelTextType", "Beam label text type:" },
            { "BeamUnder.TextTypeHint", "* Legend uses drafting view text, label displays on beams in ceiling plan" },
            { "BeamUnder.LevelSetting", "Level Settings" },
            { "BeamUnder.RefLevel", "Reference level:" },
            { "BeamUnder.UpperLevel", "Upper level:" },
            { "BeamUnder.FloorHeight", "Floor height:" },
            { "BeamUnder.LevelHint", "* Beam bottom level is calculated based on the reference level" },
            { "BeamUnder.HeightParam", "Beam Height Parameter Selection" },
            { "BeamUnder.HeightParamHint", "* Select the parameter representing beam height for each family" },
            { "BeamUnder.TopParam", "Beam Top Level Parameter Selection" },
            { "BeamUnder.TopParamHint", "* Select the parameter representing the beam top level offset from the reference level for each family" },
            { "BeamUnder.Summary", "Process Summary" },
            { "BeamUnder.ProcessContent", "Process Details" },
            { "BeamUnder.SharedParam", "Create/bind shared parameters" },
            { "BeamUnder.CalcValue", "Calculate/write beam bottom level values" },
            { "BeamUnder.CreateFilter", "Auto-create filters and apply color coding" },
            { "BeamUnder.CreateLegend", "Create legend drafting view" },
            { "BeamUnder.ExistingFilter", "Existing Filters" },
            { "BeamUnder.OverwriteFilter", "Overwrite existing \"BeamBottom_\" filters" },
            { "BeamUnder.OverwriteHint", "* Uncheck to keep existing filters" },
            { "BeamUnder.StepName1", "Level & Legend Settings" },
            { "BeamUnder.StepName2", "Beam Height Parameter Selection" },
            { "BeamUnder.StepName3", "Beam Top Level Parameter Selection" },
            { "BeamUnder.StepName4", "Process Confirmation" },
            { "BeamUnder.NotCeiling", "Active view is not a ceiling plan.\nPlease open a ceiling plan." },
            { "BeamUnder.ViewTemplate", "View Template" },
            { "BeamUnder.ViewTemplateMsg", "A view template is applied.\nThe template must be removed to create filters.\n\nRemove the template?" },
            { "BeamUnder.NoBeams", "No beams (structural framing) found in the view." },
            { "BeamUnder.NoRefLevel", "Cannot get the reference level of the view." },
            { "BeamUnder.NoUpperLevel", "No levels found above the reference level." },
            { "BeamUnder.DoneTitle", "Beam Bottom Color Coding - Complete" },

            // === FireProtection Dialog ===
            { "Fire.Title", "Fireproofing Color Coding" },
            { "Fire.Step1", "Step 1 / 3  Basic Settings" },
            { "Fire.ParamLabel", "Fireproofing Parameter" },
            { "Fire.ParamHint", "* Auto-detects parameters containing \"fireproofing\"" },
            { "Fire.DetectedTypes", "Detected Fireproofing Types" },
            { "Fire.ColorHint", "* Click color square to change" },
            { "Fire.OffsetSetting", "Filled Region Offset Settings" },
            { "Fire.CommonOffset", "Common offset" },
            { "Fire.IndividualOffset", "Individual offset per type" },
            { "Fire.Mm", " mm" },
            { "Fire.OffsetHint", "* Distance from beam edge (mm)" },
            { "Fire.BeamFace", "▽ Beam face" },
            { "Fire.ColumnSetting", "Column Fireproofing Settings" },
            { "Fire.ColumnDistA", "A: Distance from column center:" },
            { "Fire.ColumnWidthB", "B: Outer width:" },
            { "Fire.ColumnHint", "* Distance A from column center, then width B outward" },
            { "Fire.Column", "Column" },
            { "Fire.DisplaySetting", "Display Settings" },
            { "Fire.LineStyle", "Boundary line style:" },
            { "Fire.FillPattern", "Fill region pattern:" },
            { "Fire.LegendTextType", "Legend text type:" },
            { "Fire.Summary", "Process Summary" },
            { "Fire.ProcessContent", "Process Details" },
            { "Fire.CreateTypes", "Create filled region type per fireproofing type" },
            { "Fire.AutoPlace", "Auto-place filled regions around elements (merge overlaps)" },
            { "Fire.CreateLegend", "Create legend drafting view" },
            { "Fire.ExistingLabel", "Existing Fireproofing" },
            { "Fire.Overwrite", "Overwrite existing \"Fireproofing_\" filled regions and legend" },
            { "Fire.StepName1", "Basic Settings" },
            { "Fire.StepName2", "Offset & Display Settings" },
            { "Fire.StepName3", "Process Confirmation" },
            { "Fire.NoViewOnSheet", "No applicable views (plan, ceiling, structural, section) found on this sheet." },
            { "Fire.WrongView", "Please run in a floor plan, ceiling plan, structural plan, section, or sheet view." },
            { "Fire.NoElements", "No beams (structural framing) or columns (structural columns) found in the view." },
            { "Fire.DoneTitle", "Fireproofing Color Coding - Complete" },
            { "Fire.DoneMsg", "Process complete.\n\nTarget views: {0}\nFilled regions: {1}" },
            { "Fire.Foreground", "Fore" },
            { "Fire.Background", "Back" },
            { "Fire.ParamDetected", "* {0} parameter(s) detected" },
            { "Fire.ParamDetectedSuffix", " ({0} detected)" },
            { "Fire.ParamNotFound", "* No parameters containing \"fireproofing\" found" },
            { "Fire.NoParamValues", "No elements have values set for the fireproofing parameter.\nPlease check the parameters." },
            { "Fire.CategoryBeam", "Beams" },
            { "Fire.CategoryBeamColumn", "Beams & Columns" },
            { "Fire.SummaryView", "View: {0}" },
            { "Fire.SummaryCategory", "Target category: {0}" },
            { "Fire.SummaryParam", "Fireproofing parameter: {0}" },
            { "Fire.SummaryNone", "None" },
            { "Fire.SummaryTypes", "Detected types: {0}" },
            { "Fire.SummaryOffset", "  - {0} (Offset: {1}mm)" },
            { "Fire.SummaryBorder", "Border line: {0}" },
            { "Fire.SummaryPattern", "Fill pattern: {0}" },

            // === ExcelExport Dialog ===
            { "Export.Title", "Excel Export" },
            { "Export.Category", "Select Category" },
            { "Export.Parameter", "Parameters" },
            { "Export.Output", "Output" },
            { "Export.AddToOutput", "Add to output" },
            { "Export.RemoveFromOutput", "Remove from output" },
            { "Export.MoveUp", "Move up" },
            { "Export.MoveDown", "Move down" },
            { "Export.SeparateSheets", "Split output Excel into sheets per category" },
            { "Export.RunExport", "Export" },
            { "Export.LoadSettings", "Load" },
            { "Export.LoadSettingsFromExcel", "Excel Load" },
            { "Export.ExcelSettingsNoParams", "Could not read output settings from the selected Excel.\nPlease choose an Excel file exported by this add-in." },
            { "Export.ExcelSettingsPartial", "Output settings loaded.\nRestored {0} of {1} (parameters not present in the current targets were skipped)." },
            { "Export.SaveSettings", "Save" },
            { "Export.LoadSettings.Desc", "Load settings from a saved settings file (.json)" },
            { "Export.LoadSettingsFromExcel.Desc", "Load output settings from an already-exported Excel file" },
            { "Export.SaveSettings.Desc", "Save the current settings to a file (.json)" },
            { "Export.SettingsSaved", "Settings saved." },
            { "Export.SettingsSaveTitle", "Save Settings" },
            { "Export.SettingsSaveFailed", "Failed to save settings.\n{0}" },
            { "Export.SettingsLoadFailed", "Failed to load settings.\n{0}" },
            { "Export.SelectParams", "Please select parameters to export." },
            { "Export.SelectCategory", "Please select a category." },
            { "Export.ParamPrefixLegend", "I- : Instance (element) parameter\nT- : Type parameter" },
            // Kind labels used to disambiguate same-named parameters (also embedded in Excel headers;
            // if you change these, update the reverse-lookup table in ParameterKindHelper too)
            { "Export.ParamKind.BuiltIn", "Built-in" },
            { "Export.ParamKind.Shared", "Shared" },
            { "Export.ParamKind.Project", "Project" },
            { "Common.SelectAll", "Select All" },
            { "Common.SelectNone", "Clear" },
            { "Export.ClearOutput", "Clear" },
            { "Export.ClearOutput.Desc", "Clear all parameters from the output list" },
            { "Export.ClearOutputConfirm", "Clear all parameters from the output list?" },
            { "Export.Scope.WindowTitle", "Excel Export" },
            { "Export.Scope.Title", "Select Export Scope" },
            { "Export.Scope.Description", "Choose which elements to export." },
            { "Export.Scope.Project", "Entire project" },
            { "Export.Scope.View", "Elements in current view" },
            { "Export.Scope.Selection", "Currently selected elements" },

            // === ExcelImport Dialog ===
            { "Import.Title", "Excel Import" },
            { "Import.ExcelFile", "Excel File" },
            { "Import.OpenFile", "Open File" },
            { "Import.Browse", "Browse..." },
            { "Import.Preview", "Change Preview" },
            { "Import.ColElementId", "Element ID" },
            { "Import.ColCategory", "Category" },
            { "Import.ColParameter", "Parameter" },
            { "Import.ColCurrentValue", "Current Value" },
            { "Import.ColNewValue", "New Value" },
            { "Import.Execute", "Import" },
            { "Import.ResultTitle", "Import Result" },
            { "Import.NoOpenFile", "No open Excel file found." },
            { "Import.ReadFailed", "Failed to read the file.\n{0}" },

            // === FormworkCalculator Dialog ===
            { "Formwork.Title", "Formwork Quantity" },
            { "Formwork.Scope.Header", "Calculation Scope" },
            { "Formwork.Scope.Project", "Entire project" },
            { "Formwork.Scope.View", "Elements visible in the current view" },
            { "Formwork.Scope.SelectedViews", "Selected views" },
            { "Formwork.Group.Header", "Grouping" },
            { "Formwork.Group.Category", "By category (Columns / Beams / Walls / Slabs / Foundations / Stairs / Roofs)" },
            { "Formwork.Group.Zone", "By zone" },
            { "Formwork.Group.Type", "By formwork type" },
            { "Formwork.Group.ParamName", "Parameter name:" },
            { "Formwork.Output.Header", "Output" },
            { "Formwork.Output.Excel", "Export to Excel" },
            { "Formwork.Output.Schedule", "Create schedule" },
            { "Formwork.Output.View3D", "Create color-coded 3D view" },
            { "Formwork.Output.Sheet", "Create sheet" },
            { "Formwork.Color.Header", "Color Scheme" },
            { "Formwork.Color.Category", "By category" },
            { "Formwork.Color.Zone", "By zone" },
            { "Formwork.Color.Type", "By formwork type" },
            { "Formwork.Option.Header", "Options" },
            { "Formwork.Option.ShowDeducted", "Show deducted faces" },
            { "Formwork.Option.IncludeLinks", "Include linked models" },
            { "Formwork.NeedZoneParam", "Please enter the zone parameter name to enable grouping by zone." },
            { "Formwork.NeedTypeParam", "Please enter the formwork-type parameter name to enable grouping by type." },
            { "Formwork.SaveExcelTitle", "Formwork Quantity - Excel Save Location" },
            { "Formwork.NoElements", "No target elements found." },
            { "Formwork.CalcFailed", "An error occurred during formwork quantity calculation.\n{0}" },
            { "Formwork.ExcelFailed", "An error occurred during Excel export.\n{0}" },
            { "Formwork.ViewFailed", "An error occurred during view creation.\n{0}" },
            { "Formwork.DoneTitle", "Formwork Quantity - Completed" },
            { "Formwork.DoneMsg", "Processing completed.\n\nElements: {0}\nFormwork area: {1:F2} m²\nDeducted area: {2:F2} m²\nInclined (excluded): {3:F2} m²" },
            { "Formwork.ExcelAt", "Excel output: {0}" },
            { "Formwork.ErrorCount", "Errors / notes: {0}" },
            { "Formwork.Fatal", "A fatal error occurred during formwork quantity calculation.\n{0}" },
            { "Formwork.ShapesCreated", "Formwork face objects created: {0} (auto-hidden in other views)" },
            { "Formwork.ScheduleCreated", "Schedule \"Formwork Quantity\" has been created" },
            { "Formwork.SummaryScheduleCreated", "Summary schedule \"Formwork Quantity_Total\" has been created (auto-updates when DirectShapes are deleted)" },
            { "Formwork.SheetCreated", "Sheet \"{0} - {1}\" created (3D view and schedules auto-placed)" },
            { "Formwork.SteelExcluded", "Excluded {0} steel members (no formwork needed)" },
            { "Formwork.DeckSlabExcluded", "Excluded {0} deck slabs (floor type name contains \"DS\")" },
            { "Formwork.WallSweepExcluded", "Excluded {0} wall sweeps/reveals (no formwork needed)" },
            { "Formwork.SteelStairExcluded", "Excluded {0} steel stairs (type/material contains steel keyword)" },
            { "Formwork.LgsExcluded", "Excluded {0} LGS walls (wall with gypsum-board layer and no concrete layer)" },
            { "Formwork.LinkedIncluded", "Included {0} elements from linked models ({1} link instance(s))" },
            { "Formwork.ExcludedFilterNote", "(Excluded elements are hidden by the \"Formwork_Excluded\" filter in the analysis 3D view. Toggle the filter ON to inspect them.)" },
            { "Formwork.UpdateConfirm.Title", "Formwork Quantity - Update Confirmation" },
            { "Formwork.UpdateConfirm.MainInstruction", "Existing formwork outputs detected" },
            { "Formwork.UpdateConfirm.Content", "An analysis 3D view or schedule already exists for the selected source view(s). Please choose an execution mode." },
            { "Formwork.UpdateConfirm.UpdateLabel", "Update (preserve sheet layout)" },
            { "Formwork.UpdateConfirm.UpdateDesc", "Refreshes only the target analysis 3D view and schedule with the current model. The sheet, summary schedule, and other views are left untouched." },
            { "Formwork.UpdateConfirm.RecreateLabel", "Recreate (rebuild everything)" },
            { "Formwork.UpdateConfirm.RecreateDesc", "Deletes and recreates all outputs including the sheet and summary schedule." },

            // === Excel Export Category Names ===
            { "Category.Walls", "Walls" },
            { "Category.Floors", "Floors" },
            { "Category.Roofs", "Roofs" },
            { "Category.Ceilings", "Ceilings" },
            { "Category.Doors", "Doors" },
            { "Category.Windows", "Windows" },
            { "Category.Stairs", "Stairs" },
            { "Category.Ramps", "Ramps" },
            { "Category.Railings", "Railings" },
            { "Category.Columns", "Columns" },
            { "Category.StructuralColumns", "Structural Columns" },
            { "Category.StructuralFraming", "Structural Framing" },
            { "Category.StructuralFoundation", "Structural Foundations" },
            { "Category.StructuralTruss", "Structural Trusses" },
            { "Category.Rebar", "Rebar" },
            { "Category.Stiffener", "Stiffeners" },
            { "Category.Rooms", "Rooms" },
            { "Category.Areas", "Areas" },
            { "Category.Furniture", "Furniture" },
            { "Category.FurnitureSystems", "Furniture Systems" },
            { "Category.Casework", "Casework" },
            { "Category.GenericModel", "Generic Models" },
            { "Category.SpecialityEquipment", "Specialty Equipment" },
            { "Category.Site", "Site" },
            { "Category.Topography", "Topography" },
            { "Category.Planting", "Planting" },
            { "Category.Parking", "Parking" },
            { "Category.Entourage", "Entourage" },
            { "Category.Mass", "Mass" },
            { "Category.CurtainPanels", "Curtain Panels" },
            { "Category.CurtainMullions", "Curtain Wall Mullions" },
            { "Category.Ducts", "Ducts" },
            { "Category.DuctFittings", "Duct Fittings" },
            { "Category.DuctAccessories", "Duct Accessories" },
            { "Category.AirTerminals", "Air Terminals" },
            { "Category.Pipes", "Pipes" },
            { "Category.PipeFittings", "Pipe Fittings" },
            { "Category.PipeAccessories", "Pipe Accessories" },
            { "Category.Conduits", "Conduits" },
            { "Category.CableTrays", "Cable Trays" },
            { "Category.ElectricalEquipment", "Electrical Equipment" },
            { "Category.ElectricalFixtures", "Electrical Fixtures" },
            { "Category.LightingFixtures", "Lighting Fixtures" },
            { "Category.LightingDevices", "Lighting Devices" },
            { "Category.MechanicalEquipment", "Mechanical Equipment" },
            { "Category.PlumbingFixtures", "Plumbing Fixtures" },
            { "Category.Sprinklers", "Sprinklers" },
            { "Category.FireAlarmDevices", "Fire Alarm Devices" },
            { "Category.DataDevices", "Data Devices" },
            { "Category.CommunicationDevices", "Communication Devices" },
            { "Category.SecurityDevices", "Security Devices" },
            { "Category.NurseCallDevices", "Nurse Call Devices" },
            { "Category.TelephoneDevices", "Telephone Devices" },
            { "Category.Grids", "Grids" },
            { "Category.Levels", "Levels" },
            { "Category.Sheets", "Sheets" },
            { "Category.Views", "Views" },
            { "Category.Viewports", "Viewports" },
            { "Category.TextNotes", "Text Notes" },
            { "Category.GenericAnnotation", "Generic Annotations" },
            { "Category.RevisionClouds", "Revision Clouds" },
            { "Category.Schedules", "Schedules" },

            { "Expiry.Title", "28 Tools - License Expired" },
            { "Expiry.ExpiredMessage", "This version expired on {0}.\n\nPlease download the latest version from:\nhttps://28tools.com/addins.html" },
            { "Expiry.WarningTitle", "28 Tools - Expiring Soon" },
            { "Expiry.WarningMessage", "This version will expire in {0} days (on {1}).\n\nPlease consider updating to the latest version:\nhttps://28tools.com/addins.html" },

            // Fill pattern import/export
            { "Ribbon.FillPatternIO", "Fill Pattern\nI/O" },
            { "Ribbon.FillPatternIO.Tip", "List the fill patterns in the current model and export/import them as .pat files." },
            { "FillPatternIO.Title", "Fill Pattern Import/Export" },
            { "FillPatternIO.PatternType", "Pattern Type" },
            { "FillPatternIO.Search", "Search:" },
            { "FillPatternIO.ColPreview", "Pattern" },
            { "FillPatternIO.Model", "Model" },
            { "FillPatternIO.Drafting", "Drafting" },
            { "FillPatternIO.SelectAll", "Select All" },
            { "FillPatternIO.ClearAll", "Clear All" },
            { "FillPatternIO.ColName", "Name" },
            { "FillPatternIO.ColType", "Type" },
            { "FillPatternIO.ColGrid", "Grids" },
            { "FillPatternIO.Unit", "Unit:" },
            { "FillPatternIO.Export", "Export" },
            { "FillPatternIO.Import", "Import" },
            { "FillPatternIO.Close", "Close" },
            { "FillPatternIO.CountInfo", "Total {0} / Selected {1}" },
            { "FillPatternIO.PatFilter", "Pattern files (*.pat)|*.pat|All files (*.*)|*.*" },
            { "FillPatternIO.SelectFolder", "Select the destination folder (each pattern is saved as a separate .pat file)." },
            { "FillPatternIO.NoSelection", "Please select the patterns to export from the list." },
            { "FillPatternIO.OnlySolid", "The selected patterns are solid fills only. Solid fills cannot be exported as .pat files." },
            { "FillPatternIO.NoDocument", "No active document. Please open an rvt file and try again." },
            { "FillPatternIO.TransImport", "Import fill patterns" },
            { "FillPatternIO.ExportDone", "Exported {0} pattern(s)." },
            { "FillPatternIO.SolidSkipped", "({0} solid fill(s) skipped.)" },
            { "FillPatternIO.ImportDone", "Imported {0} pattern(s)." },
            { "FillPatternIO.DupSkipped", "({0} existing pattern(s) with the same name skipped.)" },
            { "FillPatternIO.InvalidSkipped", "({0} invalid pattern(s) skipped.)" },
            { "FillPatternIO.ExportError", "An error occurred during export:\n{0}" },
            { "FillPatternIO.ImportError", "An error occurred during import:\n{0}" },
            { "FillPatternIO.ProcessError", "An error occurred during processing:\n{0}" },

            // === ParameterCleanup ===
            { "Ribbon.Panel.Parameter", "Parameters" },
            { "Ribbon.ParamCleanup", "Parameter\nCleanup" },
            { "Ribbon.ParamCleanup.Tip", "Lists deletable parameters in the project (project / shared / global), highlights duplicate names, checks whether each parameter holds any value, and lets you delete unused ones. Parameters that are not bound as project parameters (for example shared parameters defined inside families) are also evaluated by reading their real values from the elements, so you no longer delete a parameter that still holds data. To avoid freezing on large models it builds a usage index once, exits early, and supports progress display and cancellation." },
            { "ParamCleanup.Title", "Parameter Cleanup" },
            { "ParamCleanup.Description", "Lists deletable parameters in the project and automatically checks whether any element holds a value for each parameter.\nParameters that are not bound as project parameters (for example shared parameters defined inside families) are also checked by reading their real values from the elements.\n\"Unused\" means no element carries the parameter, so deleting it loses no values." },
            { "ParamCleanup.SortHint", "Click a column header to sort" },
            { "ParamCleanup.Search", "Search:" },
            { "ParamCleanup.DuplicateOnly", "Duplicates only" },
            { "ParamCleanup.EmptyOnly", "Empty only" },
            { "ParamCleanup.SelectEmpty", "Select all empty" },
            { "ParamCleanup.SelectNotBound", "Select all unused" },
            { "ParamCleanup.SelectAll", "Select All" },
            { "ParamCleanup.DeselectAll", "Deselect All" },
            { "ParamCleanup.Filter.Kind", "Kind:" },
            { "ParamCleanup.Filter.All", "All" },
            { "ParamCleanup.Filter.SortAsc", "Sort Ascending" },
            { "ParamCleanup.Filter.SortDesc", "Sort Descending" },
            { "ParamCleanup.Filter.SelectAll", "(Select All)" },
            { "ParamCleanup.Filter.Blank", "(Blank)" },
            { "ParamCleanup.Filter.Clear", "Clear" },
            { "ParamCleanup.Filter.CheckAll", "Check All" },
            { "ParamCleanup.Filter.UncheckAll", "Uncheck All" },
            { "ParamCleanup.FilterHint", "Sort / Filter" },
            { "ParamCleanup.Col.Select", "Select" },
            { "ParamCleanup.Col.Name", "Parameter Name" },
            { "ParamCleanup.Col.Kind", "Kind" },
            { "ParamCleanup.Col.Scope", "Binding" },
            { "ParamCleanup.Col.Categories", "Categories" },
            { "ParamCleanup.Col.ScheduleRef", "Schedule Ref." },
            { "ParamCleanup.Col.Value", "Value" },
            { "ParamCleanup.Col.Usage", "Used by" },
            { "ParamCleanup.Scope.NotBound", "None" },
            { "ParamCleanup.Scope.InFamily", "In family" },
            { "ParamCleanup.State.NotFound", "Unused" },
            { "ParamCleanup.Tip.NotFound", "No element or type in the model carries this parameter (only the definition remains). Deleting it loses no values." },
            { "ParamCleanup.Usage.None", "-" },
            { "ParamCleanup.Usage.Summary", "{0} elements - {1}" },
            { "ParamCleanup.Usage.TypeSuffix", " (type)" },
            { "ParamCleanup.Usage.Sample", "e.g. {0} / element ID {1} = {2}" },
            { "ParamCleanup.Status.Indexing", "Indexing parameter usage..." },
            { "ParamCleanup.Status.IndexingCount", "Indexing parameter usage... {0} elements" },
            { "ParamCleanup.Warn.Main", "Warning: {0} of the selected parameters hold values or are unchecked." },
            { "ParamCleanup.Warn.Content", "Deleting them will discard the values already entered on elements. Shared parameters defined inside families (not bound as project parameters) do hold real values on elements.\nDelete anyway?" },
            { "ParamCleanup.Warn.Count", "({0} elements hold it)" },
            { "ParamCleanup.Result.Warnings", "Warnings reported by Revit:" },
            { "ParamCleanup.Btn.Check", "Check Values" },
            { "ParamCleanup.Btn.Cancel", "Cancel" },
            { "ParamCleanup.Btn.Delete", "Delete Selected" },
            { "ParamCleanup.Btn.Close", "Close" },
            { "ParamCleanup.Kind.Project", "Project" },
            { "ParamCleanup.Kind.Shared", "Shared" },
            { "ParamCleanup.Kind.Global", "Global" },
            { "ParamCleanup.Scope.Instance", "Instance" },
            { "ParamCleanup.Scope.Type", "Type" },
            { "ParamCleanup.State.Unchecked", "Not checked" },
            { "ParamCleanup.State.Checking", "Checking..." },
            { "ParamCleanup.State.HasValue", "Has value" },
            { "ParamCleanup.State.Empty", "Empty" },
            { "ParamCleanup.State.NotApplicable", "Not bound" },
            { "ParamCleanup.Tip.HasValue", "At least one element holds a value (in use). Deleting it discards those values." },
            { "ParamCleanup.Tip.Empty", "Elements carry this parameter, but none of them has a value entered. Deleting it loses no values." },
            { "ParamCleanup.Tip.Unchecked", "Not checked yet. Use \"Check Values\" to evaluate." },
            { "ParamCleanup.Tip.Checking", "Checking..." },
            { "ParamCleanup.Tip.NotBound", "Not bound to any category, so value presence cannot be determined (definition only). It can still be deleted." },
            { "ParamCleanup.Tip.Global", "Current value of the global parameter." },
            { "ParamCleanup.Status.Scanning", "Checking: {0}" },
            { "ParamCleanup.Status.Done", "Check completed." },
            { "ParamCleanup.Status.DoneSummary", "Check completed - Has value: {0} / Empty: {1} / Unused: {2}" },
            { "ParamCleanup.Status.Cancelled", "Check cancelled." },
            { "ParamCleanup.Count.Summary", "Total {0} / Shown {1} / Selected {2}" },
            { "ParamCleanup.Count.Progress", "{0} / {1}" },
            { "ParamCleanup.Txn", "Delete unused parameters" },
            { "ParamCleanup.NoDoc", "No active project." },
            { "ParamCleanup.NoSelection.Msg", "No parameters selected for deletion." },
            { "ParamCleanup.NotChecked.Msg", "Please run \"Check Values\" first." },
            { "ParamCleanup.Confirm.Title", "Delete Parameters" },
            { "ParamCleanup.Confirm.Main", "{0} selected parameter(s) will be deleted. This action cannot be undone." },
            { "ParamCleanup.Confirm.Content", "Warning: Even if a parameter is empty, deleting one that is referenced by view filters, schedules, tags, or formulas may break them. Please review before deleting.\n\nAre you sure you want to delete?" },
            { "ParamCleanup.Result.Title", "Deletion Result" },
            { "ParamCleanup.Result.Msg", "Deleted: {0} / Failed: {1}" },
            { "ParamCleanup.Result.Error", "An error occurred during deletion:\n{0}" },

            // === Ribbon: FilterManagement ===
            { "Ribbon.FilterMgmt", "Filter\nCleanup" },
            { "Ribbon.FilterMgmt.Tip", "Lists all filters in the project (used for visibility/graphics overrides) and shows which views use each filter, or whether it is unused. You can search and filter by name, rename filters, and check boxes to delete unwanted filters." },

            // === FilterManagement Dialog ===
            { "FilterMgmt.Title", "Filter Cleanup" },
            { "FilterMgmt.Description", "Lists the filters in the project and shows which views use each filter (or whether it is unused).\nYou can rename a filter (double-click the name) and delete filters you no longer need." },
            { "FilterMgmt.Search", "Search:" },
            { "FilterMgmt.UnusedOnly", "Unused only" },
            { "FilterMgmt.Filter.Kind", "Type:" },
            { "FilterMgmt.Filter.All", "All" },
            { "FilterMgmt.Kind.Rule", "Rule-based" },
            { "FilterMgmt.Kind.Selection", "Selection" },
            { "FilterMgmt.Col.Select", "Select" },
            { "FilterMgmt.Col.Name", "Filter Name" },
            { "FilterMgmt.Col.Kind", "Type" },
            { "FilterMgmt.Col.Categories", "Categories" },
            { "FilterMgmt.Col.ViewCount", "Uses" },
            { "FilterMgmt.Col.Usage", "Used In (Views)" },
            { "FilterMgmt.SelectUnused", "Select Unused" },
            { "FilterMgmt.SelectAll", "Select All" },
            { "FilterMgmt.DeselectAll", "Deselect" },
            { "FilterMgmt.Btn.Reload", "Reload" },
            { "FilterMgmt.Btn.Delete", "Delete Selected Filters" },
            { "FilterMgmt.Btn.Close", "Close" },
            { "FilterMgmt.Unused", "Unused" },
            { "FilterMgmt.TemplateMark", "Template" },
            { "FilterMgmt.Count.Summary", "Total {0} / Shown {1} / Unused {2} / Selected {3}" },
            { "FilterMgmt.Txn.Rename", "Rename Filter" },
            { "FilterMgmt.Txn.Delete", "Delete Unused Filters" },
            { "FilterMgmt.NoDoc", "No active project." },
            { "FilterMgmt.NoSelection.Msg", "No filters are selected for deletion." },
            { "FilterMgmt.Rename.Empty", "The filter name cannot be empty." },
            { "FilterMgmt.Rename.Duplicate", "A filter named \"{0}\" already exists. Please choose another name." },
            { "FilterMgmt.Rename.Error", "Failed to rename:\n{0}" },
            { "FilterMgmt.Confirm.Title", "Delete Filters" },
            { "FilterMgmt.Confirm.Main", "Delete the {0} selected filter(s). This action cannot be undone." },
            { "FilterMgmt.Confirm.Content", "Are you sure you want to delete them?" },
            { "FilterMgmt.Confirm.ContentUsed", "Note: {0} of the selected filters are in use by one or more views. Deleting them will remove them from those views' visibility/graphics overrides.\n\nAre you sure you want to delete them?" },
            { "FilterMgmt.Result.Title", "Deletion Result" },
            { "FilterMgmt.Result.Msg", "Deleted: {0} / Failed: {1}" },
            { "FilterMgmt.Result.Error", "An error occurred during deletion:\n{0}" },

            // === Ribbon: ViewTemplateManagement ===
            { "Ribbon.TemplateMgmt", "Template\nCleanup" },
            { "Ribbon.TemplateMgmt.Tip", "Lists all view templates in the project and shows which views each template is applied to, or whether it is unused. You can search and filter by name, rename templates, and check boxes to delete unwanted templates." },

            // === ViewTemplateManagement Dialog ===
            { "TemplateMgmt.Title", "View Template Cleanup" },
            { "TemplateMgmt.Description", "Lists the view templates in the project and shows which views each template is applied to (or whether it is unused).\nYou can rename a template (double-click the name) and delete templates you no longer need." },
            { "TemplateMgmt.Search", "Search:" },
            { "TemplateMgmt.UnusedOnly", "Unused only" },
            { "TemplateMgmt.Col.Select", "Select" },
            { "TemplateMgmt.Col.Name", "Template Name" },
            { "TemplateMgmt.Col.ViewType", "Type" },
            { "TemplateMgmt.Col.ViewCount", "Uses" },
            { "TemplateMgmt.Col.Usage", "Used In (Views)" },
            { "TemplateMgmt.SelectUnused", "Select Unused" },
            { "TemplateMgmt.SelectAll", "Select All" },
            { "TemplateMgmt.DeselectAll", "Deselect" },
            { "TemplateMgmt.Btn.Reload", "Reload" },
            { "TemplateMgmt.Btn.Delete", "Delete Selected Templates" },
            { "TemplateMgmt.Btn.Close", "Close" },
            { "TemplateMgmt.Unused", "Unused" },
            { "TemplateMgmt.Count.Summary", "Total {0} / Shown {1} / Unused {2} / Selected {3}" },
            { "TemplateMgmt.Txn.Rename", "Rename Template" },
            { "TemplateMgmt.Txn.Delete", "Delete Unused Templates" },
            { "TemplateMgmt.NoDoc", "No active project." },
            { "TemplateMgmt.NoSelection.Msg", "No templates are selected for deletion." },
            { "TemplateMgmt.Rename.Empty", "The template name cannot be empty." },
            { "TemplateMgmt.Rename.Duplicate", "A template named \"{0}\" already exists. Please choose another name." },
            { "TemplateMgmt.Rename.Error", "Failed to rename:\n{0}" },
            { "TemplateMgmt.Confirm.Title", "Delete Templates" },
            { "TemplateMgmt.Confirm.Main", "Delete the {0} selected template(s). This action cannot be undone." },
            { "TemplateMgmt.Confirm.Content", "Are you sure you want to delete them?" },
            { "TemplateMgmt.Confirm.ContentUsed", "Note: {0} of the selected templates are applied to one or more views. Deleting them will leave those views without a template (their current graphic settings are kept, but the template's central control is removed).\n\nAre you sure you want to delete them?" },
            { "TemplateMgmt.Result.Title", "Deletion Result" },
            { "TemplateMgmt.Result.Msg", "Deleted: {0} / Failed: {1}" },
            { "TemplateMgmt.Result.Error", "An error occurred during deletion:\n{0}" },

            // === View Types (template type display) ===
            { "ViewType.FloorPlan", "Floor Plan" },
            { "ViewType.CeilingPlan", "Ceiling Plan" },
            { "ViewType.EngineeringPlan", "Structural Plan" },
            { "ViewType.AreaPlan", "Area Plan" },
            { "ViewType.Elevation", "Elevation" },
            { "ViewType.Section", "Section" },
            { "ViewType.Detail", "Detail" },
            { "ViewType.ThreeD", "3D View" },
            { "ViewType.DraftingView", "Drafting View" },
            { "ViewType.Legend", "Legend" },
            { "ViewType.Schedule", "Schedule" },
            { "ViewType.Rendering", "Rendering" },
            { "ViewType.Walkthrough", "Walkthrough" },

            // === AutoBackup ===
            { "Ribbon.AutoBackup", "Auto\nBackup" },
            { "Ribbon.AutoBackup.Tip", "Automatically backs up the current model to a local folder at a fixed interval (15 min by default). It saves when Revit is idle so your work is not interrupted. The location, interval, and number of generations are configurable." },
            { "AutoBackup.Title", "Auto Backup Settings" },
            { "AutoBackup.Enable", "Enable auto backup" },
            { "AutoBackup.Interval.Header", "Backup interval" },
            { "AutoBackup.Interval.Unit", "minutes" },
            { "AutoBackup.Folder.Header", "Backup location" },
            { "AutoBackup.Folder.Model", "Same as model (Tools28_Backups folder)" },
            { "AutoBackup.Folder.Custom", "Custom folder" },
            { "AutoBackup.Advanced.Header", "Advanced" },
            { "AutoBackup.Generations", "Generations to keep" },
            { "AutoBackup.SaveBeforeBackup", "Save unsaved changes before backing up" },
            { "AutoBackup.BackupNow", "Back up now" },
            { "AutoBackup.Last", "Last backup: {0} ({1})" },
            { "AutoBackup.Last.Never", "Last backup: not run yet" },
            { "AutoBackup.Last.NeverShort", "not run" },
            { "AutoBackup.Error.Interval", "Enter an integer of 1 or more (minutes) for the backup interval." },
            { "AutoBackup.Error.Generations", "Enter an integer of 1 or more for the number of generations." },
            { "AutoBackup.Error.Folder", "Please specify a backup folder." },
            { "AutoBackup.Status.Success", "Success" },
            { "AutoBackup.Status.NoDoc", "No target document is open" },
            { "AutoBackup.Status.Linked", "Skipped because it is a linked model" },
            { "AutoBackup.Status.NotSaved", "Skipped because the model has never been saved" },
            { "AutoBackup.Status.Failed", "Failed: {0}" },
            { "AutoBackup.SyncWorkshared", "Synchronize workshared models with central (cloud supported)" },
            { "AutoBackup.SyncWorkshared.Note", "Cloud central models (BIM 360 / ACC) cannot be file-copied, so this synchronizes to central and relies on the cloud version history as the backup." },
            { "AutoBackup.Sync.Comment", "Synchronized by auto backup" },
            { "AutoBackup.Status.Synced", "Synchronized with central" },
            { "AutoBackup.Status.SyncSkipped", "Sync skipped (central is locked or temporarily unavailable)" },
            { "AutoBackup.Status.CloudNeedsSync", "This is a cloud model. Please enable \"Synchronize workshared models with central\"." },

            // === DwgLayerTransfer ===
            { "Ribbon.DwgVg", "DWG Layer\nTransfer" },
            { "Ribbon.DwgVg.Tip", "Transfers the display settings of imported/linked DWG layers (visibility, line color, line weight, line pattern, halftone) from another open model into this one. Pick the source view and DWG, then the target views (multiple allowed) and DWG. No intermediate file such as Excel is used." },

            { "DwgVg.Title", "Transfer DWG Layer Display Settings" },
            { "DwgVg.Description", "Transfers DWG layer display settings (visibility, line color, line weight, line pattern, halftone) from another open model into this one. Pick the view and DWG to read from on the left, then the target views and DWG on the right." },
            { "DwgVg.Source", "Source model:" },
            { "DwgVg.Target", "Target model:" },
            { "DwgVg.Mode", "Target unit:" },
            { "DwgVg.Mode.Template", "View template" },
            { "DwgVg.Mode.View", "View" },
            { "DwgVg.ObjectStyles.Label", "Base values:" },
            { "DwgVg.ObjectStyles", "Also match object styles (line color, weight, pattern)" },
            { "DwgVg.ObjectStyles.Tip", "V/G overrides are deltas on top of Object Styles. Layers without an override take their appearance from the base values, so the models will not match unless these are transferred too.\n* This affects the whole model, not just the selected views." },
            { "DwgVg.Result.ObjectStyles", "Layers whose object styles were matched: {0} (affects the whole model)" },
            { "DwgVg.Mode.Hint", "* Items whose name matches the source are selected automatically" },

            { "DwgVg.Section.Source", "Source model data" },
            { "DwgVg.Section.Target", "Target model data" },
            { "DwgVg.Step1.View", "1. Select the view to read from" },
            { "DwgVg.Step1.Hint", "* Reads the settings actually in effect in that view (whether they come from a view template or are set on the view itself)" },
            { "DwgVg.Step2", "2. Select a DWG present in this view" },
            { "DwgVg.Step3", "3. Select target views (multiple allowed)" },
            { "DwgVg.Step3.Template", "3. Select target view templates (multiple allowed)" },
            { "DwgVg.Step4", "4. Select target DWGs (multiple allowed)" },

            { "DwgVg.Col.Name", "Name" },
            { "DwgVg.Col.Status", "Status" },
            { "DwgVg.SelectAll", "Select all" },
            { "DwgVg.DeselectAll", "Clear" },
            { "DwgVg.Btn.Reload", "Reload" },
            { "DwgVg.Btn.Apply", "Transfer settings" },
            { "DwgVg.Btn.Close", "Close" },

            { "DwgVg.Kind.Link", "Link" },
            { "DwgVg.Kind.Import", "Import" },
            { "DwgVg.Kind.ViewSpecific", "this view only" },
            { "DwgVg.Dwg.SourceDetail", "{0} layers / {1} set" },
            { "DwgVg.Dwg.TargetDetail", "{0} layers / {1} matched" },
            { "DwgVg.Dwg.PlainDetail", "{0} layers" },

            { "DwgVg.Status.ViaTemplate", "View template \"{0}\" assigned (the settings will be written there)" },
            { "DwgVg.Status.TemplateNotControlling", "This template does not control imported categories (enable V/G overrides in the template)" },

            { "DwgVg.Summary", "From: {0} / {1} ({2} set)  ->  To: {3} view(s) / {4} DWG(s)" },
            { "DwgVg.NoDoc", "No model is open." },
            { "DwgVg.NoSourceDoc", "No model is available as a transfer source.\n\nOpen the model you want to copy the settings from, then run this command again." },

            { "DwgVg.Warn.NoSourceView", "Select the view to read from." },
            { "DwgVg.Warn.NoSourceDwg", "Select a source DWG.\n\nIf the selected view contains no DWG, choose a different view." },
            { "DwgVg.Warn.NoTargetView", "Select at least one target view." },
            { "DwgVg.Warn.NoTargetDwg", "Check at least one target DWG.\n\nImport or link the same DWG into the target model, then run this command again." },
            { "DwgVg.Warn.NoLayers", "There are no layer settings to transfer." },

            { "DwgVg.Confirm.Title", "Transfer settings" },
            { "DwgVg.Confirm.Main", "Layer display settings of DWG \"{1}\" in \"{0}\" will be applied to DWG \"{3}\" in {2} view(s)." },
            { "DwgVg.Confirm.ViaTemplate", "{0} of them have a view template controlling the V/G of the Imported categories, so the settings are written to {1} view template(s) instead.\n* Other views using the same template are affected as well." },
            { "DwgVg.Confirm.ObjectStyles", "WARNING: \"Also match object styles\" is enabled. This rewrites the DWG line color, weight and pattern for the WHOLE MODEL, not just the selected views. Other views will change too." },
            { "DwgVg.Confirm.Content", "Existing settings in the target views will be overwritten. You can undo this with Ctrl+Z.\nContinue?" },
            { "DwgVg.Txn.Apply", "Transfer DWG layer display settings" },
            { "DwgVg.Result.Title", "Transfer result" },
            { "DwgVg.Result.Msg", "Applied display settings for {1} DWG layer(s) across {0} view(s)." },
            { "DwgVg.Result.ViaTemplate", "{0} of the views could not be written directly, so the settings were written to {1} view template(s)." },
            { "DwgVg.Result.WrittenTo", "Written to: {0}" },
            { "DwgVg.Result.None", "No settings could be applied." },
            { "DwgVg.Result.SourceEmpty", "* The selected source view / DWG has no settings that differ from the defaults. Pick a DWG whose \"Set N\" count is 1 or more in the source list." },
            { "DwgVg.Result.Failures", "Views that could not be updated: {0}" },
            { "DwgVg.Result.LogHint", "A detailed trace is written to C:\\temp\\Tools28_debug.txt." },
            { "DwgVg.Fail.ViewNotFound", "{0}: view not found" },
            { "DwgVg.Fail.NoLayerMatch", "{0}: no matching layer in the target DWG" },
            { "DwgVg.Fail.NotApplied", "{0}: the value did not change after writing {1}" },
            { "DwgVg.Fail.NoEffect", "{0}: the settings were written to \"{1}\" but did not reach this view. The view template most likely does not include \"Imported\" in its V/G settings (edit the template and tick Imported under V/G)" },
            { "DwgVg.Fail.TemplateNotApplied", "{0}: writing to view template \"{1}\" had no effect either {2}" },
            { "DwgVg.Result.HiddenBlocked", "Layers whose visibility could not be reproduced: {0} (Revit does not allow hiding them in this view)" },
            { "DwgVg.Result.MissingLayers", "Layers not found in the target DWG: {0}" },
            { "DwgVg.Result.MissingPatterns", "Line patterns missing in the target model (left at default): {0}" },
            { "DwgVg.Result.More", "and {0} more" },
            { "DwgVg.Result.Error", "An error occurred during the transfer:\n{0}" },

            // ===== バグ修正・多言語化対応で追加 =====
            { "Common.PartialFail", "Some views could not be updated.\nSucceeded: {0} / Failed: {1}" },
            { "Common.NoActiveView", "There is no active view." },
            { "Common.Need3DViewActive", "Activate a 3D view before running this command." },
            { "Common.Need3DViewOrSelect", "The active view is not a 3D view. Activate a 3D view, or select 3D views in the Project Browser." },
            { "Common.ErrorWithManual", "{0}\n\nManual: https://28tools.com/addins.html\nDownloads: https://28yu.github.io/28tools-download/" },
            { "Common.Txn.ClearViewTemplate", "Remove View Template" },
            { "ViewCopy.NothingCopied", "No camera position has been copied. Copy a 3D view's camera position first." },
            { "ViewCopy.TemplateNotSupported", "A camera position cannot be applied to a view template." },
            { "ViewCopy.NoValidView", "No valid 3D view is selected. Select 3D views that are not view templates." },
            { "ViewCopy.CopyError", "An error occurred while copying the camera position.\n{0}" },
            { "ViewCopy.PasteError", "An error occurred while applying the camera position.\n{0}" },
            { "ViewCopy.Txn.Paste", "Paste 3D View Camera Position" },
            { "SectionBox.NoRange", "The section box extents could not be read." },
            { "SectionBox.NothingCopied", "No section box has been copied. Copy a section box first." },
            { "SectionBox.NoView3DSelected", "The selection contains no 3D view. Select 3D views." },
            { "SectionBox.CopyError", "An error occurred while copying the section box.\n{0}" },
            { "SectionBox.PasteError", "An error occurred while pasting the section box.\n{0}" },
            { "SectionBox.Txn.Paste", "Paste Section Box Extents" },
            { "CropBox.UnsupportedViewType", "This view type ({0}) is not supported." },
            { "CropBox.NothingCopied", "No crop region has been copied. Copy a crop region first." },
            { "CropBox.NoValidView", "No supported view is selected." },
            { "CropBox.CopyError", "Failed to copy the crop region.\n{0}" },
            { "CropBox.PasteError", "Failed to apply the crop region.\n{0}" },
            { "CropBox.Txn.Paste", "Apply Crop Region" },
            { "ViewportPos.NeedSheet", "Activate a sheet before running this command." },
            { "ViewportPos.NeedViewport", "Select a viewport before running this command." },
            { "ViewportPos.NoViewportInSelection", "The selection contains no viewport. Select a viewport placed on a sheet." },
            { "ViewportPos.MultipleViewports", "Multiple viewports are selected. Select a single viewport." },
            { "ViewportPos.NothingCopied", "No position has been copied. Run the position copy command first." },
            { "ViewportPos.NeedTarget", "Select a viewport, a sheet, or a view before running this command." },
            { "ViewportPos.CopyError", "An error occurred while copying the position.\n{0}" },
            { "ViewportPos.PasteError", "An error occurred while pasting the position.\n{0}" },
            { "ViewportPos.Txn.Paste", "Change Viewport Position" },
            { "Sheet.NoTitleBlockLoaded.Main", "No title block family is loaded" },
            { "Sheet.NoTitleBlockLoaded.Content", "Load a title block family into the project first.\n\nInsert tab -> Load Family -> Titleblocks" },
            { "Sheet.NoTitleBlockSelected", "No title block is selected." },
            { "Sheet.TitleBlockFailed", "Failed to get the title block." },
            { "Sheet.NewSheetName", "New Sheet {0}" },
            { "Sheet.Result.Title", "Sheets Created" },
            { "Sheet.Result.Main", "Created {0} sheet(s)" },
            { "Sheet.Result.Detail", "Title block: {0}\nSheet number: {1}" },
            { "Sheet.Result.DetailRange", "Title block: {0}\nSheet numbers: {1} - {2}" },
            { "Sheet.ProcessError", "An error occurred while creating sheets.\n\n{0}" },
            { "Sheet.Txn.Create", "Create Sheets" },
            { "BeamTop.ProcessError", "An error occurred while colouring beams by top level.\n\n{0}" },
            { "BeamUnder.ProcessError", "An error occurred while colouring beams by bottom level.\n\n{0}" },
            { "RoomTag.ProcessError", "An error occurred while placing room tags.\n\n{0}" },
            { "Fire.ProcessError", "An error occurred while colouring fire protection.\n\n{0}" },
            { "BeamTop.Txn.Apply", "Colour Beams by Top Level" },
            { "BeamUnder.Txn.Apply", "Colour Beams by Bottom Level" },
            { "Fire.Txn.Apply", "Colour Fire Protection" },
            { "Fire.Txn.PlaceLegend", "Place Legend on Sheet" },
            { "Room3D.Txn.Group", "Colour Rooms in 3D" },
            { "Room3D.Txn.EnableVolume", "Enable Volume Computation" },
            { "Room3D.Txn.Generate", "Generate and Colour Room Solids" },
            { "RoomTag.Txn.Group", "Place Room Tags" },
            { "RoomTag.Txn.CreateView", "Create View" },
            { "RoomTag.Txn.CreateTags", "Create Room Tags" },
            { "GridBubble.Txn.Both", "Toggle Bubbles on Both Ends" },
            { "GridBubble.Txn.Left", "Toggle Bubble on Left End" },
            { "GridBubble.Txn.Right", "Toggle Bubble on Right End" },
            { "FilledRegion.Txn.Apply", "Split / Merge Filled Regions" },
            { "Import.Txn", "Excel Import" },
            { "Formwork.Txn.Params", "Formwork Quantities - Shared Parameters" },
            { "Formwork.Txn.Workset", "Formwork Quantities - Create Workset" },
            { "Formwork.Txn.View", "Formwork Quantities - Create View" },
            { "Formwork.Txn.HideOtherViews", "Formwork Quantities - Hide in Other Views" },
            { "Formwork.Txn.DeleteSheet", "Formwork Quantities - Delete Existing Sheet" },
            { "Formwork.Txn.Sheet", "Formwork Quantities - Create Sheet" },
            { "Common.Other", "Other: " },
            { "BeamUnder.SelectUpperLevel", "Select an upper level." },
            { "Import.SelectExcelFile", "Select an Excel File" },
            // ===== GenericModelMerge =====
            { "Ribbon.Panel.Model", "Model" },
            { "Ribbon.GmMerge", "Merge to Generic Model" },
            { "Ribbon.GmMerge.Tip", "Reads the shapes of elements visible in the current 3D view, across any categories, and builds them into a single generic model. Can be created either as a DirectShape or as a generic model family (.rfa)." },
            { "GmMerge.Title", "Merge to Generic Model" },
            { "GmMerge.Txn.Create", "Merge to Generic Model" },
            { "GmMerge.Description", "Reads the shapes of the elements shown in this 3D view and builds them into one generic model. Only elements visible in the view are used - the section box, view filters and hidden-element settings all apply as they are." },
            { "GmMerge.Categories", "Target categories" },
            { "GmMerge.Categories.Hint", "Only elements in the checked categories are used. The number in brackets is how many elements were found in this view." },
            { "GmMerge.SelectAll", "Select all" },
            { "GmMerge.DeselectAll", "Clear all" },
            { "GmMerge.Output", "1. What to create" },
            { "GmMerge.Output.DirectShape", "Create a DirectShape (quick)" },
            { "GmMerge.Output.DirectShape.Hint", "Places the merged shape straight into this project. No extra file, and it finishes quickly. It is not a family, so you cannot edit its shape later or reuse it in another model." },
            { "GmMerge.Output.Family", "Create a generic model family (.rfa) (reusable)" },
            { "GmMerge.Output.Family.Hint", "Creates a family file (.rfa), then loads and places it in this project. You will be asked where to save it. Being a family, it can be reused in other models and edited later in the family editor. This takes a little longer." },
            { "GmMerge.Combine", "2. How to merge them" },
            { "GmMerge.Combine.Keep", "Keep the shapes, merge only into one element (recommended)" },
            { "GmMerge.Combine.Keep.Hint", "Keeps every original shape as it is and merges them into a single Revit element. Nothing can fail, so this is the safest option. Overlapping parts stay overlapped." },
            { "GmMerge.Combine.UnionAll", "Fuse everything into one shape" },
            { "GmMerge.Combine.UnionAll.Hint", "Fuses overlapping and touching parts into a single true solid, so sections join cleanly and the volume is correct. On complex geometry some parts may not fuse; those are kept in their original form." },
            { "GmMerge.Combine.UnionTouching", "Fuse only the parts that touch" },
            { "GmMerge.Combine.UnionTouching.Hint", "Fuses elements that touch each other and keeps separate ones as separate shapes inside the same generic model. Good when you only want continuous parts, such as a column and beam, to become one." },
            { "GmMerge.Detail", "3. Finishing" },
            { "GmMerge.Material", "Material" },
            { "GmMerge.Material.Hint", "This material is applied to the whole generic model. The materials of the original elements are not carried over." },
            { "GmMerge.Name", "Name" },
            { "GmMerge.Name.Hint", "Name of the element to create." },
            { "GmMerge.Name.Hint.Family", "Name of the family to create. It is also used as the default file name of the .rfa." },
            { "GmMerge.HideSource", "Hide the original elements in this view" },
            { "GmMerge.HideSource.Hint", "The original elements are not deleted. They are only hidden in this view, so other views and the model itself are unaffected." },
            { "GmMerge.Btn.Run", "Create generic model" },
            { "GmMerge.Summary", "Selected: {0} categories / {1} elements" },
            { "GmMerge.DefaultName", "MergedGenericModel" },
            { "GmMerge.SaveFamily.Title", "Save the generic model family" },
            { "GmMerge.SaveFamily.Filter", "Revit family" },
            { "GmMerge.SelectTemplate.Prompt", "The generic model family template (.rft) could not be found automatically. Please select it manually in the next dialog." },
            { "GmMerge.SelectTemplate.Title", "Select the generic model family template" },
            { "GmMerge.SelectTemplate.Filter", "Family template" },
            { "GmMerge.Confirm.Many", "{0} elements are selected. This may take a while. Continue?" },
            { "GmMerge.Err.NoDoc", "No project is open." },
            { "GmMerge.Err.Not3DView", "Please run this command in a 3D view.\n\nBecause it works with solid geometry, it is limited to 3D views where you can see the target range set by the section box and view filters." },
            { "GmMerge.Err.NoElement", "No model elements were found in this view." },
            { "GmMerge.Err.NoCategory", "Please select at least one category." },
            { "GmMerge.Err.NoName", "Please enter a name." },
            { "GmMerge.Err.NoSolid", "No solid geometry could be read from the selected elements.\n\nOnly elements without solid geometry (grids, levels, lines and so on) may have been selected." },
            { "GmMerge.Err.NoTemplate", "Cancelled because no family template was selected." },
            { "GmMerge.Err.FamilyFailed", "Failed to create the family file.\n\n{0}" },
            { "GmMerge.Err.LoadFailed", "The created family could not be loaded into the project." },
            { "GmMerge.Err.EmptyResult", "The generic model that was created contained no geometry, so the operation was undone. The model is unchanged.\n\n{0}" },
            { "GmMerge.Result.Created", "Created a generic model with {1} shapes from {0} elements." },
            { "GmMerge.Result.SavedTo", "Family saved to: {0}" },
            { "GmMerge.Result.Hidden", "Hid {0} original elements in this view." },
            { "GmMerge.Result.NoGeometry", "Elements skipped because they have no solid geometry: {0}" },
            { "GmMerge.Result.UnionFailed", "Shapes kept in their original form because they could not be fused: {0}" },
            { "GmMerge.Result.ShapeFailed", "Shapes that could not be added to the family: {0}" },
            { "GmMerge.Result.MaterialSkipped", "The material was not applied because there are too many faces (the shape itself was created normally)." },
            { "GmMerge.Result.MaterialFailed", "The material could not be applied (the shape itself was created normally)." },
            { "Common.RevitWarnings", "Warnings reported by Revit:" },
            { "Formwork.Sheet.ConfirmDelete.Title", "Confirm Deleting an Existing Sheet" },
            { "Formwork.Sheet.ConfirmDelete.Main", "A sheet named \"{0} - {1}\" was found." },
            { "Formwork.Sheet.ConfirmDelete.Content", "This sheet has no record of being created by 28 Tools. It may have been created manually.\n\nIf you continue, the sheet will be deleted and rebuilt from this run. Any other views or viewports placed on it will be lost.\n\nDelete and rebuild it?\nChoose No to skip sheet creation." },
            { "Formwork.Sheet.Skipped", "Sheet creation was skipped because deleting the existing sheet was cancelled." },
            { "Export.Header.ElementId", "Element ID" },
            { "Export.Header.Category", "Category" },
            { "Export.SheetName.Merged", "Data" },
            { "Export.Marker.ReadOnly", "(*Read-only)" },
            { "Export.Marker.Image", "(*Image ref/no text)" },
            { "Export.Marker.Reference", "(*Element ref/name required)" },
            { "Sheet.Mode", "Creation method:" },
            { "Sheet.Mode.Count", "Create a numbered series by count" },
            { "Sheet.Mode.List", "Create from a list of numbers and names" },
            { "Sheet.List", "Sheet list:" },
            { "Sheet.ListHint", "One sheet per line, in the form \"Sheet number[Tab]Sheet name\". You can paste two columns straight from Excel." },
            { "Sheet.ListEmpty", "The sheet list is empty. Enter one sheet per line." },
            { "Sheet.Result.Skipped", "Skipped because the sheet number already exists: {0}" },
        };
    }
}
