using System.Collections.Generic;

namespace Tools28.Localization
{
    internal static class StringsJP
    {
        internal static readonly Dictionary<string, string> All = new Dictionary<string, string>
        {
            // === Ribbon: Panel Names ===
            { "Ribbon.Panel.GridBubble", "符号 ON/OFF" },
            { "Ribbon.Panel.SheetView", "シート・ビュー" },
            { "Ribbon.Panel.3DView", "3Dビュー" },
            { "Ribbon.Panel.Annotation", "注釈・詳細" },
            { "Ribbon.Panel.Structural", "色分け" },
            { "Ribbon.Panel.Quantity", "数量算出" },
            { "Ribbon.Panel.Excel", "Excel連携" },
            { "Ribbon.Panel.Settings", "設定" },

            // === Ribbon: GridBubble ===
            { "Ribbon.GridBubble.Both", "両端" },
            { "Ribbon.GridBubble.Both.Tip", "通り芯・レベルの符号を両端に表示します" },
            { "Ribbon.GridBubble.Left", "左端" },
            { "Ribbon.GridBubble.Left.Tip", "通り芯・レベルの符号を左端のみに表示します" },
            { "Ribbon.GridBubble.Right", "右端" },
            { "Ribbon.GridBubble.Right.Tip", "通り芯・レベルの符号を右端のみに表示します" },

            // === Ribbon: Sheet/View ===
            { "Ribbon.Sheet.Create", "一括作成" },
            { "Ribbon.Sheet.Create.Tip", "図枠を指定して複数のシートを一括作成します" },
            { "Ribbon.Viewport.Copy", "ビューポート\n位置コピー" },
            { "Ribbon.Viewport.Copy.Tip", "シート上のビューポート位置をコピーします" },
            { "Ribbon.Viewport.Paste", "ビューポート\n位置ペースト" },
            { "Ribbon.Viewport.Paste.Tip", "コピーしたビューポート位置を他のシートに適用します" },
            { "Ribbon.CropBox.Copy", "トリミング\n領域コピー" },
            { "Ribbon.CropBox.Copy.Tip", "ビューのトリミング領域をコピーします" },
            { "Ribbon.CropBox.Paste", "トリミング\n領域ペースト" },
            { "Ribbon.CropBox.Paste.Tip", "コピーしたトリミング領域を他のビューに適用します" },

            // === Ribbon: 3D View ===
            { "Ribbon.View.Copy", "視点コピー" },
            { "Ribbon.View.Copy.Tip", "3Dビューの視点をコピーします" },
            { "Ribbon.View.Paste", "視点ペースト" },
            { "Ribbon.View.Paste.Tip", "コピーした視点を他の3Dビューに適用します" },
            { "Ribbon.SectionBox.Copy", "切断ボックス\nコピー" },
            { "Ribbon.SectionBox.Copy.Tip", "3Dビューの切断ボックスをコピーします" },
            { "Ribbon.SectionBox.Paste", "切断ボックス\nペースト" },
            { "Ribbon.SectionBox.Paste.Tip", "コピーした切断ボックスを他の3Dビューに適用します" },

            // === Ribbon: Annotation ===
            { "Ribbon.RoomTag", "部屋タグ\n自動配置" },
            { "Ribbon.RoomTag.Tip", "ビューポート内の部屋タグを指定方向・間隔で自動配置します" },
            { "Ribbon.FilledRegion", "塗潰し領域\n分割･統合" },
            { "Ribbon.FilledRegion.Tip", "配置されている塗潰領域を分割/統合します" },

            // === Ribbon: Structural ===
            { "Ribbon.BeamUnder", "梁下端\n色分け" },
            { "Ribbon.BeamUnder.Tip", "天井伏図の梁下端レベルを自動算出し、レベル別に色分け表示します" },
            { "Ribbon.BeamTop", "梁天端\n色分け" },
            { "Ribbon.BeamTop.Tip", "平面ビューの梁天端レベルをパラメータから取得し、レベル別に色分け表示します" },
            { "Ribbon.FireProtection", "耐火被覆\n色分け" },
            { "Ribbon.FireProtection.Tip", "梁の耐火被覆範囲を自動検出し、種類別に色分けした塗潰領域を作成します" },

            // === Ribbon: Quantity ===
            { "Ribbon.Formwork", "型枠" },
            { "Ribbon.Formwork.Tip", "躯体モデルから型枠数量（面積）を自動算出し、Excel/Revit集計表/色分け3Dビューを出力します" },

            // === Ribbon: Excel ===
            { "Ribbon.Excel.Export", "Excel\nエクスポート" },
            { "Ribbon.Excel.Export.Tip", "パラメータをExcelに書き出します" },
            { "Ribbon.Excel.Import", "Excel\nインポート" },
            { "Ribbon.Excel.Import.Tip", "Excelからパラメータを読み込みます" },

            // === Ribbon: Settings ===
            { "Ribbon.Settings.Lang.Tip", "UIの表示言語を切り替えます (JP / US / CN)" },
            { "Ribbon.Settings.About", "バージョン情報" },
            { "Ribbon.Settings.About.Tip", "28 Tools のバージョン情報を表示します" },
            { "Ribbon.Settings.Manual", "マニュアル" },
            { "Ribbon.Settings.Manual.Tip", "28 Tools のマニュアルをブラウザで開きます" },
            { "Ribbon.Settings.Lang.JP.Tip", "日本語に切り替えます" },
            { "Ribbon.Settings.Lang.US.Tip", "Switch to English" },
            { "Ribbon.Settings.Lang.CN.Tip", "切换为中文" },

            // === Common ===
            { "Common.Error", "エラー" },
            { "Common.Warning", "警告" },
            { "Common.Confirm", "確認" },
            { "Common.Complete", "完了" },
            { "Common.OK", "OK" },
            { "Common.Cancel", "キャンセル" },
            { "Common.Next", "次へ" },
            { "Common.Back", "戻る" },
            { "Common.Execute", "実行" },
            { "Common.Create", "作成" },
            { "Common.Search", "検索" },
            { "Common.InputError", "入力エラー" },
            { "Common.ProcessComplete", "処理完了" },
            { "Common.StepIndicator", "ステップ {0} / {1}  {2}" },

            // === Application.cs ===
            { "App.StartupFailed", "アドインの起動に失敗しました。\n{0}" },

            // === About ===
            { "About.Title", "28 Tools について" },
            { "About.Message", "28 Tools\nバージョン: {0}\n有効期限: {1} {2}\n\nRevit 向け業務効率化アドイン" },
            { "About.RemainingSuffix", "(残り {0} 日)" },
            { "About.ExpiredSuffix", "(期限切れ)" },

            // === SheetCreation Dialog ===
            { "Sheet.Title", "シート一括作成" },
            { "Sheet.SelectTitleBlock", "図枠を選択:" },
            { "Sheet.Count", "作成枚数:" },
            { "Sheet.CountHint", "※ 1～100の範囲で入力してください" },
            { "Sheet.DrawingNo", "図面No:" },
            { "Sheet.DrawingNoHint", "※ 空欄の場合は図面Noなし（例: D-駐住, A-棟, など）" },
            { "Sheet.NoTitleBlock", "プロジェクトに図枠ファミリがロードされていません。" },
            { "Sheet.SelectTitleBlockWarn", "図枠を選択してください。" },
            { "Sheet.CountRange", "作成枚数は1～100の範囲で入力してください。" },

            // === FilledRegion Dialog ===
            { "FilledRegion.Title", "塗潰し領域 分割/統合" },
            { "FilledRegion.Operation", "操作" },
            { "FilledRegion.Split", "分割（複数エリアを持つ領域を個別の領域に分割）" },
            { "FilledRegion.Merge", "統合（複数の領域を1つの領域に統合）" },
            { "FilledRegion.Pattern", "塗り潰しパターン" },
            { "FilledRegion.SelectPattern", "統合後の塗り潰しパターンを選択してください：" },
            { "FilledRegion.SelectFirst", "塗り潰し領域を選択してから、このコマンドを実行してください。" },
            { "FilledRegion.NoneSelected", "塗り潰し領域が選択されていません。\n塗り潰し領域を選択してから、このコマンドを実行してください。" },
            { "FilledRegion.NoneAvailable", "分割または統合できる塗り潰し領域がありません。\n\n• 分割: 複数のエリアを持つ領域を選択してください\n• 統合: 複数の領域を選択してください" },
            { "FilledRegion.SelectOperation", "操作（分割または統合）を選択してください。" },
            { "FilledRegion.SelectPatternWarn", "塗り潰しパターンを選択してください。" },
            { "FilledRegion.ProcessError", "処理中にエラーが発生しました。\n\n{0}" },
            { "FilledRegion.InfoSplit", "選択: {0}個の領域（分割可能: {1}個、合計{2}エリア）" },
            { "FilledRegion.InfoMerge", "選択: {0}個の領域（合計{1}エリア）→ 1個の領域に統合" },
            { "FilledRegion.InfoGeneral", "選択: {0}個の領域" },
            { "FilledRegion.SplitResult", "{0}個の領域を{1}個の独立した領域に分割しました。" },
            { "FilledRegion.MergeResult", "{0}個の領域を1個の領域に統合しました。" },

            // === RoomTag Dialog ===
            { "RoomTag.Title", "部屋タグ自動配置" },
            { "RoomTag.ViewName", "ビュー名:" },
            { "RoomTag.ViewFamilyType", "ビューファミリタイプ:" },
            { "RoomTag.FloorPlan", "仕上表__平面図" },
            { "RoomTag.CeilingPlan", "仕上表__天井伏図" },
            { "RoomTag.TagFamilyType", "タグファミリタイプ:" },
            { "RoomTag.TagSpacing", "タグ間隔 (mm):" },
            { "RoomTag.RoomList", "部屋リスト:" },
            { "RoomTag.MoveUp", "上へ移動" },
            { "RoomTag.MoveDown", "下へ移動" },
            { "RoomTag.Delete", "項目を削除" },
            { "RoomTag.UnclosedHint", "*は未閉鎖部屋を示す" },
            { "RoomTag.Preview", "配置プレビュー:" },
            { "RoomTag.IncRows", "行数を増やす" },
            { "RoomTag.DecRows", "行数を減らす" },
            { "RoomTag.OpenSheet", "シートビューを開いた状態で実行してください。" },
            { "RoomTag.NoViewport", "ビューポートが取得できませんでした。" },
            { "RoomTag.NoView", "ビューポートのビューが取得できませんでした。" },
            { "RoomTag.NoRooms", "選択したビューポート内に部屋が見つかりません。" },
            { "RoomTag.NoViewType", "ビューファミリタイプが選択されていません。" },
            { "RoomTag.NoTagType", "タグファミリタイプが選択されていません。" },
            { "RoomTag.NoLayout", "配置設定が取得できませんでした。" },
            { "RoomTag.GenFailed", "部屋タグの生成に失敗しました。" },
            { "RoomTag.GenError", "部屋タグの生成中にエラーが発生しました。\n{0}" },
            { "RoomTag.Done", "部屋タグの自動配置が完了しました。\n\nビュー名: {0}\n配置枚数: {1}個" },
            { "RoomTag.EnterViewName", "ビュー名を入力してください。" },
            { "RoomTag.SelectRooms", "部屋が選択されていません。" },
            { "RoomTag.SelectTagType", "タグファミリタイプを選択してください。" },
            { "RoomTag.InvalidSpacing", "タグ間隔には0以上の数値を入力してください。" },

            // === BeamTopLevel Dialog ===
            { "BeamTop.Title", "梁天端色分け" },
            { "BeamTop.Step1", "ステップ 1 / 3  基本設定" },
            { "BeamTop.ViewInfo", "ビュー情報" },
            { "BeamTop.ViewName", "ビュー名:" },
            { "BeamTop.BeamCount", "梁数:" },
            { "BeamTop.RefLevel", "参照レベル:" },
            { "BeamTop.TextTypeSetting", "文字タイプ設定" },
            { "BeamTop.LegendTextType", "凡例の文字タイプ:" },
            { "BeamTop.LabelTextType", "梁ラベルの文字タイプ:" },
            { "BeamTop.TextTypeHint", "※ 凡例は製図ビューの文字、梁ラベルは平面ビュー上の梁に表示する文字です" },
            { "BeamTop.ParamSelect", "梁天端レベルパラメータ選択" },
            { "BeamTop.ParamHint", "※ ファミリ毎に梁天端レベル（参照レベルからのオフセット）として使用するパラメータを選択してください" },
            { "BeamTop.Summary", "処理概要" },
            { "BeamTop.ProcessContent", "処理内容" },
            { "BeamTop.SharedParam", "共有パラメータ作成・バインド" },
            { "BeamTop.GetValue", "梁天端レベル値の取得・書き込み" },
            { "BeamTop.CreateFilter", "フィルタ自動作成・色分け" },
            { "BeamTop.CreateLegend", "凡例の製図ビュー作成" },
            { "BeamTop.ExistingFilter", "既存フィルタについて" },
            { "BeamTop.OverwriteFilter", "既存の「梁天端_」フィルタを上書きする" },
            { "BeamTop.OverwriteHint", "※ チェックを���すと既存フィルタはそのまま残ります" },
            { "BeamTop.StepName1", "基本設定" },
            { "BeamTop.StepName2", "梁天端レベルパラメータ選択" },
            { "BeamTop.StepName3", "処理確認" },
            { "BeamTop.NotPlanView", "アクティブビューが平面ビューまたは構造伏図ではありません。\n平面ビューまたは構造伏図を開いた状態で実行してください。" },
            { "BeamTop.ViewTemplate", "ビューテンプレート確認" },
            { "BeamTop.ViewTemplateMsg", "ビューテンプレートが設定されています。\nフィルタを作成するにはテンプレートを解除する必要があります。\n\nテンプレートを解除しますか？" },
            { "BeamTop.NoBeams", "ビュー内に梁（構造フレーム）が見つかりません。" },
            { "BeamTop.NoRefLevel", "ビューの参照レベルが取得できません。" },
            { "BeamTop.DoneTitle", "梁天端色分け - 完了" },

            // === BeamUnderLevel Dialog ===
            { "BeamUnder.Title", "梁下端色分け" },
            { "BeamUnder.Step1", "ステップ 1 / 4  レベル設定、凡例設定" },
            { "BeamUnder.ViewInfo", "ビュー情報" },
            { "BeamUnder.ViewName", "ビュー名:" },
            { "BeamUnder.BeamCount", "梁数:" },
            { "BeamUnder.TextTypeSetting", "文字タイプ設定" },
            { "BeamUnder.LegendTextType", "凡例の文字タイプ:" },
            { "BeamUnder.LabelTextType", "梁ラベルの文字タイプ:" },
            { "BeamUnder.TextTypeHint", "※ 凡例は製図ビューの文字、梁ラベルは天井伏図上の梁に表示する文字です" },
            { "BeamUnder.LevelSetting", "レベル設定" },
            { "BeamUnder.RefLevel", "参照レベル:" },
            { "BeamUnder.UpperLevel", "上位レベル:" },
            { "BeamUnder.FloorHeight", "階高:" },
            { "BeamUnder.LevelHint", "※ 参照レベルを基準として梁下端レベルを算出します" },
            { "BeamUnder.HeightParam", "梁高さパラメータ選択" },
            { "BeamUnder.HeightParamHint", "※ ファミリ毎に梁高さとして使用するパラメータを選択してください" },
            { "BeamUnder.TopParam", "梁天端レベルパラメータ選択" },
            { "BeamUnder.TopParamHint", "※ ファミリ毎に梁天端レベル（参照レベルからのオフセット）として使用するパラメータを選択してください" },
            { "BeamUnder.Summary", "処理概要" },
            { "BeamUnder.ProcessContent", "処理内容" },
            { "BeamUnder.SharedParam", "共有パラメータ作成・バインド" },
            { "BeamUnder.CalcValue", "梁下レベル値の計算・書き込み" },
            { "BeamUnder.CreateFilter", "フィルタ自動作成・色分け" },
            { "BeamUnder.CreateLegend", "凡例の製図ビュー作成" },
            { "BeamUnder.ExistingFilter", "既存フィルタについて" },
            { "BeamUnder.OverwriteFilter", "既存の「梁下_」フィルタを上書きする" },
            { "BeamUnder.OverwriteHint", "※ チェックを外すと既存フィルタはそのまま残ります" },
            { "BeamUnder.StepName1", "レベル設定、凡例設定" },
            { "BeamUnder.StepName2", "梁高さパラメータ選択" },
            { "BeamUnder.StepName3", "梁天端レベルパラメータ選択" },
            { "BeamUnder.StepName4", "処理確認" },
            { "BeamUnder.NotCeiling", "アクティブビューが天井伏図ではありません。\n天井伏図を開いた状態で実行してください。" },
            { "BeamUnder.ViewTemplate", "ビューテンプレート確認" },
            { "BeamUnder.ViewTemplateMsg", "ビューテンプレートが設定されています。\nフィルタを作成するにはテンプレートを解除する必要があります。\n\nテンプレートを解除しますか？" },
            { "BeamUnder.NoBeams", "ビュー内に梁（構造フレーム）が見つかりません。" },
            { "BeamUnder.NoRefLevel", "ビューの参照レベルが取得できません。" },
            { "BeamUnder.NoUpperLevel", "参照レベルより上のレベルが見つかりません。" },
            { "BeamUnder.DoneTitle", "梁下端色分け - 完了" },

            // === FireProtection Dialog ===
            { "Fire.Title", "耐火被覆 色分け" },
            { "Fire.Step1", "ステップ 1 / 3  基本設定" },
            { "Fire.ParamLabel", "耐火被覆パラメータ" },
            { "Fire.ParamHint", "※「耐火被覆」を含むパラメータを自動検出します" },
            { "Fire.DetectedTypes", "検出された耐火被覆の種類" },
            { "Fire.ColorHint", "※ 色の四角をクリックすると変更できます" },
            { "Fire.OffsetSetting", "塗り潰し領域のオフセット設定" },
            { "Fire.CommonOffset", "共通オフセット" },
            { "Fire.IndividualOffset", "種類ごとに個別オフセット" },
            { "Fire.Mm", " mm" },
            { "Fire.OffsetHint", "※ 梁のエッジからの距離（mm）" },
            { "Fire.BeamFace", "▽ 梁面" },
            { "Fire.ColumnSetting", "柱 耐火被覆設定" },
            { "Fire.ColumnDistA", "A: 柱中心からの距離:" },
            { "Fire.ColumnWidthB", "B: 外側の幅:" },
            { "Fire.ColumnHint", "※ 柱中心からA、そこから外側にB幅" },
            { "Fire.Column", "柱" },
            { "Fire.DisplaySetting", "表示設定" },
            { "Fire.LineStyle", "境界線の線種:" },
            { "Fire.FillPattern", "塗り潰し領域パターン:" },
            { "Fire.LegendTextType", "凡例の文字タイプ:" },
            { "Fire.Summary", "処理概要" },
            { "Fire.ProcessContent", "処理内容" },
            { "Fire.CreateTypes", "耐火被覆種類ごとの塗潰領域タイプ作成" },
            { "Fire.AutoPlace", "要素周囲に塗潰領域を自動配置（重なり部分は統合）" },
            { "Fire.CreateLegend", "凡例の製図ビュー作成" },
            { "Fire.ExistingLabel", "既存の耐火被覆について" },
            { "Fire.Overwrite", "既存の「耐火被覆_」塗潰領域・凡例を上書きする" },
            { "Fire.StepName1", "基本設定" },
            { "Fire.StepName2", "オフセット・表示設定" },
            { "Fire.StepName3", "処理確認" },
            { "Fire.NoViewOnSheet", "シート上に対応するビュー（平面、天伏、構造伏、断面）がありません。" },
            { "Fire.WrongView", "平面ビュー、天井伏図、構造伏図、断面図、またはシートで実行してください。" },
            { "Fire.NoElements", "ビュー内に梁（構造フレーム）または柱（構造柱）が見つかりません。" },
            { "Fire.DoneTitle", "耐火被覆色分け - 完了" },
            { "Fire.DoneMsg", "処理が完了しました。\n\n対象ビュー数: {0}\n塗潰領域数: {1}" },
            { "Fire.Foreground", "前景" },
            { "Fire.Background", "背景" },
            { "Fire.ParamDetected", "※ {0} 個のパラメータを検出しました" },
            { "Fire.ParamDetectedSuffix", "（{0}件検出）" },
            { "Fire.ParamNotFound", "※「耐火被覆」を含むパラメータが見つかりません" },
            { "Fire.NoParamValues", "耐火被覆パラメータに値が設定された要素がありません。\nパラメータを確認してください。" },
            { "Fire.CategoryBeam", "梁" },
            { "Fire.CategoryBeamColumn", "梁・柱" },
            { "Fire.SummaryView", "ビュー: {0}" },
            { "Fire.SummaryCategory", "対象カテゴリ: {0}" },
            { "Fire.SummaryParam", "耐火被覆パラメータ: {0}" },
            { "Fire.SummaryNone", "なし" },
            { "Fire.SummaryTypes", "検出された種類: {0}" },
            { "Fire.SummaryOffset", "  - {0}（オフセット: {1}mm）" },
            { "Fire.SummaryBorder", "境界線: {0}" },
            { "Fire.SummaryPattern", "塗りパターン: {0}" },

            // === ExcelExport Dialog ===
            { "Export.Title", "EXCELエクスポート" },
            { "Export.Category", "カテゴリを選択" },
            { "Export.Parameter", "パラメータ" },
            { "Export.Output", "出力" },
            { "Export.AddToOutput", "出力に追加" },
            { "Export.RemoveFromOutput", "出力から削除" },
            { "Export.MoveUp", "上へ移動" },
            { "Export.MoveDown", "下へ移動" },
            { "Export.SeparateSheets", "出力Excelをカテゴリ毎にシートに分ける" },
            { "Export.RestoreSettings", "設定復元" },
            { "Export.LoadSettings", "設定読込" },
            { "Export.SaveSettings", "設定保存" },
            { "Export.SettingsSaved", "設定を保存しました。" },
            { "Export.SettingsSaveTitle", "設定保存" },
            { "Export.SettingsSaveFailed", "設定の保存に失敗しました。\n{0}" },
            { "Export.SettingsLoadFailed", "設定の読み込みに失敗しました。\n{0}" },
            { "Export.SelectParams", "出力するパラメータを選択してください。" },
            { "Export.SelectCategory", "カテゴリを選択してください。" },
            { "Export.ParamPrefixLegend", "I- : インスタンス（要素）パラメータ\nT- : タイプパラメータ" },
            { "Export.Scope.WindowTitle", "EXCELエクスポート" },
            { "Export.Scope.Title", "書出し範囲の選択" },
            { "Export.Scope.Description", "書出す要素の範囲を選択してください。" },
            { "Export.Scope.Project", "プロジェクト全体の要素" },
            { "Export.Scope.View", "現在のビューにある要素" },
            { "Export.Scope.Selection", "現在選択されている要素" },

            // === ExcelImport Dialog ===
            { "Import.Title", "EXCELインポート" },
            { "Import.ExcelFile", "Excelファイル" },
            { "Import.OpenFile", "開いているファイル" },
            { "Import.Browse", "参照..." },
            { "Import.SheetInfo", "シート情報" },
            { "Import.SelectFile", "Excelファイルを選択してください" },
            { "Import.Preview", "変更プレビュー" },
            { "Import.ColElementId", "要素ID" },
            { "Import.ColCategory", "カテゴリ" },
            { "Import.ColParameter", "パラメータ" },
            { "Import.ColCurrentValue", "現在値" },
            { "Import.ColNewValue", "新しい値" },
            { "Import.Execute", "インポート実行" },
            { "Import.ResultTitle", "インポート結果" },
            { "Import.NoOpenFile", "開いているExcelファイルが見つかりません。" },
            { "Import.ReadFailed", "ファイルの読み込みに失敗しました。\n{0}" },

            // === FormworkCalculator Dialog ===
            { "Formwork.Title", "型枠数量算出" },
            { "Formwork.Scope.Header", "計算範囲" },
            { "Formwork.Scope.Project", "プロジェクト全体" },
            { "Formwork.Scope.View", "現在のビューに表示されている要素" },
            { "Formwork.Scope.SelectedViews", "選択のビュー" },
            { "Formwork.Group.Header", "集計区分" },
            { "Formwork.Group.Category", "部位別（柱・梁・壁・スラブ・基礎・階段・屋根）" },
            { "Formwork.Group.Zone", "工区別" },
            { "Formwork.Group.Type", "型枠種別" },
            { "Formwork.Group.ParamName", "パラメータ名:" },
            { "Formwork.Output.Header", "出力設定" },
            { "Formwork.Output.Excel", "Excel ファイルに出力" },
            { "Formwork.Output.Schedule", "集計表を作成" },
            { "Formwork.Output.View3D", "色分け 3D ビューを作成" },
            { "Formwork.Output.Sheet", "シートを作成" },
            { "Formwork.Color.Header", "色分け区分" },
            { "Formwork.Color.Category", "部位別" },
            { "Formwork.Color.Zone", "工区別" },
            { "Formwork.Color.Type", "型枠種別" },
            { "Formwork.Option.Header", "オプション" },
            { "Formwork.Option.ShowDeducted", "控除面も表示する" },
            { "Formwork.Option.IncludeLinks", "リンクモデルも対象に含める" },
            { "Formwork.NeedZoneParam", "工区別集計を有効にする場合は、工区パラメータ名を入力してください。" },
            { "Formwork.NeedTypeParam", "型枠種別集計を有効にする場合は、型枠種別パラメータ名を入力してください。" },
            { "Formwork.SaveExcelTitle", "型枠数量集計 - Excel 保存先" },
            { "Formwork.NoElements", "対象要素が見つかりませんでした。" },
            { "Formwork.CalcFailed", "型枠数量の計算中にエラーが発生しました。\n{0}" },
            { "Formwork.ExcelFailed", "Excel 出力中にエラーが発生しました。\n{0}" },
            { "Formwork.ViewFailed", "ビュー作成中にエラーが発生しました。\n{0}" },
            { "Formwork.DoneTitle", "型枠数量算出 - 完了" },
            { "Formwork.DoneMsg", "処理が完了しました。\n\n対象要素数: {0}\n型枠面積: {1:F2} ㎡\n控除面積: {2:F2} ㎡\n傾斜面（計算対象外）: {3:F2} ㎡" },
            { "Formwork.ExcelAt", "Excel 出力先: {0}" },
            { "Formwork.ErrorCount", "エラー・注記: {0} 件" },
            { "Formwork.Fatal", "型枠数量算出中に致命的なエラーが発生しました。\n{0}" },
            { "Formwork.ShapesCreated", "型枠面オブジェクト: {0} 個を作成（他ビューでは自動的に非表示）" },
            { "Formwork.ScheduleCreated", "集計表「型枠数量集計」を作成しました" },
            { "Formwork.SummaryScheduleCreated", "サマリ集計表「型枠数量集計_合計」を作成しました（要素削除に追従）" },
            { "Formwork.SheetCreated", "シート「{0} - {1}」を作成しました（3Dビューと集計表を自動配置）" },
            { "Formwork.SteelExcluded", "鉄骨部材 {0} 個を型枠不要として除外しました" },
            { "Formwork.DeckSlabExcluded", "デッキスラブ {0} 個を型枠不要として除外しました（タイプ名に \"DS\" を含む床）" },
            { "Formwork.WallSweepExcluded", "壁スイープ・リビール {0} 個を型枠不要として除外しました" },
            { "Formwork.SteelStairExcluded", "鉄骨階段 {0} 個を型枠不要として除外しました（タイプ名・マテリアルに鉄骨キーワードを含む階段）" },
            { "Formwork.LgsExcluded", "LGS壁 {0} 個を型枠不要として除外しました（石膏ボード層を含みコンクリート層を含まない壁）" },
            { "Formwork.LinkedIncluded", "リンクモデルから {0} 件の要素を対象に含めました（リンクインスタンス: {1} 個）" },
            { "Formwork.ExcludedFilterNote", "（除外要素は解析3Dビューの「型枠_除外」フィルタで非表示。表示 ON で確認可能）" },
            { "Formwork.UpdateConfirm.Title", "型枠数量算出 - 更新確認" },
            { "Formwork.UpdateConfirm.MainInstruction", "既存の型枠出力が見つかりました" },
            { "Formwork.UpdateConfirm.Content", "対象ビューに対応する分析3Dビューまたは集計表が既に存在します。実行モードを選択してください。" },
            { "Formwork.UpdateConfirm.UpdateLabel", "更新（既存のシートレイアウトを保持）" },
            { "Formwork.UpdateConfirm.UpdateDesc", "対象の分析3Dビューと集計表のみ最新モデルで更新します。シート・合計集計表・他のビューは変更しません。" },
            { "Formwork.UpdateConfirm.RecreateLabel", "再作成（全ての出力を作り直す）" },
            { "Formwork.UpdateConfirm.RecreateDesc", "シートと合計集計表を含む全ての出力を削除して再作成します。" },

            // === Excel エクスポート カテゴリ名（BuiltInCategory→ローカライズ）===
            { "Category.Walls", "壁" },
            { "Category.Floors", "床" },
            { "Category.Roofs", "屋根" },
            { "Category.Ceilings", "天井" },
            { "Category.Doors", "ドア" },
            { "Category.Windows", "窓" },
            { "Category.Stairs", "階段" },
            { "Category.Ramps", "スロープ" },
            { "Category.Railings", "手すり" },
            { "Category.Columns", "柱" },
            { "Category.StructuralColumns", "構造柱" },
            { "Category.StructuralFraming", "構造フレーム" },
            { "Category.StructuralFoundation", "構造基礎" },
            { "Category.StructuralTruss", "構造トラス" },
            { "Category.Rebar", "鉄筋" },
            { "Category.Stiffener", "スティフナー" },
            { "Category.Rooms", "部屋" },
            { "Category.Areas", "エリア" },
            { "Category.Furniture", "家具" },
            { "Category.FurnitureSystems", "システム家具" },
            { "Category.Casework", "造作家具" },
            { "Category.GenericModel", "一般モデル" },
            { "Category.SpecialityEquipment", "特殊設備" },
            { "Category.Site", "敷地" },
            { "Category.Topography", "地形" },
            { "Category.Planting", "植栽" },
            { "Category.Parking", "駐車場" },
            { "Category.Entourage", "エンタラージュ" },
            { "Category.Mass", "マス" },
            { "Category.CurtainPanels", "カーテンパネル" },
            { "Category.CurtainMullions", "カーテンマリオン" },
            { "Category.Ducts", "ダクト" },
            { "Category.DuctFittings", "ダクト継手" },
            { "Category.DuctAccessories", "ダクト付属品" },
            { "Category.AirTerminals", "空気端末" },
            { "Category.Pipes", "配管" },
            { "Category.PipeFittings", "配管継手" },
            { "Category.PipeAccessories", "配管付属品" },
            { "Category.Conduits", "電線管" },
            { "Category.CableTrays", "ケーブルトレイ" },
            { "Category.ElectricalEquipment", "電気設備" },
            { "Category.ElectricalFixtures", "電気器具" },
            { "Category.LightingFixtures", "照明器具" },
            { "Category.LightingDevices", "照明装置" },
            { "Category.MechanicalEquipment", "機械設備" },
            { "Category.PlumbingFixtures", "衛生器具" },
            { "Category.Sprinklers", "スプリンクラー" },
            { "Category.FireAlarmDevices", "火災警報装置" },
            { "Category.DataDevices", "データ装置" },
            { "Category.CommunicationDevices", "通信装置" },
            { "Category.SecurityDevices", "セキュリティ装置" },
            { "Category.NurseCallDevices", "ナースコール装置" },
            { "Category.TelephoneDevices", "電話装置" },
            { "Category.Grids", "通り芯" },
            { "Category.Levels", "レベル" },
            { "Category.Sheets", "シート" },
            { "Category.Views", "ビュー" },
            { "Category.Viewports", "ビューポート" },
            { "Category.TextNotes", "テキスト" },
            { "Category.GenericAnnotation", "一般注釈" },
            { "Category.RevisionClouds", "改訂雲" },
            { "Category.Schedules", "集計表" },

            { "Expiry.Title", "28 Tools - 使用期限" },
            { "Expiry.ExpiredMessage", "このバージョンの使用期限（{0}）が切れました。\n\n最新版を以下からダウンロードしてください：\nhttps://28tools.com/addins.html" },
            { "Expiry.WarningTitle", "28 Tools - 期限切れ間近" },
            { "Expiry.WarningMessage", "このバージョンの使用期限まで残り {0} 日です（期限: {1}）。\n\n最新版へのアップデートをご検討ください：\nhttps://28tools.com/addins.html" },

            // 塗潰しパターン入出力
            { "Ribbon.FillPatternIO", "塗潰しパターン\n入出力" },
            { "Ribbon.FillPatternIO.Tip", "rvtファイル内の塗り潰しパターンを一覧表示し、.patファイルへの書き出し／読み込みを行います。" },
            { "FillPatternIO.Title", "塗潰しパターン入出力" },
            { "FillPatternIO.PatternType", "パターン タイプ" },
            { "FillPatternIO.Search", "検索:" },
            { "FillPatternIO.ColPreview", "パターン" },
            { "FillPatternIO.Model", "モデル" },
            { "FillPatternIO.Drafting", "製図" },
            { "FillPatternIO.SelectAll", "全選択" },
            { "FillPatternIO.ClearAll", "全解除" },
            { "FillPatternIO.ColName", "名前" },
            { "FillPatternIO.ColType", "種類" },
            { "FillPatternIO.ColGrid", "グリッド数" },
            { "FillPatternIO.Unit", "単位:" },
            { "FillPatternIO.Export", "エクスポート" },
            { "FillPatternIO.Import", "インポート" },
            { "FillPatternIO.Close", "閉じる" },
            { "FillPatternIO.CountInfo", "全 {0} 件 / 選択 {1} 件" },
            { "FillPatternIO.PatFilter", "パターンファイル (*.pat)|*.pat|すべてのファイル (*.*)|*.*" },
            { "FillPatternIO.SelectFolder", "書き出し先のフォルダを選択してください（各パターンを個別の.patファイルとして保存します）。" },
            { "FillPatternIO.NoSelection", "書き出すパターンを一覧から選択してください。" },
            { "FillPatternIO.OnlySolid", "選択されたパターンはソリッド塗り潰しのみです。ソリッド塗り潰しは.pat形式で書き出せません。" },
            { "FillPatternIO.NoDocument", "アクティブなドキュメントがありません。rvtファイルを開いてから実行してください。" },
            { "FillPatternIO.TransImport", "塗潰しパターンのインポート" },
            { "FillPatternIO.ExportDone", "{0} 件のパターンを書き出しました。" },
            { "FillPatternIO.SolidSkipped", "（ソリッド塗り潰し {0} 件はスキップしました）" },
            { "FillPatternIO.ImportDone", "{0} 件のパターンを読み込みました。" },
            { "FillPatternIO.DupSkipped", "（同名の既存パターン {0} 件はスキップしました）" },
            { "FillPatternIO.InvalidSkipped", "（無効なパターン {0} 件はスキップしました）" },
            { "FillPatternIO.ExportError", "書き出し中にエラーが発生しました：\n{0}" },
            { "FillPatternIO.ImportError", "読み込み中にエラーが発生しました：\n{0}" },
            { "FillPatternIO.ProcessError", "処理中にエラーが発生しました：\n{0}" },

            // === ParameterCleanup（パラメータ整理）===
            { "Ribbon.Panel.Parameter", "パラメータ" },
            { "Ribbon.ParamCleanup", "パラメータ整理" },
            { "Ribbon.ParamCleanup.Tip", "プロジェクト内の削除可能なパラメータ（プロジェクト／共有／グローバル）を一覧表示し、同名パラメータの特定・値の有無の確認・不要（未使用）パラメータの削除を行います。大容量モデルでもフリーズしないよう、値の確認は必要なときだけ実行され、進捗表示と中止に対応します。" },
            { "ParamCleanup.Title", "パラメータ整理" },
            { "ParamCleanup.Description", "プロジェクト内の削除可能なパラメータを一覧表示し、各パラメータに値が入った要素があるかを自動で確認します。同名のパラメータは強調表示されます。不要（空）なパラメータを選択して削除できます。" },
            { "ParamCleanup.SortHint", "列見出しをクリックで並べ替え" },
            { "ParamCleanup.Search", "検索:" },
            { "ParamCleanup.DuplicateOnly", "同名のみ" },
            { "ParamCleanup.EmptyOnly", "空のみ" },
            { "ParamCleanup.SelectEmpty", "空を全選択" },
            { "ParamCleanup.SelectNotBound", "バインドなしを全選択" },
            { "ParamCleanup.SelectAll", "全選択" },
            { "ParamCleanup.DeselectAll", "選択解除" },
            { "ParamCleanup.Filter.Kind", "種別:" },
            { "ParamCleanup.Filter.All", "すべて" },
            { "ParamCleanup.Filter.SortAsc", "昇順で並べ替え" },
            { "ParamCleanup.Filter.SortDesc", "降順で並べ替え" },
            { "ParamCleanup.Filter.SelectAll", "(すべて選択)" },
            { "ParamCleanup.Filter.Blank", "(空白)" },
            { "ParamCleanup.Filter.Clear", "クリア" },
            { "ParamCleanup.Filter.CheckAll", "全選択" },
            { "ParamCleanup.Filter.UncheckAll", "選択解除" },
            { "ParamCleanup.FilterHint", "並べ替え・フィルター" },
            { "ParamCleanup.Col.Select", "選択" },
            { "ParamCleanup.Col.Name", "パラメータ名" },
            { "ParamCleanup.Col.Kind", "種別" },
            { "ParamCleanup.Col.Scope", "バインド" },
            { "ParamCleanup.Col.Categories", "対象カテゴリ" },
            { "ParamCleanup.Col.ScheduleRef", "集計表参照" },
            { "ParamCleanup.Col.Value", "値" },
            { "ParamCleanup.Btn.Check", "値の有無を確認" },
            { "ParamCleanup.Btn.Cancel", "中止" },
            { "ParamCleanup.Btn.Delete", "選択したパラメータを削除" },
            { "ParamCleanup.Btn.Close", "閉じる" },
            { "ParamCleanup.Kind.Project", "プロジェクト" },
            { "ParamCleanup.Kind.Shared", "共有" },
            { "ParamCleanup.Kind.Global", "グローバル" },
            { "ParamCleanup.Scope.Instance", "インスタンス" },
            { "ParamCleanup.Scope.Type", "タイプ" },
            { "ParamCleanup.State.Unchecked", "未確認" },
            { "ParamCleanup.State.Checking", "確認中…" },
            { "ParamCleanup.State.HasValue", "値あり" },
            { "ParamCleanup.State.Empty", "空（未使用）" },
            { "ParamCleanup.State.NotApplicable", "バインドなし" },
            { "ParamCleanup.Tip.HasValue", "値の入った要素が1件以上あります（使用中）。" },
            { "ParamCleanup.Tip.Empty", "バインド先カテゴリの全要素を確認しましたが、値が1件も入っていません（未使用）。" },
            { "ParamCleanup.Tip.Unchecked", "未確認です。「値の有無を確認」で判定できます。" },
            { "ParamCleanup.Tip.Checking", "確認中です…" },
            { "ParamCleanup.Tip.NotBound", "どのカテゴリにもバインドされていないため、値の有無を判定できません（定義のみ存在）。削除は可能です。" },
            { "ParamCleanup.Tip.Global", "グローバルパラメータの現在値です。" },
            { "ParamCleanup.Status.Scanning", "確認中: {0}" },
            { "ParamCleanup.Status.Done", "確認が完了しました。" },
            { "ParamCleanup.Status.DoneSummary", "確認完了 — 値あり: {0} 件 / 空: {1} 件" },
            { "ParamCleanup.Status.Cancelled", "確認を中止しました。" },
            { "ParamCleanup.Count.Summary", "全 {0} 件 / 表示 {1} 件 / 選択 {2} 件" },
            { "ParamCleanup.Count.Progress", "{0} / {1} 件" },
            { "ParamCleanup.Txn", "不要パラメータの削除" },
            { "ParamCleanup.NoDoc", "アクティブなプロジェクトがありません。" },
            { "ParamCleanup.NoSelection.Msg", "削除するパラメータが選択されていません。" },
            { "ParamCleanup.NotChecked.Msg", "先に「値の有無を確認」を実行してください。" },
            { "ParamCleanup.Confirm.Title", "パラメータの削除" },
            { "ParamCleanup.Confirm.Main", "選択した {0} 件のパラメータを削除します。この操作は元に戻せません。" },
            { "ParamCleanup.Confirm.Content", "注意: 値が空でも、ビューフィルタ・集計表・タグ・数式などで参照されているパラメータを削除すると、それらが機能しなくなる場合があります。削除前に内容をご確認ください。\n\n削除してもよろしいですか？" },
            { "ParamCleanup.Result.Title", "削除結果" },
            { "ParamCleanup.Result.Msg", "削除: {0} 件 / 失敗: {1} 件" },
            { "ParamCleanup.Result.Error", "削除中にエラーが発生しました：\n{0}" },
        };
    }
}
